// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytes.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteOwnerAnalyteAlias = `-- name: DeleteOwnerAnalyteAlias :execrows
DELETE FROM analyte_aliases WHERE id = $1 AND user_id = $2::uuid
`

type DeleteOwnerAnalyteAliasParams struct {
	ID     int64
	UserID uuid.UUID
}

func (q *Queries) DeleteOwnerAnalyteAlias(ctx context.Context, arg DeleteOwnerAnalyteAliasParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOwnerAnalyteAlias, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findAnalyteByLabel = `-- name: FindAnalyteByLabel :one
SELECT an.code FROM analyte_aliases a JOIN analytes an ON an.id = a.analyte_id
WHERE a.label_key = $1 AND (a.user_id = $2::uuid OR a.user_id IS NULL)
ORDER BY a.user_id NULLS LAST
LIMIT 1
`

type FindAnalyteByLabelParams struct {
	LabelKey string
	UserID   uuid.UUID
}

// The user's alias wins over a seeded one.
func (q *Queries) FindAnalyteByLabel(ctx context.Context, arg FindAnalyteByLabelParams) (string, error) {
	row := q.db.QueryRow(ctx, findAnalyteByLabel, arg.LabelKey, arg.UserID)
	var code string
	err := row.Scan(&code)
	return code, err
}

const getAnalyteAlias = `-- name: GetAnalyteAlias :one
SELECT a.id, a.label, a.user_id, a.created_at, an.code AS analyte
FROM analyte_aliases a JOIN analytes an ON an.id = a.analyte_id
WHERE a.id = $1 AND (a.user_id IS NULL OR a.user_id = $2::uuid)
`

type GetAnalyteAliasParams struct {
	ID     int64
	UserID uuid.UUID
}

type GetAnalyteAliasRow struct {
	ID        int64
	Label     string
	UserID    *uuid.UUID
	CreatedAt time.Time
	Analyte   string
}

func (q *Queries) GetAnalyteAlias(ctx context.Context, arg GetAnalyteAliasParams) (GetAnalyteAliasRow, error) {
	row := q.db.QueryRow(ctx, getAnalyteAlias, arg.ID, arg.UserID)
	var i GetAnalyteAliasRow
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.UserID,
		&i.CreatedAt,
		&i.Analyte,
	)
	return i, err
}

const getAnalyteID = `-- name: GetAnalyteID :one

SELECT id FROM analytes WHERE code = $1
`

// Analyte catalogue and aliases (J12.5); see docs/architecture/analyte-catalog.md.
func (q *Queries) GetAnalyteID(ctx context.Context, code string) (int16, error) {
	row := q.db.QueryRow(ctx, getAnalyteID, code)
	var id int16
	err := row.Scan(&id)
	return id, err
}

const insertAnalyteAlias = `-- name: InsertAnalyteAlias :one
INSERT INTO analyte_aliases (analyte_id, label, label_key, user_id, created_by)
SELECT an.id, $1, $2, $3::uuid, $4::text FROM analytes an WHERE an.code = $5
RETURNING id, created_at
`

type InsertAnalyteAliasParams struct {
	Label     string
	LabelKey  string
	UserID    uuid.UUID
	CreatedBy string
	Analyte   string
}

type InsertAnalyteAliasRow struct {
	ID        int64
	CreatedAt time.Time
}

// No row when the analyte code is unknown.
func (q *Queries) InsertAnalyteAlias(ctx context.Context, arg InsertAnalyteAliasParams) (InsertAnalyteAliasRow, error) {
	row := q.db.QueryRow(ctx, insertAnalyteAlias,
		arg.Label,
		arg.LabelKey,
		arg.UserID,
		arg.CreatedBy,
		arg.Analyte,
	)
	var i InsertAnalyteAliasRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listAnalyteAliases = `-- name: ListAnalyteAliases :many
SELECT a.id, a.label, a.user_id, a.created_at, an.code AS analyte
FROM analyte_aliases a JOIN analytes an ON an.id = a.analyte_id
WHERE a.user_id IS NULL OR a.user_id = $1::uuid
ORDER BY a.user_id NULLS FIRST, a.id
`

type ListAnalyteAliasesRow struct {
	ID        int64
	Label     string
	UserID    *uuid.UUID
	CreatedAt time.Time
	Analyte   string
}

// Seeded aliases first, then the user's own, each in creation order.
func (q *Queries) ListAnalyteAliases(ctx context.Context, userID uuid.UUID) ([]ListAnalyteAliasesRow, error) {
	rows, err := q.db.Query(ctx, listAnalyteAliases, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAnalyteAliasesRow
	for rows.Next() {
		var i ListAnalyteAliasesRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.UserID,
			&i.CreatedAt,
			&i.Analyte,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
