// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package dbq

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const insertAuditEvent = `-- name: InsertAuditEvent :one
INSERT INTO audit_events (user_id, actor, action, target_type, target_id, detail)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, occurred_at
`

type InsertAuditEventParams struct {
	UserID     *uuid.UUID
	Actor      string
	Action     string
	TargetType *string
	TargetID   *string
	Detail     json.RawMessage
}

type InsertAuditEventRow struct {
	ID         int64
	OccurredAt time.Time
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (InsertAuditEventRow, error) {
	row := q.db.QueryRow(ctx, insertAuditEvent,
		arg.UserID,
		arg.Actor,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Detail,
	)
	var i InsertAuditEventRow
	err := row.Scan(&i.ID, &i.OccurredAt)
	return i, err
}
