// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOtherSessions = `-- name: DeleteOtherSessions :execrows
DELETE FROM sessions WHERE user_id = $1 AND id <> $2
`

type DeleteOtherSessionsParams struct {
	UserID uuid.UUID
	Keep   uuid.UUID
}

func (q *Queries) DeleteOtherSessions(ctx context.Context, arg DeleteOtherSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOtherSessions, arg.UserID, arg.Keep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRecoveryCodes = `-- name: DeleteRecoveryCodes :exec
DELETE FROM recovery_codes WHERE user_id = $1
`

func (q *Queries) DeleteRecoveryCodes(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRecoveryCodes, userID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const deleteStaleSessions = `-- name: DeleteStaleSessions :exec
DELETE FROM sessions WHERE user_id = $1 AND (expires_at <= $2 OR last_seen_at <= $3)
`

type DeleteStaleSessionsParams struct {
	UserID    uuid.UUID
	Now       time.Time
	IdleSince time.Time
}

func (q *Queries) DeleteStaleSessions(ctx context.Context, arg DeleteStaleSessionsParams) error {
	_, err := q.db.Exec(ctx, deleteStaleSessions, arg.UserID, arg.Now, arg.IdleSince)
	return err
}

const deleteUserSession = `-- name: DeleteUserSession :execrows
DELETE FROM sessions WHERE id = $1 AND user_id = $2
`

type DeleteUserSessionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteUserSession(ctx context.Context, arg DeleteUserSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserSession, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserSessions = `-- name: DeleteUserSessions :execrows
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserSessions, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const disableTOTP = `-- name: DisableTOTP :exec
UPDATE users
SET totp_ciphertext = NULL, totp_key_id = NULL, totp_enabled_at = NULL, totp_last_step = NULL, updated_at = now()
WHERE id = $1
`

func (q *Queries) DisableTOTP(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, disableTOTP, id)
	return err
}

const enableTOTP = `-- name: EnableTOTP :execrows
UPDATE users SET totp_enabled_at = $1::timestamptz, totp_last_step = $2::bigint, updated_at = now()
WHERE id = $3 AND totp_ciphertext IS NOT NULL AND totp_enabled_at IS NULL
`

type EnableTOTPParams struct {
	Now  time.Time
	Step int64
	ID   uuid.UUID
}

func (q *Queries) EnableTOTP(ctx context.Context, arg EnableTOTPParams) (int64, error) {
	result, err := q.db.Exec(ctx, enableTOTP, arg.Now, arg.Step, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLiveSession = `-- name: GetLiveSession :one
SELECT id, user_id, token_hash, created_at, last_seen_at, expires_at FROM sessions WHERE token_hash = $1 AND expires_at > $2 AND last_seen_at > $3
`

type GetLiveSessionParams struct {
	TokenHash []byte
	Now       time.Time
	IdleSince time.Time
}

func (q *Queries) GetLiveSession(ctx context.Context, arg GetLiveSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, getLiveSession, arg.TokenHash, arg.Now, arg.IdleSince)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, totp_ciphertext, totp_key_id, created_at, updated_at, totp_enabled_at, totp_last_step FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.TotpCiphertext,
		&i.TotpKeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotpEnabledAt,
		&i.TotpLastStep,
	)
	return i, err
}

const insertRecoveryCode = `-- name: InsertRecoveryCode :exec
INSERT INTO recovery_codes (user_id, code_hash) VALUES ($1, $2)
`

type InsertRecoveryCodeParams struct {
	UserID   uuid.UUID
	CodeHash []byte
}

func (q *Queries) InsertRecoveryCode(ctx context.Context, arg InsertRecoveryCodeParams) error {
	_, err := q.db.Exec(ctx, insertRecoveryCode, arg.UserID, arg.CodeHash)
	return err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (id, user_id, token_hash, created_at, last_seen_at, expires_at)
VALUES ($1, $2, $3, $4, $4, $5)
`

type InsertSessionParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	Now       time.Time
	ExpiresAt time.Time
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.Now,
		arg.ExpiresAt,
	)
	return err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (id, username, password_hash) VALUES ($1, $2, $3)
`

type InsertUserParams struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.Exec(ctx, insertUser, arg.ID, arg.Username, arg.PasswordHash)
	return err
}

const listLiveSessions = `-- name: ListLiveSessions :many
SELECT id, created_at, last_seen_at, expires_at FROM sessions
WHERE user_id = $1 AND expires_at > $2 AND last_seen_at > $3
ORDER BY last_seen_at DESC, id
`

type ListLiveSessionsParams struct {
	UserID    uuid.UUID
	Now       time.Time
	IdleSince time.Time
}

type ListLiveSessionsRow struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	LastSeenAt time.Time
	ExpiresAt  time.Time
}

func (q *Queries) ListLiveSessions(ctx context.Context, arg ListLiveSessionsParams) ([]ListLiveSessionsRow, error) {
	rows, err := q.db.Query(ctx, listLiveSessions, arg.UserID, arg.Now, arg.IdleSince)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiveSessionsRow
	for rows.Next() {
		var i ListLiveSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPasswordHash = `-- name: SetPasswordHash :exec
UPDATE users SET password_hash = $1, updated_at = now() WHERE id = $2
`

type SetPasswordHashParams struct {
	PasswordHash string
	ID           uuid.UUID
}

func (q *Queries) SetPasswordHash(ctx context.Context, arg SetPasswordHashParams) error {
	_, err := q.db.Exec(ctx, setPasswordHash, arg.PasswordHash, arg.ID)
	return err
}

const setPendingTOTP = `-- name: SetPendingTOTP :execrows
UPDATE users
SET totp_ciphertext = $1, totp_key_id = $2::text, totp_last_step = NULL, updated_at = now()
WHERE id = $3 AND totp_enabled_at IS NULL
`

type SetPendingTOTPParams struct {
	TotpCiphertext []byte
	TotpKeyID      string
	ID             uuid.UUID
}

func (q *Queries) SetPendingTOTP(ctx context.Context, arg SetPendingTOTPParams) (int64, error) {
	result, err := q.db.Exec(ctx, setPendingTOTP, arg.TotpCiphertext, arg.TotpKeyID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = $1 WHERE id = $2 AND last_seen_at < $3
`

type TouchSessionParams struct {
	Now    time.Time
	ID     uuid.UUID
	Before time.Time
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.Now, arg.ID, arg.Before)
	return err
}

const useRecoveryCode = `-- name: UseRecoveryCode :execrows
UPDATE recovery_codes SET used_at = $1::timestamptz
WHERE user_id = $2 AND code_hash = $3 AND used_at IS NULL
`

type UseRecoveryCodeParams struct {
	Now      time.Time
	UserID   uuid.UUID
	CodeHash []byte
}

func (q *Queries) UseRecoveryCode(ctx context.Context, arg UseRecoveryCodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, useRecoveryCode, arg.Now, arg.UserID, arg.CodeHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const useTOTPStep = `-- name: UseTOTPStep :execrows
UPDATE users SET totp_last_step = $1::bigint
WHERE id = $2 AND totp_enabled_at IS NOT NULL AND (totp_last_step IS NULL OR totp_last_step < $1)
`

type UseTOTPStepParams struct {
	Step int64
	ID   uuid.UUID
}

func (q *Queries) UseTOTPStep(ctx context.Context, arg UseTOTPStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, useTOTPStep, arg.Step, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
