// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backfills.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cancelBackfill = `-- name: CancelBackfill :one
UPDATE backfills SET status = 'cancelled', finished_at = now()
WHERE id = $1 AND status IN ('running', 'failed')
RETURNING connection_id
`

func (q *Queries) CancelBackfill(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, cancelBackfill, id)
	var connection_id uuid.UUID
	err := row.Scan(&connection_id)
	return connection_id, err
}

const cancelBackfillJobs = `-- name: CancelBackfillJobs :exec
UPDATE jobs SET status = 'cancelled', finished_at = now()
WHERE kind = 'backfill_unit' AND status = 'queued' AND connection_id = $1
  AND payload->>'backfill_id' = $2::text
`

type CancelBackfillJobsParams struct {
	ConnectionID *uuid.UUID
	BackfillID   string
}

// A running unit finishes its current page and then sees the cancellation.
func (q *Queries) CancelBackfillJobs(ctx context.Context, arg CancelBackfillJobsParams) error {
	_, err := q.db.Exec(ctx, cancelBackfillJobs, arg.ConnectionID, arg.BackfillID)
	return err
}

const endBackfillUnit = `-- name: EndBackfillUnit :execrows
UPDATE backfill_units SET status = $1, last_error_class = $2, updated_at = now()
WHERE backfill_id = $3 AND range_start = $4 AND status <> 'done'
`

type EndBackfillUnitParams struct {
	Status     string
	ErrorClass *string
	BackfillID uuid.UUID
	RangeStart time.Time
}

// Done is final: a unit is finished exactly once.
func (q *Queries) EndBackfillUnit(ctx context.Context, arg EndBackfillUnitParams) (int64, error) {
	result, err := q.db.Exec(ctx, endBackfillUnit,
		arg.Status,
		arg.ErrorClass,
		arg.BackfillID,
		arg.RangeStart,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishBackfill = `-- name: FinishBackfill :exec
UPDATE backfills b SET finished_at = now(),
       status = CASE WHEN EXISTS (SELECT 1 FROM backfill_units u WHERE u.backfill_id = b.id AND u.status = 'failed')
                     THEN 'failed' ELSE 'done' END
WHERE b.id = $1 AND b.status = 'running'
  AND NOT EXISTS (SELECT 1 FROM backfill_units u WHERE u.backfill_id = b.id AND u.status IN ('pending', 'running'))
`

// Once no unit is pending or running, the backfill is done, or failed if a unit failed.
func (q *Queries) FinishBackfill(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, finishBackfill, id)
	return err
}

const getBackfillUnit = `-- name: GetBackfillUnit :one
SELECT u.range_start, u.range_end, u.status, b.connection_id, b.stream, b.status AS backfill_status
FROM backfill_units u JOIN backfills b ON b.id = u.backfill_id
WHERE u.backfill_id = $1 AND u.range_start = $2
`

type GetBackfillUnitParams struct {
	BackfillID uuid.UUID
	RangeStart time.Time
}

type GetBackfillUnitRow struct {
	RangeStart     time.Time
	RangeEnd       time.Time
	Status         string
	ConnectionID   uuid.UUID
	Stream         string
	BackfillStatus string
}

func (q *Queries) GetBackfillUnit(ctx context.Context, arg GetBackfillUnitParams) (GetBackfillUnitRow, error) {
	row := q.db.QueryRow(ctx, getBackfillUnit, arg.BackfillID, arg.RangeStart)
	var i GetBackfillUnitRow
	err := row.Scan(
		&i.RangeStart,
		&i.RangeEnd,
		&i.Status,
		&i.ConnectionID,
		&i.Stream,
		&i.BackfillStatus,
	)
	return i, err
}

const insertBackfill = `-- name: InsertBackfill :exec

INSERT INTO backfills (id, connection_id, stream, range_start, range_end)
VALUES ($1, $2, $3, $4, $5)
`

type InsertBackfillParams struct {
	ID           uuid.UUID
	ConnectionID uuid.UUID
	Stream       string
	RangeStart   time.Time
	RangeEnd     time.Time
}

// Backfills (J06.6); see docs/architecture/connectors.md#runtime-responsibilities.
func (q *Queries) InsertBackfill(ctx context.Context, arg InsertBackfillParams) error {
	_, err := q.db.Exec(ctx, insertBackfill,
		arg.ID,
		arg.ConnectionID,
		arg.Stream,
		arg.RangeStart,
		arg.RangeEnd,
	)
	return err
}

const insertBackfillUnits = `-- name: InsertBackfillUnits :exec
INSERT INTO backfill_units (backfill_id, range_start, range_end)
SELECT $1::uuid, unnest($2::timestamptz[]), unnest($3::timestamptz[])
`

type InsertBackfillUnitsParams struct {
	BackfillID uuid.UUID
	Starts     []time.Time
	Ends       []time.Time
}

func (q *Queries) InsertBackfillUnits(ctx context.Context, arg InsertBackfillUnitsParams) error {
	_, err := q.db.Exec(ctx, insertBackfillUnits, arg.BackfillID, arg.Starts, arg.Ends)
	return err
}

const listBackfillUnits = `-- name: ListBackfillUnits :many
SELECT backfill_id, range_start, range_end, status, attempts, last_error_class, updated_at FROM backfill_units
WHERE backfill_id = $1 AND ($2::text IS NULL OR status = $2)
ORDER BY range_start
`

type ListBackfillUnitsParams struct {
	BackfillID uuid.UUID
	Status     *string
}

func (q *Queries) ListBackfillUnits(ctx context.Context, arg ListBackfillUnitsParams) ([]BackfillUnit, error) {
	rows, err := q.db.Query(ctx, listBackfillUnits, arg.BackfillID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BackfillUnit
	for rows.Next() {
		var i BackfillUnit
		if err := rows.Scan(
			&i.BackfillID,
			&i.RangeStart,
			&i.RangeEnd,
			&i.Status,
			&i.Attempts,
			&i.LastErrorClass,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackfills = `-- name: ListBackfills :many
SELECT b.id, b.connection_id, b.stream, b.range_start, b.range_end, b.status, b.created_at, b.finished_at,
       count(*) FILTER (WHERE u.status = 'pending') AS pending,
       count(*) FILTER (WHERE u.status = 'running') AS running,
       count(*) FILTER (WHERE u.status = 'done') AS done,
       count(*) FILTER (WHERE u.status = 'failed') AS failed
FROM backfills b JOIN backfill_units u ON u.backfill_id = b.id
WHERE b.connection_id = $1
GROUP BY b.id
ORDER BY b.created_at DESC, b.id
`

type ListBackfillsRow struct {
	ID           uuid.UUID
	ConnectionID uuid.UUID
	Stream       string
	RangeStart   time.Time
	RangeEnd     time.Time
	Status       string
	CreatedAt    time.Time
	FinishedAt   *time.Time
	Pending      int64
	Running      int64
	Done         int64
	Failed       int64
}

func (q *Queries) ListBackfills(ctx context.Context, connectionID uuid.UUID) ([]ListBackfillsRow, error) {
	rows, err := q.db.Query(ctx, listBackfills, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBackfillsRow
	for rows.Next() {
		var i ListBackfillsRow
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.Stream,
			&i.RangeStart,
			&i.RangeEnd,
			&i.Status,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.Pending,
			&i.Running,
			&i.Done,
			&i.Failed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reopenBackfill = `-- name: ReopenBackfill :exec
UPDATE backfills SET status = 'running', finished_at = NULL WHERE id = $1 AND status IN ('running', 'failed')
`

func (q *Queries) ReopenBackfill(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, reopenBackfill, id)
	return err
}

const reopenBackfillUnits = `-- name: ReopenBackfillUnits :many
UPDATE backfill_units u SET status = CASE WHEN u.status = 'failed' THEN 'pending' ELSE u.status END, updated_at = now()
FROM backfills b
WHERE b.id = u.backfill_id AND b.id = $1 AND b.status IN ('running', 'failed') AND u.status <> 'done'
  AND ($2::timestamptz IS NULL OR u.range_start = $2)
RETURNING u.range_start, b.connection_id
`

type ReopenBackfillUnitsParams struct {
	BackfillID uuid.UUID
	RangeStart *time.Time
}

type ReopenBackfillUnitsRow struct {
	RangeStart   time.Time
	ConnectionID uuid.UUID
}

// Failed units go back to pending; every unfinished unit is returned so its job can be enqueued
// again (a dedupe key keeps a unit that still has an active job from getting a second one).
func (q *Queries) ReopenBackfillUnits(ctx context.Context, arg ReopenBackfillUnitsParams) ([]ReopenBackfillUnitsRow, error) {
	rows, err := q.db.Query(ctx, reopenBackfillUnits, arg.BackfillID, arg.RangeStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReopenBackfillUnitsRow
	for rows.Next() {
		var i ReopenBackfillUnitsRow
		if err := rows.Scan(&i.RangeStart, &i.ConnectionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startBackfillUnit = `-- name: StartBackfillUnit :exec
UPDATE backfill_units SET status = 'running', attempts = attempts + 1, updated_at = now()
WHERE backfill_id = $1 AND range_start = $2 AND status <> 'done'
`

type StartBackfillUnitParams struct {
	BackfillID uuid.UUID
	RangeStart time.Time
}

func (q *Queries) StartBackfillUnit(ctx context.Context, arg StartBackfillUnitParams) error {
	_, err := q.db.Exec(ctx, startBackfillUnit, arg.BackfillID, arg.RangeStart)
	return err
}
