// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backup.sql

package dbq

import (
	"context"
)

const countSchemaTables = `-- name: CountSchemaTables :one

SELECT count(*) FROM pg_catalog.pg_tables WHERE schemaname = 'vitamux'
`

// Backup and restore (J13.5, docs/operations/backup.md).
// A restore target must have no tables yet (roles.sql creates the empty schema).
func (q *Queries) CountSchemaTables(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSchemaTables)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const grantAppDefaultFunctionPrivileges = `-- name: GrantAppDefaultFunctionPrivileges :exec
ALTER DEFAULT PRIVILEGES FOR ROLE vitamux_owner IN SCHEMA vitamux
  GRANT EXECUTE ON FUNCTIONS TO vitamux_app
`

func (q *Queries) GrantAppDefaultFunctionPrivileges(ctx context.Context) error {
	_, err := q.db.Exec(ctx, grantAppDefaultFunctionPrivileges)
	return err
}

const grantAppDefaultPrivileges = `-- name: GrantAppDefaultPrivileges :exec
ALTER DEFAULT PRIVILEGES FOR ROLE vitamux_owner IN SCHEMA vitamux
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO vitamux_app
`

// After pg_restore: the defaults of deploy/sql/roles.sql again.
func (q *Queries) GrantAppDefaultPrivileges(ctx context.Context) error {
	_, err := q.db.Exec(ctx, grantAppDefaultPrivileges)
	return err
}

const grantAppDefaultSequencePrivileges = `-- name: GrantAppDefaultSequencePrivileges :exec
ALTER DEFAULT PRIVILEGES FOR ROLE vitamux_owner IN SCHEMA vitamux
  GRANT USAGE, SELECT ON SEQUENCES TO vitamux_app
`

func (q *Queries) GrantAppDefaultSequencePrivileges(ctx context.Context) error {
	_, err := q.db.Exec(ctx, grantAppDefaultSequencePrivileges)
	return err
}

const listReferencedBlobHashes = `-- name: ListReferencedBlobHashes :many
SELECT sha256 FROM blobs WHERE refcount > 0 ORDER BY sha256
`

// Rows with refcount 0 are sweep candidates; their files may be gone in a consistent backup.
func (q *Queries) ListReferencedBlobHashes(ctx context.Context) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listReferencedBlobHashes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var sha256 []byte
		if err := rows.Scan(&sha256); err != nil {
			return nil, err
		}
		items = append(items, sha256)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAppDefaultFunctionPrivileges = `-- name: RevokeAppDefaultFunctionPrivileges :exec
ALTER DEFAULT PRIVILEGES FOR ROLE vitamux_owner IN SCHEMA vitamux
  REVOKE ALL ON FUNCTIONS FROM vitamux_app
`

func (q *Queries) RevokeAppDefaultFunctionPrivileges(ctx context.Context) error {
	_, err := q.db.Exec(ctx, revokeAppDefaultFunctionPrivileges)
	return err
}

const revokeAppDefaultPrivileges = `-- name: RevokeAppDefaultPrivileges :exec
ALTER DEFAULT PRIVILEGES FOR ROLE vitamux_owner IN SCHEMA vitamux
  REVOKE ALL ON TABLES FROM vitamux_app
`

// Before pg_restore: objects it creates must start with the default ACL, because the dump
// only lists differences from it (otherwise every narrowed table would regain full DML).
func (q *Queries) RevokeAppDefaultPrivileges(ctx context.Context) error {
	_, err := q.db.Exec(ctx, revokeAppDefaultPrivileges)
	return err
}

const revokeAppDefaultSequencePrivileges = `-- name: RevokeAppDefaultSequencePrivileges :exec
ALTER DEFAULT PRIVILEGES FOR ROLE vitamux_owner IN SCHEMA vitamux
  REVOKE ALL ON SEQUENCES FROM vitamux_app
`

func (q *Queries) RevokeAppDefaultSequencePrivileges(ctx context.Context) error {
	_, err := q.db.Exec(ctx, revokeAppDefaultSequencePrivileges)
	return err
}
