// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blobs.sql

package dbq

import (
	"context"
	"time"
)

const addBlobRef = `-- name: AddBlobRef :one
UPDATE blobs SET refcount = refcount + $1::integer WHERE sha256 = $2 RETURNING refcount
`

type AddBlobRefParams struct {
	Delta  int32
	Sha256 []byte
}

func (q *Queries) AddBlobRef(ctx context.Context, arg AddBlobRefParams) (int32, error) {
	row := q.db.QueryRow(ctx, addBlobRef, arg.Delta, arg.Sha256)
	var refcount int32
	err := row.Scan(&refcount)
	return refcount, err
}

const deleteUnreferencedBlobs = `-- name: DeleteUnreferencedBlobs :many
DELETE FROM blobs WHERE refcount = 0 AND created_at < $1::timestamptz RETURNING sha256
`

func (q *Queries) DeleteUnreferencedBlobs(ctx context.Context, before time.Time) ([][]byte, error) {
	rows, err := q.db.Query(ctx, deleteUnreferencedBlobs, before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var sha256 []byte
		if err := rows.Scan(&sha256); err != nil {
			return nil, err
		}
		items = append(items, sha256)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlob = `-- name: GetBlob :one
SELECT sha256, size_bytes, stored_bytes, compression, key_id, refcount, created_at FROM blobs WHERE sha256 = $1
`

func (q *Queries) GetBlob(ctx context.Context, sha256 []byte) (Blob, error) {
	row := q.db.QueryRow(ctx, getBlob, sha256)
	var i Blob
	err := row.Scan(
		&i.Sha256,
		&i.SizeBytes,
		&i.StoredBytes,
		&i.Compression,
		&i.KeyID,
		&i.Refcount,
		&i.CreatedAt,
	)
	return i, err
}

const insertBlob = `-- name: InsertBlob :execrows
INSERT INTO blobs (sha256, size_bytes, stored_bytes, compression, key_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (sha256) DO NOTHING
`

type InsertBlobParams struct {
	Sha256      []byte
	SizeBytes   int64
	StoredBytes int64
	Compression string
	KeyID       *string
}

func (q *Queries) InsertBlob(ctx context.Context, arg InsertBlobParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertBlob,
		arg.Sha256,
		arg.SizeBytes,
		arg.StoredBytes,
		arg.Compression,
		arg.KeyID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listBlobHashes = `-- name: ListBlobHashes :many
SELECT sha256 FROM blobs
`

func (q *Queries) ListBlobHashes(ctx context.Context) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listBlobHashes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var sha256 []byte
		if err := rows.Scan(&sha256); err != nil {
			return nil, err
		}
		items = append(items, sha256)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBlobsExclusive = `-- name: LockBlobsExclusive :exec
SELECT pg_advisory_xact_lock($1::bigint)
`

func (q *Queries) LockBlobsExclusive(ctx context.Context, key int64) error {
	_, err := q.db.Exec(ctx, lockBlobsExclusive, key)
	return err
}

const lockBlobsShared = `-- name: LockBlobsShared :exec
SELECT pg_advisory_xact_lock_shared($1::bigint)
`

// Writers (Put, Retain) hold this until commit; the sweeper takes it exclusively.
func (q *Queries) LockBlobsShared(ctx context.Context, key int64) error {
	_, err := q.db.Exec(ctx, lockBlobsShared, key)
	return err
}
