// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cache.sql

package dbq

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const claimDirtyMarks = `-- name: ClaimDirtyMarks :many
SELECT r.user_id, r.metric_id, mc.code AS metric, r.local_date, r.marked_at
FROM resolution_dirty r JOIN metric_catalog mc ON mc.id = r.metric_id
WHERE r.marked_at < $1
ORDER BY r.user_id, r.metric_id, r.local_date
LIMIT $2::integer
FOR UPDATE OF r SKIP LOCKED
`

type ClaimDirtyMarksParams struct {
	Before  time.Time
	MaxRows int32
}

type ClaimDirtyMarksRow struct {
	UserID    uuid.UUID
	MetricID  int16
	Metric    string
	LocalDate time.Time
	MarkedAt  time.Time
}

// Dirty marks old enough to consume, locked for the rebuild transaction.
func (q *Queries) ClaimDirtyMarks(ctx context.Context, arg ClaimDirtyMarksParams) ([]ClaimDirtyMarksRow, error) {
	rows, err := q.db.Query(ctx, claimDirtyMarks, arg.Before, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimDirtyMarksRow
	for rows.Next() {
		var i ClaimDirtyMarksRow
		if err := rows.Scan(
			&i.UserID,
			&i.MetricID,
			&i.Metric,
			&i.LocalDate,
			&i.MarkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteDirtyMarks = `-- name: DeleteDirtyMarks :execrows
DELETE FROM resolution_dirty r
USING (SELECT unnest($1::uuid[]) AS u, unnest($2::smallint[]) AS m, unnest($3::date[]) AS d,
             unnest($4::timestamptz[]) AS at) AS k
WHERE r.user_id = k.u AND r.metric_id = k.m AND r.local_date = k.d AND r.marked_at = k.at
`

type DeleteDirtyMarksParams struct {
	UserIds   []uuid.UUID
	MetricIds []int16
	Dates     []time.Time
	MarkedAt  []time.Time
}

// Deletes consumed marks; a mark renewed meanwhile (newer marked_at) stays.
func (q *Queries) DeleteDirtyMarks(ctx context.Context, arg DeleteDirtyMarksParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDirtyMarks,
		arg.UserIds,
		arg.MetricIds,
		arg.Dates,
		arg.MarkedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteHourlyAggregates = `-- name: DeleteHourlyAggregates :exec
DELETE FROM source_hourly_aggregates
WHERE user_id = $1 AND metric_id = $2 AND hour_start >= $3 AND hour_start < $4
`

type DeleteHourlyAggregatesParams struct {
	UserID   uuid.UUID
	MetricID int16
	FromAt   time.Time
	ToAt     time.Time
}

func (q *Queries) DeleteHourlyAggregates(ctx context.Context, arg DeleteHourlyAggregatesParams) error {
	_, err := q.db.Exec(ctx, deleteHourlyAggregates,
		arg.UserID,
		arg.MetricID,
		arg.FromAt,
		arg.ToAt,
	)
	return err
}

const disableJIT = `-- name: DisableJIT :exec
SELECT set_config('jit', 'off', true)
`

// For the rest of the transaction: compiling RebuildHourlyAggregates (whose estimates are large)
// costs more than it saves.
func (q *Queries) DisableJIT(ctx context.Context) error {
	_, err := q.db.Exec(ctx, disableJIT)
	return err
}

const getResolvedCache = `-- name: GetResolvedCache :many

SELECT c.local_date, c.results FROM resolved_cache c
JOIN (SELECT unnest($1::date[]) AS d, unnest($2::text[]) AS fp) AS k ON c.local_date = k.d AND c.overrides_fp = k.fp
WHERE c.user_id = $3 AND c.metric = $4 AND c.window_kind = $5 AND c.rule_ref = $6
  AND c.complete_at <= $7
`

type GetResolvedCacheParams struct {
	Dates      []time.Time
	Fps        []string
	UserID     uuid.UUID
	Metric     string
	WindowKind string
	RuleRef    string
	Now        time.Time
}

type GetResolvedCacheRow struct {
	LocalDate time.Time
	Results   json.RawMessage
}

// Resolution cache and hourly aggregates (J09.9, internal/resolve/cache.go and aggregates.go).
// Invalidation is done by the triggers of the resolution_cache migration.
// The cached dates of a request: each date with its overrides fingerprint, closed by now.
func (q *Queries) GetResolvedCache(ctx context.Context, arg GetResolvedCacheParams) ([]GetResolvedCacheRow, error) {
	rows, err := q.db.Query(ctx, getResolvedCache,
		arg.Dates,
		arg.Fps,
		arg.UserID,
		arg.Metric,
		arg.WindowKind,
		arg.RuleRef,
		arg.Now,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetResolvedCacheRow
	for rows.Next() {
		var i GetResolvedCacheRow
		if err := rows.Scan(&i.LocalDate, &i.Results); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResolveUsers = `-- name: ListResolveUsers :many
SELECT id FROM users ORDER BY id
`

func (q *Queries) ListResolveUsers(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listResolveUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putResolvedCache = `-- name: PutResolvedCache :many
INSERT INTO resolved_cache (user_id, metric, window_kind, local_date, rule_ref, overrides_fp, results, deps,
                            dep_from, dep_to, complete_at)
SELECT $1, $2, $3, k.d, $4, k.fp, k.res, $5::text[],
       k.d - $6::integer, k.d + $7::integer, k.complete
FROM (SELECT unnest($8::date[]) AS d, unnest($9::text[]) AS fp, unnest($10::jsonb[]) AS res,
             unnest($11::timestamptz[]) AS complete) AS k
WHERE NOT EXISTS (
  SELECT 1 FROM resolution_dirty r JOIN metric_catalog mc ON mc.id = r.metric_id
  WHERE r.user_id = $1 AND mc.code = ANY($5::text[])
    AND r.local_date BETWEEN k.d - $6::integer AND k.d + $7::integer)
ON CONFLICT DO NOTHING
RETURNING local_date
`

type PutResolvedCacheParams struct {
	UserID     uuid.UUID
	Metric     string
	WindowKind string
	RuleRef    string
	Deps       []string
	BackDays   int32
	AheadDays  int32
	Dates      []time.Time
	Fps        []string
	Results    []json.RawMessage
	CompleteAt []time.Time
}

// Stores computed dates unless a dirty mark of a dependency is still pending in their range: a
// request that read rows before a writer committed must not cache them. Returns the stored dates.
func (q *Queries) PutResolvedCache(ctx context.Context, arg PutResolvedCacheParams) ([]time.Time, error) {
	rows, err := q.db.Query(ctx, putResolvedCache,
		arg.UserID,
		arg.Metric,
		arg.WindowKind,
		arg.RuleRef,
		arg.Deps,
		arg.BackDays,
		arg.AheadDays,
		arg.Dates,
		arg.Fps,
		arg.Results,
		arg.CompleteAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []time.Time
	for rows.Next() {
		var local_date time.Time
		if err := rows.Scan(&local_date); err != nil {
			return nil, err
		}
		items = append(items, local_date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rebuildHourlyAggregates = `-- name: RebuildHourlyAggregates :execrows
WITH h AS (
  SELECT $3::timestamptz[] AS hs, $4::timestamptz[] AS he, $5::date[] AS ld
), sample_bucket AS ( -- samples per source, hour i and 5-minute bucket b
  SELECT s.connection_id, s.device_id, s.origin_id, s.i, s.b, count(*) AS n, sum(s.value ORDER BY s.start_at, s.id) AS total,
    min(s.value) AS min_value, max(s.value) AS max_value, min(s.start_at) AS first_at, max(s.start_at) AS last_at
  FROM (
    SELECT x.id, x.start_at, x.value, x.connection_id, x.device_id, x.origin_id, width_bucket(x.start_at, h.hs) AS i,
      date_bin('5 minutes', x.start_at, TIMESTAMPTZ '2000-01-01 00:00:00+00') AS b
    FROM h, measurements x
    WHERE x.user_id = $1 AND x.metric_id = $2
      AND x.start_at >= $6 AND x.start_at < $7
      AND x.superseded_at IS NULL AND x.deleted_at IS NULL AND x.kind <> 'daily_value'
      AND (x.end_at IS NULL OR x.end_at <= x.start_at)
  ) s, h
  WHERE s.i > 0 AND s.start_at < h.he[s.i]
  GROUP BY s.connection_id, s.device_id, s.origin_id, s.i, s.b
), interval_part AS ( -- an interval's part [lo, hi) in each hour i it overlaps
  SELECT p.id, p.start_at, p.end_at, p.value, p.connection_id, p.device_id, p.origin_id, p.i, p.lo, p.hi FROM (
    SELECT x.id, x.start_at, x.end_at, x.value, x.connection_id, x.device_id, x.origin_id, i,
      greatest(x.start_at, h.hs[i]) AS lo, least(x.end_at, h.he[i]) AS hi
    FROM h, measurements x,
      generate_series(width_bucket(greatest(x.start_at, h.hs[1]), h.hs), width_bucket(x.end_at - interval '1 microsecond', h.hs)) AS i
    WHERE x.user_id = $1 AND x.metric_id = $2
      AND x.start_at >= $6 AND x.start_at < $7
      AND x.superseded_at IS NULL AND x.deleted_at IS NULL AND x.kind <> 'daily_value'
      AND x.end_at > x.start_at
  ) p
  WHERE p.lo < p.hi
), bucket AS ( -- every bucket holding a sample or part of an interval
  SELECT connection_id, device_id, origin_id, i, b FROM sample_bucket
  UNION
  SELECT p.connection_id, p.device_id, p.origin_id, p.i, g
  FROM interval_part p,
    generate_series(date_bin('5 minutes', p.lo, TIMESTAMPTZ '2000-01-01 00:00:00+00'), p.hi - interval '1 microsecond', interval '5 minutes') AS g
), hour AS ( -- per source and hour: the samples' part, the intervals' part, the bucket count
  SELECT connection_id, device_id, origin_id, i, sum(n)::integer AS samples, NULL::integer AS buckets,
    sum(total / n ORDER BY b) AS bucket_mean_sum, min(min_value) AS min_value, max(max_value) AS max_value,
    NULL::double precision AS interval_sum, min(first_at) AS first_at, max(last_at) AS last_at
  FROM sample_bucket GROUP BY connection_id, device_id, origin_id, i
  UNION ALL
  SELECT connection_id, device_id, origin_id, i, count(*)::integer, NULL, NULL, min(value), max(value),
    sum(value * (extract(epoch FROM hi - lo) * 1000000000)::float8 / (extract(epoch FROM end_at - start_at) * 1000000000)::float8
        ORDER BY start_at, id),
    min(lo), max(hi)
  FROM interval_part GROUP BY connection_id, device_id, origin_id, i
  UNION ALL
  SELECT connection_id, device_id, origin_id, i, 0, count(*)::integer, NULL, NULL, NULL, NULL, NULL, NULL
  FROM bucket GROUP BY connection_id, device_id, origin_id, i
)
INSERT INTO source_hourly_aggregates (user_id, metric_id, source_key, hour_start, local_date, connection_id, device_id,
                                      origin_id, samples, buckets, bucket_mean_sum, min_value, max_value, interval_sum,
                                      first_at, last_at)
SELECT $1, $2,
  a.connection_id::text || '/' || COALESCE(a.device_id::text, '-') || '/' || COALESCE(a.origin_id::text, '-'),
  h.hs[a.i], h.ld[a.i], a.connection_id, a.device_id, a.origin_id, a.samples, a.buckets, COALESCE(a.bucket_mean_sum, 0),
  a.min_value, a.max_value, COALESCE(a.interval_sum, 0), a.first_at, a.last_at
FROM (
  SELECT connection_id, device_id, origin_id, i, sum(samples)::integer AS samples, sum(buckets)::smallint AS buckets,
    sum(bucket_mean_sum) AS bucket_mean_sum, min(min_value) AS min_value, max(max_value) AS max_value,
    sum(interval_sum) AS interval_sum, min(first_at) AS first_at, max(last_at) AS last_at
  FROM hour GROUP BY connection_id, device_id, origin_id, i
) a, h
`

type RebuildHourlyAggregatesParams struct {
	UserID     uuid.UUID
	MetricID   int16
	HourStarts []time.Time
	HourEnds   []time.Time
	LocalDates []time.Time
	FromAt     time.Time
	ToAt       time.Time
}

// Aggregates the active non-daily rows of a metric that start from from_at into the owner's
// local hours (hour_starts, hour_ends, local_dates: ascending and contiguous, ending at to_at), in
// the database so a year of dense rows never leaves it. A sample counts in the hour it starts, an
// interval in every hour it overlaps, pro-rated linearly by its nanoseconds in the hour. buckets
// counts the UTC-aligned 5-minute buckets holding a sample or part of an interval and
// bucket_mean_sum adds each bucket's sample mean in bucket order; sums run in (start_at, id)
// order, so the floats are reproducible. The caller deletes the hours first.
func (q *Queries) RebuildHourlyAggregates(ctx context.Context, arg RebuildHourlyAggregatesParams) (int64, error) {
	result, err := q.db.Exec(ctx, rebuildHourlyAggregates,
		arg.UserID,
		arg.MetricID,
		arg.HourStarts,
		arg.HourEnds,
		arg.LocalDates,
		arg.FromAt,
		arg.ToAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
