// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cache.sql

package dbq

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const aggregateRows = `-- name: AggregateRows :many
SELECT x.kind, x.start_at, x.end_at, x.value, x.connection_id, x.device_id, x.origin_id
FROM measurements x
WHERE x.user_id = $1 AND x.metric_id = $2
  AND x.start_at >= $3 AND x.start_at < $4
  AND x.superseded_at IS NULL AND x.deleted_at IS NULL AND x.kind <> 'daily_value'
ORDER BY x.start_at, x.id
`

type AggregateRowsParams struct {
	UserID   uuid.UUID
	MetricID int16
	FromAt   time.Time
	ToAt     time.Time
}

type AggregateRowsRow struct {
	Kind         string
	StartAt      time.Time
	EndAt        *time.Time
	Value        float64
	ConnectionID uuid.UUID
	DeviceID     *uuid.UUID
	OriginID     *uuid.UUID
}

// Active non-daily rows of a metric starting from from_at and before to_at, with their source ids.
func (q *Queries) AggregateRows(ctx context.Context, arg AggregateRowsParams) ([]AggregateRowsRow, error) {
	rows, err := q.db.Query(ctx, aggregateRows,
		arg.UserID,
		arg.MetricID,
		arg.FromAt,
		arg.ToAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AggregateRowsRow
	for rows.Next() {
		var i AggregateRowsRow
		if err := rows.Scan(
			&i.Kind,
			&i.StartAt,
			&i.EndAt,
			&i.Value,
			&i.ConnectionID,
			&i.DeviceID,
			&i.OriginID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimDirtyMarks = `-- name: ClaimDirtyMarks :many
SELECT r.user_id, r.metric_id, mc.code AS metric, r.local_date, r.marked_at
FROM resolution_dirty r JOIN metric_catalog mc ON mc.id = r.metric_id
WHERE r.marked_at < $1
ORDER BY r.user_id, r.metric_id, r.local_date
LIMIT $2::integer
FOR UPDATE OF r SKIP LOCKED
`

type ClaimDirtyMarksParams struct {
	Before  time.Time
	MaxRows int32
}

type ClaimDirtyMarksRow struct {
	UserID    uuid.UUID
	MetricID  int16
	Metric    string
	LocalDate time.Time
	MarkedAt  time.Time
}

// Dirty marks old enough to consume, locked for the rebuild transaction.
func (q *Queries) ClaimDirtyMarks(ctx context.Context, arg ClaimDirtyMarksParams) ([]ClaimDirtyMarksRow, error) {
	rows, err := q.db.Query(ctx, claimDirtyMarks, arg.Before, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimDirtyMarksRow
	for rows.Next() {
		var i ClaimDirtyMarksRow
		if err := rows.Scan(
			&i.UserID,
			&i.MetricID,
			&i.Metric,
			&i.LocalDate,
			&i.MarkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteDirtyMarks = `-- name: DeleteDirtyMarks :execrows
DELETE FROM resolution_dirty r
USING (SELECT unnest($1::uuid[]) AS u, unnest($2::smallint[]) AS m, unnest($3::date[]) AS d,
             unnest($4::timestamptz[]) AS at) AS k
WHERE r.user_id = k.u AND r.metric_id = k.m AND r.local_date = k.d AND r.marked_at = k.at
`

type DeleteDirtyMarksParams struct {
	UserIds   []uuid.UUID
	MetricIds []int16
	Dates     []time.Time
	MarkedAt  []time.Time
}

// Deletes consumed marks; a mark renewed meanwhile (newer marked_at) stays.
func (q *Queries) DeleteDirtyMarks(ctx context.Context, arg DeleteDirtyMarksParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDirtyMarks,
		arg.UserIds,
		arg.MetricIds,
		arg.Dates,
		arg.MarkedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteHourlyAggregates = `-- name: DeleteHourlyAggregates :exec
DELETE FROM source_hourly_aggregates
WHERE user_id = $1 AND metric_id = $2 AND hour_start >= $3 AND hour_start < $4
`

type DeleteHourlyAggregatesParams struct {
	UserID   uuid.UUID
	MetricID int16
	FromAt   time.Time
	ToAt     time.Time
}

func (q *Queries) DeleteHourlyAggregates(ctx context.Context, arg DeleteHourlyAggregatesParams) error {
	_, err := q.db.Exec(ctx, deleteHourlyAggregates,
		arg.UserID,
		arg.MetricID,
		arg.FromAt,
		arg.ToAt,
	)
	return err
}

const getResolvedCache = `-- name: GetResolvedCache :many

SELECT c.local_date, c.results FROM resolved_cache c
JOIN (SELECT unnest($1::date[]) AS d, unnest($2::text[]) AS fp) AS k ON c.local_date = k.d AND c.overrides_fp = k.fp
WHERE c.user_id = $3 AND c.metric = $4 AND c.window_kind = $5 AND c.rule_ref = $6
  AND c.complete_at <= $7
`

type GetResolvedCacheParams struct {
	Dates      []time.Time
	Fps        []string
	UserID     uuid.UUID
	Metric     string
	WindowKind string
	RuleRef    string
	Now        time.Time
}

type GetResolvedCacheRow struct {
	LocalDate time.Time
	Results   json.RawMessage
}

// Resolution cache and hourly aggregates (J09.9, internal/resolve/cache.go and aggregates.go).
// Invalidation is done by the triggers of the resolution_cache migration.
// The cached dates of a request: each date with its overrides fingerprint, closed by now.
func (q *Queries) GetResolvedCache(ctx context.Context, arg GetResolvedCacheParams) ([]GetResolvedCacheRow, error) {
	rows, err := q.db.Query(ctx, getResolvedCache,
		arg.Dates,
		arg.Fps,
		arg.UserID,
		arg.Metric,
		arg.WindowKind,
		arg.RuleRef,
		arg.Now,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetResolvedCacheRow
	for rows.Next() {
		var i GetResolvedCacheRow
		if err := rows.Scan(&i.LocalDate, &i.Results); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertHourlyAggregates = `-- name: InsertHourlyAggregates :execrows
INSERT INTO source_hourly_aggregates
SELECT (p).* FROM jsonb_populate_recordset(NULL::source_hourly_aggregates, $1::jsonb) p
`

// Rows arrive as a JSON array of source_hourly_aggregates records.
func (q *Queries) InsertHourlyAggregates(ctx context.Context, batch json.RawMessage) (int64, error) {
	result, err := q.db.Exec(ctx, insertHourlyAggregates, batch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listHourlyAggregates = `-- name: ListHourlyAggregates :many
SELECT user_id, metric_id, source_key, hour_start, local_date, connection_id, device_id, origin_id, samples, buckets, bucket_mean_sum, min_value, max_value, interval_sum, first_at, last_at FROM source_hourly_aggregates
WHERE user_id = $1 AND metric_id = (SELECT id FROM metric_catalog WHERE code = $2::text)
  AND hour_start >= $3 AND hour_start < $4
ORDER BY hour_start, source_key
`

type ListHourlyAggregatesParams struct {
	UserID uuid.UUID
	Metric string
	FromAt time.Time
	ToAt   time.Time
}

func (q *Queries) ListHourlyAggregates(ctx context.Context, arg ListHourlyAggregatesParams) ([]SourceHourlyAggregate, error) {
	rows, err := q.db.Query(ctx, listHourlyAggregates,
		arg.UserID,
		arg.Metric,
		arg.FromAt,
		arg.ToAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SourceHourlyAggregate
	for rows.Next() {
		var i SourceHourlyAggregate
		if err := rows.Scan(
			&i.UserID,
			&i.MetricID,
			&i.SourceKey,
			&i.HourStart,
			&i.LocalDate,
			&i.ConnectionID,
			&i.DeviceID,
			&i.OriginID,
			&i.Samples,
			&i.Buckets,
			&i.BucketMeanSum,
			&i.MinValue,
			&i.MaxValue,
			&i.IntervalSum,
			&i.FirstAt,
			&i.LastAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResolveUsers = `-- name: ListResolveUsers :many
SELECT id FROM users ORDER BY id
`

func (q *Queries) ListResolveUsers(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listResolveUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putResolvedCache = `-- name: PutResolvedCache :many
INSERT INTO resolved_cache (user_id, metric, window_kind, local_date, rule_ref, overrides_fp, results, deps,
                            dep_from, dep_to, complete_at)
SELECT $1, $2, $3, k.d, $4, k.fp, k.res, $5::text[],
       k.d - $6::integer, k.d + $7::integer, k.complete
FROM (SELECT unnest($8::date[]) AS d, unnest($9::text[]) AS fp, unnest($10::jsonb[]) AS res,
             unnest($11::timestamptz[]) AS complete) AS k
WHERE NOT EXISTS (
  SELECT 1 FROM resolution_dirty r JOIN metric_catalog mc ON mc.id = r.metric_id
  WHERE r.user_id = $1 AND mc.code = ANY($5::text[])
    AND r.local_date BETWEEN k.d - $6::integer AND k.d + $7::integer)
ON CONFLICT DO NOTHING
RETURNING local_date
`

type PutResolvedCacheParams struct {
	UserID     uuid.UUID
	Metric     string
	WindowKind string
	RuleRef    string
	Deps       []string
	BackDays   int32
	AheadDays  int32
	Dates      []time.Time
	Fps        []string
	Results    []json.RawMessage
	CompleteAt []time.Time
}

// Stores computed dates unless a dirty mark of a dependency is still pending in their range: a
// request that read rows before a writer committed must not cache them. Returns the stored dates.
func (q *Queries) PutResolvedCache(ctx context.Context, arg PutResolvedCacheParams) ([]time.Time, error) {
	rows, err := q.db.Query(ctx, putResolvedCache,
		arg.UserID,
		arg.Metric,
		arg.WindowKind,
		arg.RuleRef,
		arg.Deps,
		arg.BackDays,
		arg.AheadDays,
		arg.Dates,
		arg.Fps,
		arg.Results,
		arg.CompleteAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []time.Time
	for rows.Next() {
		var local_date time.Time
		if err := rows.Scan(&local_date); err != nil {
			return nil, err
		}
		items = append(items, local_date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
