// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: config.sql

package dbq

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const deleteConnectionBatches = `-- name: DeleteConnectionBatches :exec
DELETE FROM ingest_batches WHERE connection_id = $1
`

func (q *Queries) DeleteConnectionBatches(ctx context.Context, connectionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteConnectionBatches, connectionID)
	return err
}

const deleteConnectionClients = `-- name: DeleteConnectionClients :exec
DELETE FROM clients WHERE connection_id = $1
`

func (q *Queries) DeleteConnectionClients(ctx context.Context, connectionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteConnectionClients, connectionID)
	return err
}

const deleteConnectionGroups = `-- name: DeleteConnectionGroups :execrows
DELETE FROM measurement_groups WHERE connection_id = $1
`

func (q *Queries) DeleteConnectionGroups(ctx context.Context, connectionID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConnectionGroups, connectionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteConnectionImportRuns = `-- name: DeleteConnectionImportRuns :exec
DELETE FROM import_runs WHERE connection_id = $1
`

func (q *Queries) DeleteConnectionImportRuns(ctx context.Context, connectionID *uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteConnectionImportRuns, connectionID)
	return err
}

const deleteConnectionImports = `-- name: DeleteConnectionImports :exec
DELETE FROM import_items
WHERE raw_payload_id IN (SELECT rp.id FROM raw_payloads rp WHERE rp.connection_id = $1::uuid)
   OR import_run_id IN (SELECT ir.id FROM import_runs ir WHERE ir.connection_id = $1::uuid)
`

func (q *Queries) DeleteConnectionImports(ctx context.Context, connectionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteConnectionImports, connectionID)
	return err
}

const deleteConnectionMeasurements = `-- name: DeleteConnectionMeasurements :execrows
DELETE FROM measurements WHERE connection_id = $1
`

func (q *Queries) DeleteConnectionMeasurements(ctx context.Context, connectionID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConnectionMeasurements, connectionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteConnectionRaw = `-- name: DeleteConnectionRaw :execrows
DELETE FROM raw_payloads WHERE connection_id = $1
`

func (q *Queries) DeleteConnectionRaw(ctx context.Context, connectionID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConnectionRaw, connectionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteConnectionSleep = `-- name: DeleteConnectionSleep :execrows
DELETE FROM sleep_sessions WHERE connection_id = $1
`

func (q *Queries) DeleteConnectionSleep(ctx context.Context, connectionID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConnectionSleep, connectionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteConnectionWorkouts = `-- name: DeleteConnectionWorkouts :execrows
DELETE FROM workouts WHERE connection_id = $1
`

func (q *Queries) DeleteConnectionWorkouts(ctx context.Context, connectionID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConnectionWorkouts, connectionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOwnerConnection = `-- name: DeleteOwnerConnection :execrows
DELETE FROM connections WHERE id = $1 AND user_id = $2
`

type DeleteOwnerConnectionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteOwnerConnection(ctx context.Context, arg DeleteOwnerConnectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOwnerConnection, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureManualConnection = `-- name: EnsureManualConnection :one
INSERT INTO connections (id, user_id, provider_id, account_key, mode, status)
SELECT $1, $2, p.id, $3, 'push', 'active' FROM providers p WHERE p.code = 'manual'
ON CONFLICT (user_id, provider_id, account_key) DO UPDATE SET account_key = excluded.account_key
RETURNING id
`

type EnsureManualConnectionParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	AccountKey []byte
}

// The owner's one connection of provider manual: account_key is fixed, so the unique key finds it.
func (q *Queries) EnsureManualConnection(ctx context.Context, arg EnsureManualConnectionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, ensureManualConnection, arg.ID, arg.UserID, arg.AccountKey)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getJobsByID = `-- name: GetJobsByID :many
SELECT id, kind, status, connection_id, exclusive, priority, run_at, dedupe_key, payload, attempts, max_attempts, lease_owner, lease_expires_at, created_at, started_at, finished_at, checkpoint FROM jobs WHERE id = ANY($1::uuid[]) ORDER BY created_at, id
`

func (q *Queries) GetJobsByID(ctx context.Context, ids []uuid.UUID) ([]Job, error) {
	rows, err := q.db.Query(ctx, getJobsByID, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Status,
			&i.ConnectionID,
			&i.Exclusive,
			&i.Priority,
			&i.RunAt,
			&i.DedupeKey,
			&i.Payload,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Checkpoint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOwnerSchedule = `-- name: GetOwnerSchedule :one
SELECT s.id, s.connection_id, s.stream, s.run_interval, s.lookback, s.next_run_at, s.enabled, s.mode FROM schedules s JOIN connections c ON c.id = s.connection_id
WHERE s.id = $1 AND c.user_id = $2
`

type GetOwnerScheduleParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetOwnerSchedule(ctx context.Context, arg GetOwnerScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, getOwnerSchedule, arg.ID, arg.UserID)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.Stream,
		&i.RunInterval,
		&i.Lookback,
		&i.NextRunAt,
		&i.Enabled,
		&i.Mode,
	)
	return i, err
}

const insertPushConnection = `-- name: InsertPushConnection :one
INSERT INTO connections (id, user_id, provider_id, mode, status)
SELECT $1, $2, p.id, 'push', 'active' FROM providers p WHERE p.code = $3
RETURNING id
`

type InsertPushConnectionParams struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	Provider string
}

func (q *Queries) InsertPushConnection(ctx context.Context, arg InsertPushConnectionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertPushConnection, arg.ID, arg.UserID, arg.Provider)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listConnectionRuns = `-- name: ListConnectionRuns :many
SELECT r.id, r.job_id, j.kind, r.attempt, r.started_at, r.finished_at, r.outcome, r.error_class, r.error_message, r.stats
FROM job_runs r JOIN jobs j ON j.id = r.job_id
WHERE j.connection_id = $1 AND ($2::bigint IS NULL OR r.id < $2::bigint)
ORDER BY r.id DESC
LIMIT $3
`

type ListConnectionRunsParams struct {
	ConnectionID *uuid.UUID
	AfterID      *int64
	Lim          int32
}

type ListConnectionRunsRow struct {
	ID           int64
	JobID        uuid.UUID
	Kind         string
	Attempt      int32
	StartedAt    time.Time
	FinishedAt   *time.Time
	Outcome      *string
	ErrorClass   *string
	ErrorMessage *string
	Stats        json.RawMessage
}

func (q *Queries) ListConnectionRuns(ctx context.Context, arg ListConnectionRunsParams) ([]ListConnectionRunsRow, error) {
	rows, err := q.db.Query(ctx, listConnectionRuns, arg.ConnectionID, arg.AfterID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConnectionRunsRow
	for rows.Next() {
		var i ListConnectionRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Kind,
			&i.Attempt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Outcome,
			&i.ErrorClass,
			&i.ErrorMessage,
			&i.Stats,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverridesPage = `-- name: ListOverridesPage :many
SELECT id, user_id, metric, window_kind, window_key, local_date, action, input_id, source_group, value, unit, note, created_by, created_at, revoked_at, revoked_by FROM manual_overrides
WHERE user_id = $1
  AND ($2::text[] IS NULL OR metric = ANY($2::text[]))
  AND ($3::timestamptz IS NULL OR (created_at, id) < ($3::timestamptz, $4::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListOverridesPageParams struct {
	UserID   uuid.UUID
	Metrics  []string
	AfterKey *time.Time
	AfterID  uuid.UUID
	Lim      int32
}

// Newest first, revoked ones included.
func (q *Queries) ListOverridesPage(ctx context.Context, arg ListOverridesPageParams) ([]ManualOverride, error) {
	rows, err := q.db.Query(ctx, listOverridesPage,
		arg.UserID,
		arg.Metrics,
		arg.AfterKey,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManualOverride
	for rows.Next() {
		var i ManualOverride
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Metric,
			&i.WindowKind,
			&i.WindowKey,
			&i.LocalDate,
			&i.Action,
			&i.InputID,
			&i.SourceGroup,
			&i.Value,
			&i.Unit,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.RevokedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnerConnections = `-- name: ListOwnerConnections :many

SELECT c.id, p.code AS provider, c.mode, c.status, c.last_success_at, c.last_error_class, c.consecutive_failures,
       c.created_at, c.updated_at, r.blocked_until, c.upstream
FROM connections c JOIN providers p ON p.id = c.provider_id
LEFT JOIN provider_rate_state r ON r.provider_id = c.provider_id
WHERE c.user_id = $1 AND ($2::uuid IS NULL OR c.id = $2::uuid)
ORDER BY c.created_at, c.id
`

type ListOwnerConnectionsParams struct {
	UserID uuid.UUID
	ID     *uuid.UUID
}

type ListOwnerConnectionsRow struct {
	ID                  uuid.UUID
	Provider            string
	Mode                string
	Status              string
	LastSuccessAt       *time.Time
	LastErrorClass      *string
	ConsecutiveFailures int32
	CreatedAt           time.Time
	UpdatedAt           time.Time
	BlockedUntil        *time.Time
	Upstream            []byte
}

// Owner configuration endpoints (J10.4, docs/architecture/api.md#owner-endpoints-apiv1). Every
// query is scoped to the owner, directly or through the connection. Lists are keyset-paginated:
// a NULL after_* starts at the beginning.
// One connection when id is set, else all of the owner's.
func (q *Queries) ListOwnerConnections(ctx context.Context, arg ListOwnerConnectionsParams) ([]ListOwnerConnectionsRow, error) {
	rows, err := q.db.Query(ctx, listOwnerConnections, arg.UserID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOwnerConnectionsRow
	for rows.Next() {
		var i ListOwnerConnectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Mode,
			&i.Status,
			&i.LastSuccessAt,
			&i.LastErrorClass,
			&i.ConsecutiveFailures,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BlockedUntil,
			&i.Upstream,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnerJobs = `-- name: ListOwnerJobs :many
SELECT j.id, j.kind, j.status, j.connection_id, j.exclusive, j.priority, j.run_at, j.dedupe_key, j.payload, j.attempts, j.max_attempts, j.lease_owner, j.lease_expires_at, j.created_at, j.started_at, j.finished_at, j.checkpoint FROM jobs j LEFT JOIN connections c ON c.id = j.connection_id
WHERE (j.connection_id IS NULL OR c.user_id = $1)
  AND ($2::text IS NULL OR j.status = $2::text)
  AND ($3::timestamptz IS NULL OR (j.created_at, j.id) < ($3::timestamptz, $4::uuid))
ORDER BY j.created_at DESC, j.id DESC
LIMIT $5
`

type ListOwnerJobsParams struct {
	UserID   uuid.UUID
	Status   *string
	AfterKey *time.Time
	AfterID  uuid.UUID
	Lim      int32
}

// Newest first. Connection-less jobs (normalize, export, recompute) belong to the single owner.
func (q *Queries) ListOwnerJobs(ctx context.Context, arg ListOwnerJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listOwnerJobs,
		arg.UserID,
		arg.Status,
		arg.AfterKey,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Status,
			&i.ConnectionID,
			&i.Exclusive,
			&i.Priority,
			&i.RunAt,
			&i.DedupeKey,
			&i.Payload,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Checkpoint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnerSchedules = `-- name: ListOwnerSchedules :many
SELECT s.id, s.connection_id, s.stream, s.run_interval, s.lookback, s.next_run_at, s.enabled, s.mode FROM schedules s JOIN connections c ON c.id = s.connection_id
WHERE c.user_id = $1 AND ($2::uuid IS NULL OR s.connection_id = $2::uuid)
ORDER BY s.connection_id, s.stream, s.mode
`

type ListOwnerSchedulesParams struct {
	UserID       uuid.UUID
	ConnectionID *uuid.UUID
}

func (q *Queries) ListOwnerSchedules(ctx context.Context, arg ListOwnerSchedulesParams) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, listOwnerSchedules, arg.UserID, arg.ConnectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schedule
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.Stream,
			&i.RunInterval,
			&i.Lookback,
			&i.NextRunAt,
			&i.Enabled,
			&i.Mode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStreamCursors = `-- name: ListStreamCursors :many
SELECT stream, (cursor IS NOT NULL)::boolean AS has_cursor, high_watermark, status, status_reason, updated_at
FROM sync_cursors WHERE connection_id = $1
ORDER BY stream
`

type ListStreamCursorsRow struct {
	Stream        string
	HasCursor     bool
	HighWatermark *time.Time
	Status        string
	StatusReason  *string
	UpdatedAt     time.Time
}

func (q *Queries) ListStreamCursors(ctx context.Context, connectionID uuid.UUID) ([]ListStreamCursorsRow, error) {
	rows, err := q.db.Query(ctx, listStreamCursors, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStreamCursorsRow
	for rows.Next() {
		var i ListStreamCursorsRow
		if err := rows.Scan(
			&i.Stream,
			&i.HasCursor,
			&i.HighWatermark,
			&i.Status,
			&i.StatusReason,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockConnectionJobs = `-- name: LockConnectionJobs :many
SELECT status FROM jobs WHERE connection_id = $1 AND status IN ('queued', 'running')
FOR UPDATE
`

// Locks the connection's active jobs until commit: workers skip locked queued jobs when claiming.
func (q *Queries) LockConnectionJobs(ctx context.Context, connectionID *uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, lockConnectionJobs, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var status string
		if err := rows.Scan(&status); err != nil {
			return nil, err
		}
		items = append(items, status)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markConnectionDirty = `-- name: MarkConnectionDirty :exec

INSERT INTO resolution_dirty (user_id, metric_id, local_date)
SELECT m.user_id, m.metric_id, m.local_date FROM measurements m
WHERE m.connection_id = $1 AND m.superseded_at IS NULL
UNION
SELECT s.user_id, mc.id, s.sleep_date FROM sleep_sessions s JOIN metric_catalog mc ON mc.code = ANY($2::text[])
WHERE s.connection_id = $1 AND s.superseded_at IS NULL
ON CONFLICT (user_id, metric_id, local_date) DO UPDATE SET marked_at = now()
`

type MarkConnectionDirtyParams struct {
	ConnectionID uuid.UUID
	SleepCodes   []string
}

// Deleting a connection with its data (DELETE /connections/{id}?data=delete), in this order
// inside one transaction; deleting the connection row then cascades credentials, schedules,
// cursors, backfills, jobs and OAuth states.
// The days of the connection's active rows must be resolved again once they are gone.
func (q *Queries) MarkConnectionDirty(ctx context.Context, arg MarkConnectionDirtyParams) error {
	_, err := q.db.Exec(ctx, markConnectionDirty, arg.ConnectionID, arg.SleepCodes)
	return err
}

const providerExists = `-- name: ProviderExists :one
SELECT EXISTS (SELECT 1 FROM providers WHERE code = $1)
`

func (q *Queries) ProviderExists(ctx context.Context, code string) (bool, error) {
	row := q.db.QueryRow(ctx, providerExists, code)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const releaseConnectionRawBlobs = `-- name: ReleaseConnectionRawBlobs :exec
UPDATE blobs b SET refcount = b.refcount - c.n
FROM (SELECT rp.content_sha256, count(*)::integer AS n FROM raw_payloads rp WHERE rp.connection_id = $1 GROUP BY rp.content_sha256) c
WHERE b.sha256 = c.content_sha256
`

// One blob reference per raw row goes away (hold blob.LockShared); the sweeper removes unreferenced files.
func (q *Queries) ReleaseConnectionRawBlobs(ctx context.Context, connectionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, releaseConnectionRawBlobs, connectionID)
	return err
}

const resetStreamCursor = `-- name: ResetStreamCursor :exec
UPDATE sync_cursors SET cursor = NULL, high_watermark = NULL, updated_at = now()
WHERE connection_id = $1 AND stream = $2
`

type ResetStreamCursorParams struct {
	ConnectionID uuid.UUID
	Stream       string
}

// The next incremental sync starts from the connector's initial window.
func (q *Queries) ResetStreamCursor(ctx context.Context, arg ResetStreamCursorParams) error {
	_, err := q.db.Exec(ctx, resetStreamCursor, arg.ConnectionID, arg.Stream)
	return err
}

const setOwnerConnectionStatus = `-- name: SetOwnerConnectionStatus :execrows
UPDATE connections SET status = $1, updated_at = now()
WHERE id = $2 AND user_id = $3 AND status = ANY($4::text[])
`

type SetOwnerConnectionStatusParams struct {
	Status       string
	ID           uuid.UUID
	UserID       uuid.UUID
	FromStatuses []string
}

// Owner pause and resume: only from one of from_statuses, so system states are never overwritten.
func (q *Queries) SetOwnerConnectionStatus(ctx context.Context, arg SetOwnerConnectionStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setOwnerConnectionStatus,
		arg.Status,
		arg.ID,
		arg.UserID,
		arg.FromStatuses,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
