// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connectors.sql

package dbq

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const advanceSyncCursor = `-- name: AdvanceSyncCursor :exec
INSERT INTO sync_cursors (connection_id, stream, cursor, high_watermark)
VALUES ($1, $2, $3, $4)
ON CONFLICT (connection_id, stream) DO UPDATE
SET cursor = coalesce(excluded.cursor, sync_cursors.cursor),
    high_watermark = greatest(sync_cursors.high_watermark, excluded.high_watermark),
    updated_at = now()
`

type AdvanceSyncCursorParams struct {
	ConnectionID  uuid.UUID
	Stream        string
	Cursor        []byte
	HighWatermark *time.Time
}

// A null cursor keeps the stored one; the high watermark never moves backwards.
func (q *Queries) AdvanceSyncCursor(ctx context.Context, arg AdvanceSyncCursorParams) error {
	_, err := q.db.Exec(ctx, advanceSyncCursor,
		arg.ConnectionID,
		arg.Stream,
		arg.Cursor,
		arg.HighWatermark,
	)
	return err
}

const blockProvider = `-- name: BlockProvider :one
INSERT INTO provider_rate_state (provider_id, blocked_until)
SELECT id, $1 FROM providers WHERE code = $2
ON CONFLICT (provider_id) DO UPDATE
SET blocked_until = greatest(provider_rate_state.blocked_until, excluded.blocked_until), updated_at = now()
RETURNING blocked_until
`

type BlockProviderParams struct {
	BlockedUntil time.Time
	Provider     string
}

// Extends, never shortens, the shared block.
func (q *Queries) BlockProvider(ctx context.Context, arg BlockProviderParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, blockProvider, arg.BlockedUntil, arg.Provider)
	var blocked_until time.Time
	err := row.Scan(&blocked_until)
	return blocked_until, err
}

const getCredentials = `-- name: GetCredentials :one
SELECT ciphertext, version FROM credentials WHERE connection_id = $1
`

type GetCredentialsRow struct {
	Ciphertext []byte
	Version    int32
}

func (q *Queries) GetCredentials(ctx context.Context, connectionID uuid.UUID) (GetCredentialsRow, error) {
	row := q.db.QueryRow(ctx, getCredentials, connectionID)
	var i GetCredentialsRow
	err := row.Scan(&i.Ciphertext, &i.Version)
	return i, err
}

const getProviderBlock = `-- name: GetProviderBlock :one
SELECT r.blocked_until FROM provider_rate_state r JOIN providers p ON p.id = r.provider_id
WHERE p.code = $1
`

func (q *Queries) GetProviderBlock(ctx context.Context, provider string) (time.Time, error) {
	row := q.db.QueryRow(ctx, getProviderBlock, provider)
	var blocked_until time.Time
	err := row.Scan(&blocked_until)
	return blocked_until, err
}

const getSyncConnection = `-- name: GetSyncConnection :one

SELECT c.id, c.user_id, c.status, c.config, p.code AS provider
FROM connections c JOIN providers p ON p.id = c.provider_id
WHERE c.id = $1
`

type GetSyncConnectionRow struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	Status   string
	Config   json.RawMessage
	Provider string
}

// Connector runtime (J06.4, J06.5); see docs/architecture/connectors.md#runtime-responsibilities.
func (q *Queries) GetSyncConnection(ctx context.Context, id uuid.UUID) (GetSyncConnectionRow, error) {
	row := q.db.QueryRow(ctx, getSyncConnection, id)
	var i GetSyncConnectionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Config,
		&i.Provider,
	)
	return i, err
}

const getSyncCursor = `-- name: GetSyncCursor :one
SELECT cursor, high_watermark FROM sync_cursors WHERE connection_id = $1 AND stream = $2
`

type GetSyncCursorParams struct {
	ConnectionID uuid.UUID
	Stream       string
}

type GetSyncCursorRow struct {
	Cursor        []byte
	HighWatermark *time.Time
}

func (q *Queries) GetSyncCursor(ctx context.Context, arg GetSyncCursorParams) (GetSyncCursorRow, error) {
	row := q.db.QueryRow(ctx, getSyncCursor, arg.ConnectionID, arg.Stream)
	var i GetSyncCursorRow
	err := row.Scan(&i.Cursor, &i.HighWatermark)
	return i, err
}

const lockCredentials = `-- name: LockCredentials :one
SELECT ciphertext, version FROM credentials WHERE connection_id = $1 FOR UPDATE
`

type LockCredentialsRow struct {
	Ciphertext []byte
	Version    int32
}

// Serializes refreshes of one connection's tokens until commit (single-flight across processes).
func (q *Queries) LockCredentials(ctx context.Context, connectionID uuid.UUID) (LockCredentialsRow, error) {
	row := q.db.QueryRow(ctx, lockCredentials, connectionID)
	var i LockCredentialsRow
	err := row.Scan(&i.Ciphertext, &i.Version)
	return i, err
}

const recordSyncFailure = `-- name: RecordSyncFailure :exec
UPDATE connections
SET status = CASE WHEN status IN ('active', 'degraded') THEN coalesce($1, status) ELSE status END,
    last_error_class = $2,
    consecutive_failures = consecutive_failures + $3,
    updated_at = now()
WHERE id = $4
`

type RecordSyncFailureParams struct {
	Status     *string
	ErrorClass *string
	Failures   int32
	ID         uuid.UUID
}

// A null status keeps the current one. Owner-set states (paused, disabled) are never overwritten.
func (q *Queries) RecordSyncFailure(ctx context.Context, arg RecordSyncFailureParams) error {
	_, err := q.db.Exec(ctx, recordSyncFailure,
		arg.Status,
		arg.ErrorClass,
		arg.Failures,
		arg.ID,
	)
	return err
}

const recordSyncSuccess = `-- name: RecordSyncSuccess :exec
UPDATE connections
SET status = CASE WHEN EXISTS (SELECT 1 FROM sync_cursors s WHERE s.connection_id = $1 AND s.status = 'degraded'
                               AND (EXISTS (SELECT 1 FROM schedules x WHERE x.connection_id = s.connection_id
                                            AND x.stream = s.stream AND x.enabled)
                                    OR NOT EXISTS (SELECT 1 FROM schedules x WHERE x.connection_id = s.connection_id
                                                   AND x.stream = s.stream)))
                  THEN 'degraded' ELSE 'active' END,
    last_success_at = now(), last_error_class = NULL, consecutive_failures = 0, updated_at = now()
WHERE id = $1 AND status IN ('active', 'degraded')
`

// The connection stays degraded while any of its streams is, except one whose schedules the
// owner has all disabled.
func (q *Queries) RecordSyncSuccess(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, recordSyncSuccess, id)
	return err
}

const setStreamStatus = `-- name: SetStreamStatus :exec
INSERT INTO sync_cursors (connection_id, stream, status, status_reason)
VALUES ($1, $2, $3, $4)
ON CONFLICT (connection_id, stream) DO UPDATE
SET status = excluded.status, status_reason = excluded.status_reason, updated_at = now()
`

type SetStreamStatusParams struct {
	ConnectionID uuid.UUID
	Stream       string
	Status       string
	StatusReason *string
}

func (q *Queries) SetStreamStatus(ctx context.Context, arg SetStreamStatusParams) error {
	_, err := q.db.Exec(ctx, setStreamStatus,
		arg.ConnectionID,
		arg.Stream,
		arg.Status,
		arg.StatusReason,
	)
	return err
}

const upsertCredentials = `-- name: UpsertCredentials :exec
INSERT INTO credentials (connection_id, ciphertext, key_id, access_expires_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (connection_id) DO UPDATE
SET ciphertext = excluded.ciphertext, key_id = excluded.key_id, access_expires_at = excluded.access_expires_at,
    version = credentials.version + 1, updated_at = now()
`

type UpsertCredentialsParams struct {
	ConnectionID    uuid.UUID
	Ciphertext      []byte
	KeyID           string
	AccessExpiresAt *time.Time
}

func (q *Queries) UpsertCredentials(ctx context.Context, arg UpsertCredentialsParams) error {
	_, err := q.db.Exec(ctx, upsertCredentials,
		arg.ConnectionID,
		arg.Ciphertext,
		arg.KeyID,
		arg.AccessExpiresAt,
	)
	return err
}
