// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countDocumentResults = `-- name: CountDocumentResults :one
SELECT count(*) FROM lab_results r JOIN lab_reports p ON p.id = r.report_id WHERE p.document_id = $1
`

func (q *Queries) CountDocumentResults(ctx context.Context, documentID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentResults, documentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDocumentKey = `-- name: DeleteDocumentKey :execrows
DELETE FROM document_keys WHERE document_id = $1
`

func (q *Queries) DeleteDocumentKey(ctx context.Context, documentID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDocumentKey, documentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExtractionRuns = `-- name: DeleteExtractionRuns :many
DELETE FROM extraction_runs WHERE document_id = $1 RETURNING response_blob_sha256
`

// Runs, their rows and edits go with the original; confirmed results keep copies of what they need.
func (q *Queries) DeleteExtractionRuns(ctx context.Context, documentID uuid.UUID) ([][]byte, error) {
	rows, err := q.db.Query(ctx, deleteExtractionRuns, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var response_blob_sha256 []byte
		if err := rows.Scan(&response_blob_sha256); err != nil {
			return nil, err
		}
		items = append(items, response_blob_sha256)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteLabReports = `-- name: DeleteLabReports :execrows
DELETE FROM lab_reports WHERE document_id = $1
`

func (q *Queries) DeleteLabReports(ctx context.Context, documentID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLabReports, documentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDocument = `-- name: GetDocument :one
SELECT id, user_id, status, sha256, blob_sha256, filename_ciphertext, size_bytes, page_count, uploaded_at, uploaded_by, retention_until, deleted_at FROM documents WHERE user_id = $1 AND id = $2
`

type GetDocumentParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, arg.UserID, arg.ID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Sha256,
		&i.BlobSha256,
		&i.FilenameCiphertext,
		&i.SizeBytes,
		&i.PageCount,
		&i.UploadedAt,
		&i.UploadedBy,
		&i.RetentionUntil,
		&i.DeletedAt,
	)
	return i, err
}

const getDocumentKey = `-- name: GetDocumentKey :one
SELECT ciphertext FROM document_keys WHERE document_id = $1
`

func (q *Queries) GetDocumentKey(ctx context.Context, documentID uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getDocumentKey, documentID)
	var ciphertext []byte
	err := row.Scan(&ciphertext)
	return ciphertext, err
}

const getLiveDocumentBySHA256 = `-- name: GetLiveDocumentBySHA256 :one
SELECT id, user_id, status, sha256, blob_sha256, filename_ciphertext, size_bytes, page_count, uploaded_at, uploaded_by, retention_until, deleted_at FROM documents WHERE user_id = $1 AND sha256 = $2
`

type GetLiveDocumentBySHA256Params struct {
	UserID uuid.UUID
	Sha256 []byte
}

func (q *Queries) GetLiveDocumentBySHA256(ctx context.Context, arg GetLiveDocumentBySHA256Params) (Document, error) {
	row := q.db.QueryRow(ctx, getLiveDocumentBySHA256, arg.UserID, arg.Sha256)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Sha256,
		&i.BlobSha256,
		&i.FilenameCiphertext,
		&i.SizeBytes,
		&i.PageCount,
		&i.UploadedAt,
		&i.UploadedBy,
		&i.RetentionUntil,
		&i.DeletedAt,
	)
	return i, err
}

const insertDocument = `-- name: InsertDocument :exec

INSERT INTO documents (id, user_id, sha256, blob_sha256, filename_ciphertext, size_bytes, page_count, uploaded_by, retention_until)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertDocumentParams struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	Sha256             []byte
	BlobSha256         []byte
	FilenameCiphertext []byte
	SizeBytes          int64
	PageCount          int32
	UploadedBy         string
	RetentionUntil     *time.Time
}

// Lab documents (J12.1); see docs/architecture/lab-documents.md#storage.
func (q *Queries) InsertDocument(ctx context.Context, arg InsertDocumentParams) error {
	_, err := q.db.Exec(ctx, insertDocument,
		arg.ID,
		arg.UserID,
		arg.Sha256,
		arg.BlobSha256,
		arg.FilenameCiphertext,
		arg.SizeBytes,
		arg.PageCount,
		arg.UploadedBy,
		arg.RetentionUntil,
	)
	return err
}

const insertDocumentKey = `-- name: InsertDocumentKey :exec
INSERT INTO document_keys (document_id, ciphertext, key_id) VALUES ($1, $2, $3)
`

type InsertDocumentKeyParams struct {
	DocumentID uuid.UUID
	Ciphertext []byte
	KeyID      string
}

func (q *Queries) InsertDocumentKey(ctx context.Context, arg InsertDocumentKeyParams) error {
	_, err := q.db.Exec(ctx, insertDocumentKey, arg.DocumentID, arg.Ciphertext, arg.KeyID)
	return err
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, user_id, status, sha256, blob_sha256, filename_ciphertext, size_bytes, page_count, uploaded_at, uploaded_by, retention_until, deleted_at FROM documents
WHERE user_id = $1 AND status <> 'deleted' AND ($2::uuid IS NULL OR id < $2::uuid)
ORDER BY id DESC
LIMIT $3
`

type ListDocumentsParams struct {
	UserID uuid.UUID
	After  *uuid.UUID
	Lim    int32
}

// Newest first; ids are UUIDv7, so id order is upload order. A nil after starts at the newest.
func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocuments, arg.UserID, arg.After, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.Sha256,
			&i.BlobSha256,
			&i.FilenameCiphertext,
			&i.SizeBytes,
			&i.PageCount,
			&i.UploadedAt,
			&i.UploadedBy,
			&i.RetentionUntil,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsDue = `-- name: ListDocumentsDue :many
SELECT d.user_id, d.id FROM documents d
LEFT JOIN settings s ON s.user_id = d.user_id AND s.key = $1
WHERE d.status <> 'deleted'
  AND (d.retention_until <= $2::timestamptz OR (d.status = 'confirmed' AND s.value = 'true'::jsonb))
ORDER BY d.id
LIMIT $3
`

type ListDocumentsDueParams struct {
	AfterConfirmationKey string
	Now                  time.Time
	Lim                  int32
}

type ListDocumentsDueRow struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

// Originals the document_retention job deletes: past retention_until, or confirmed while the
// owner chose to delete originals after confirmation.
func (q *Queries) ListDocumentsDue(ctx context.Context, arg ListDocumentsDueParams) ([]ListDocumentsDueRow, error) {
	rows, err := q.db.Query(ctx, listDocumentsDue, arg.AfterConfirmationKey, arg.Now, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsDueRow
	for rows.Next() {
		var i ListDocumentsDueRow
		if err := rows.Scan(&i.UserID, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDocument = `-- name: LockDocument :one
SELECT id, user_id, status, sha256, blob_sha256, filename_ciphertext, size_bytes, page_count, uploaded_at, uploaded_by, retention_until, deleted_at FROM documents WHERE user_id = $1 AND id = $2 FOR UPDATE
`

type LockDocumentParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) LockDocument(ctx context.Context, arg LockDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, lockDocument, arg.UserID, arg.ID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Sha256,
		&i.BlobSha256,
		&i.FilenameCiphertext,
		&i.SizeBytes,
		&i.PageCount,
		&i.UploadedAt,
		&i.UploadedBy,
		&i.RetentionUntil,
		&i.DeletedAt,
	)
	return i, err
}

const lockDocumentKeysToRotate = `-- name: LockDocumentKeysToRotate :many
SELECT document_id, ciphertext FROM document_keys
WHERE key_id <> $1
ORDER BY document_id
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type LockDocumentKeysToRotateParams struct {
	KeyID string
	Batch int32
}

type LockDocumentKeysToRotateRow struct {
	DocumentID uuid.UUID
	Ciphertext []byte
}

func (q *Queries) LockDocumentKeysToRotate(ctx context.Context, arg LockDocumentKeysToRotateParams) ([]LockDocumentKeysToRotateRow, error) {
	rows, err := q.db.Query(ctx, lockDocumentKeysToRotate, arg.KeyID, arg.Batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockDocumentKeysToRotateRow
	for rows.Next() {
		var i LockDocumentKeysToRotateRow
		if err := rows.Scan(&i.DocumentID, &i.Ciphertext); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resealDocumentKey = `-- name: ResealDocumentKey :exec
UPDATE document_keys SET ciphertext = $1, key_id = $2 WHERE document_id = $3
`

type ResealDocumentKeyParams struct {
	Ciphertext []byte
	KeyID      string
	DocumentID uuid.UUID
}

func (q *Queries) ResealDocumentKey(ctx context.Context, arg ResealDocumentKeyParams) error {
	_, err := q.db.Exec(ctx, resealDocumentKey, arg.Ciphertext, arg.KeyID, arg.DocumentID)
	return err
}

const setDocumentRetention = `-- name: SetDocumentRetention :exec
UPDATE documents
SET retention_until = CASE WHEN $1::integer IS NULL THEN NULL
                           ELSE uploaded_at + make_interval(days => $1::integer) END
WHERE user_id = $2 AND status <> 'deleted'
`

type SetDocumentRetentionParams struct {
	Days   *int32
	UserID uuid.UUID
}

// Applies documents.retention_days (null keeps originals) to every live document of the user.
func (q *Queries) SetDocumentRetention(ctx context.Context, arg SetDocumentRetentionParams) error {
	_, err := q.db.Exec(ctx, setDocumentRetention, arg.Days, arg.UserID)
	return err
}

const tombstoneDocument = `-- name: TombstoneDocument :exec
UPDATE documents SET status = 'deleted', sha256 = NULL, blob_sha256 = NULL, filename_ciphertext = NULL, deleted_at = now()
WHERE id = $1
`

func (q *Queries) TombstoneDocument(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, tombstoneDocument, id)
	return err
}
