// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: extraction.sql

package dbq

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const abandonExtractionRuns = `-- name: AbandonExtractionRuns :exec
UPDATE extraction_runs SET status = 'failed', error_class = 'abandoned', finished_at = now()
WHERE document_id = $1 AND status IN ('queued', 'running')
`

// Called under the document lock once no extraction job is active: a run still queued or
// running lost its job (e.g. reaped after a crash on its last attempt).
func (q *Queries) AbandonExtractionRuns(ctx context.Context, documentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, abandonExtractionRuns, documentID)
	return err
}

const finishExtractionRun = `-- name: FinishExtractionRun :exec
UPDATE extraction_runs
SET status = $1, model = coalesce($2, model), provider_request_id = $3,
    response_blob_sha256 = $4, doc_meta = $5, usage = $6, warnings = $7,
    error_class = $8, finished_at = now()
WHERE id = $9
`

type FinishExtractionRunParams struct {
	Status             string
	Model              *string
	ProviderRequestID  *string
	ResponseBlobSha256 []byte
	DocMeta            json.RawMessage
	Usage              json.RawMessage
	Warnings           []string
	ErrorClass         *string
	ID                 uuid.UUID
}

// status is succeeded or failed; a failed run may still keep the (sealed) response it got.
func (q *Queries) FinishExtractionRun(ctx context.Context, arg FinishExtractionRunParams) error {
	_, err := q.db.Exec(ctx, finishExtractionRun,
		arg.Status,
		arg.Model,
		arg.ProviderRequestID,
		arg.ResponseBlobSha256,
		arg.DocMeta,
		arg.Usage,
		arg.Warnings,
		arg.ErrorClass,
		arg.ID,
	)
	return err
}

const getExtractionRun = `-- name: GetExtractionRun :one
SELECT id, document_id, user_id, job_id, status, provider, model, external, consent, schema_version, prompt_version, provider_request_id, response_blob_sha256, doc_meta, usage, warnings, error_class, created_by, created_at, started_at, finished_at FROM extraction_runs WHERE id = $1
`

func (q *Queries) GetExtractionRun(ctx context.Context, id uuid.UUID) (ExtractionRun, error) {
	row := q.db.QueryRow(ctx, getExtractionRun, id)
	var i ExtractionRun
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.UserID,
		&i.JobID,
		&i.Status,
		&i.Provider,
		&i.Model,
		&i.External,
		&i.Consent,
		&i.SchemaVersion,
		&i.PromptVersion,
		&i.ProviderRequestID,
		&i.ResponseBlobSha256,
		&i.DocMeta,
		&i.Usage,
		&i.Warnings,
		&i.ErrorClass,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const hasSucceededExtraction = `-- name: HasSucceededExtraction :one
SELECT EXISTS (SELECT 1 FROM extraction_runs WHERE document_id = $1 AND status IN ('succeeded', 'confirmed'))
`

func (q *Queries) HasSucceededExtraction(ctx context.Context, documentID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasSucceededExtraction, documentID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertExtractedRow = `-- name: InsertExtractedRow :exec
INSERT INTO lab_extracted_rows (run_id, row_index, page, analyte_label, value_text, value_numeric, comparator, unit_text,
  reference_range_text, ref_low, ref_high, abnormal_flag_printed, specimen_type, collected_at, reported_at, laboratory,
  evidence_text, bbox, confidence, warnings)
VALUES ($1, $2, $3, $4, $5, $6, $7,
  $8, $9, $10, $11, $12,
  $13, $14, $15, $16, $17,
  $18, $19, $20)
`

type InsertExtractedRowParams struct {
	RunID               uuid.UUID
	RowIndex            int32
	Page                *int32
	AnalyteLabel        string
	ValueText           *string
	ValueNumeric        *float64
	Comparator          *string
	UnitText            *string
	ReferenceRangeText  *string
	RefLow              *float64
	RefHigh             *float64
	AbnormalFlagPrinted *string
	SpecimenType        *string
	CollectedAt         *string
	ReportedAt          *string
	Laboratory          *string
	EvidenceText        *string
	Bbox                []byte
	Confidence          *float32
	Warnings            []string
}

func (q *Queries) InsertExtractedRow(ctx context.Context, arg InsertExtractedRowParams) error {
	_, err := q.db.Exec(ctx, insertExtractedRow,
		arg.RunID,
		arg.RowIndex,
		arg.Page,
		arg.AnalyteLabel,
		arg.ValueText,
		arg.ValueNumeric,
		arg.Comparator,
		arg.UnitText,
		arg.ReferenceRangeText,
		arg.RefLow,
		arg.RefHigh,
		arg.AbnormalFlagPrinted,
		arg.SpecimenType,
		arg.CollectedAt,
		arg.ReportedAt,
		arg.Laboratory,
		arg.EvidenceText,
		arg.Bbox,
		arg.Confidence,
		arg.Warnings,
	)
	return err
}

const insertExtractionRun = `-- name: InsertExtractionRun :exec

INSERT INTO extraction_runs (id, document_id, user_id, job_id, provider, model, external, consent, schema_version, prompt_version, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertExtractionRunParams struct {
	ID            uuid.UUID
	DocumentID    uuid.UUID
	UserID        uuid.UUID
	JobID         *uuid.UUID
	Provider      string
	Model         *string
	External      bool
	Consent       []byte
	SchemaVersion string
	PromptVersion string
	CreatedBy     string
}

// Extraction runs (J12.3); see docs/architecture/lab-documents.md#extraction-provider-interface.
func (q *Queries) InsertExtractionRun(ctx context.Context, arg InsertExtractionRunParams) error {
	_, err := q.db.Exec(ctx, insertExtractionRun,
		arg.ID,
		arg.DocumentID,
		arg.UserID,
		arg.JobID,
		arg.Provider,
		arg.Model,
		arg.External,
		arg.Consent,
		arg.SchemaVersion,
		arg.PromptVersion,
		arg.CreatedBy,
	)
	return err
}

const listExtractionRuns = `-- name: ListExtractionRuns :many
SELECT r.id, r.document_id, r.status, r.provider, r.model, r.external, r.consent, r.schema_version, r.prompt_version,
       r.provider_request_id, r.doc_meta, r.usage, r.warnings, r.error_class, r.created_by, r.created_at, r.started_at,
       r.finished_at, (SELECT count(*) FROM lab_extracted_rows x WHERE x.run_id = r.id) AS row_count
FROM extraction_runs r
WHERE r.user_id = $1 AND r.document_id = $2
ORDER BY r.created_at DESC, r.id DESC
`

type ListExtractionRunsParams struct {
	UserID     uuid.UUID
	DocumentID uuid.UUID
}

type ListExtractionRunsRow struct {
	ID                uuid.UUID
	DocumentID        uuid.UUID
	Status            string
	Provider          string
	Model             *string
	External          bool
	Consent           []byte
	SchemaVersion     string
	PromptVersion     string
	ProviderRequestID *string
	DocMeta           json.RawMessage
	Usage             json.RawMessage
	Warnings          []string
	ErrorClass        *string
	CreatedBy         string
	CreatedAt         time.Time
	StartedAt         *time.Time
	FinishedAt        *time.Time
	RowCount          int64
}

// Newest first, with the number of extracted rows. Never the response blob.
func (q *Queries) ListExtractionRuns(ctx context.Context, arg ListExtractionRunsParams) ([]ListExtractionRunsRow, error) {
	rows, err := q.db.Query(ctx, listExtractionRuns, arg.UserID, arg.DocumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExtractionRunsRow
	for rows.Next() {
		var i ListExtractionRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Status,
			&i.Provider,
			&i.Model,
			&i.External,
			&i.Consent,
			&i.SchemaVersion,
			&i.PromptVersion,
			&i.ProviderRequestID,
			&i.DocMeta,
			&i.Usage,
			&i.Warnings,
			&i.ErrorClass,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.RowCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueExtractionRun = `-- name: RequeueExtractionRun :exec
UPDATE extraction_runs SET status = 'queued', error_class = $1 WHERE id = $2 AND status IN ('queued', 'running')
`

type RequeueExtractionRunParams struct {
	ErrorClass *string
	ID         uuid.UUID
}

// The attempt failed and the job retries; error_class says why.
func (q *Queries) RequeueExtractionRun(ctx context.Context, arg RequeueExtractionRunParams) error {
	_, err := q.db.Exec(ctx, requeueExtractionRun, arg.ErrorClass, arg.ID)
	return err
}

const setDocumentStatus = `-- name: SetDocumentStatus :exec
UPDATE documents SET status = $1 WHERE id = $2 AND status IN ('uploaded', 'extracting', 'needs_review')
`

type SetDocumentStatusParams struct {
	Status string
	ID     uuid.UUID
}

// Moves a live document between uploaded, extracting and needs_review; confirmed and deleted stay.
func (q *Queries) SetDocumentStatus(ctx context.Context, arg SetDocumentStatusParams) error {
	_, err := q.db.Exec(ctx, setDocumentStatus, arg.Status, arg.ID)
	return err
}

const startExtractionRun = `-- name: StartExtractionRun :execrows
UPDATE extraction_runs SET status = 'running', started_at = coalesce(started_at, now())
WHERE id = $1 AND status IN ('queued', 'running')
`

func (q *Queries) StartExtractionRun(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, startExtractionRun, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
