// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: healthexport.sql

package dbq

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const appleExportOverlaps = `-- name: AppleExportOverlaps :many

WITH p AS (
  SELECT unnest($2::integer[]) AS ord, unnest($3::text[]) AS kind, unnest($4::text[]) AS code,
    unnest($5::timestamptz[]) AS start_at, unnest($6::timestamptz[]) AS end_at,
    unnest($7::float8[]) AS val, unnest($8::text[]) AS origin
)
SELECT p.ord::integer AS ord FROM p
WHERE CASE p.kind
  WHEN 'measurement' THEN EXISTS (
    SELECT 1 FROM measurements m
    JOIN metric_catalog c ON c.id = m.metric_id
    JOIN data_origins o ON o.id = m.origin_id
    JOIN raw_payloads r ON r.id = m.raw_payload_id
    WHERE m.user_id = $1 AND c.code = p.code
      AND m.start_at > p.start_at - interval '1 second' AND m.start_at < p.start_at + interval '1 second'
      AND abs(extract(epoch FROM coalesce(m.end_at, m.start_at) - p.end_at)) < 1 AND o.name = p.origin
      AND r.stream = 'healthkit.samples.v1' AND m.superseded_at IS NULL AND m.deleted_at IS NULL
      AND (p.val = 'NaN'::float8 OR abs(coalesce(m.source_value, m.value) - p.val) <= 1e-4 * greatest(abs(p.val), 1e-6)))
  WHEN 'sleep' THEN EXISTS (
    SELECT 1 FROM sleep_sessions s
    JOIN sleep_stages st ON st.session_id = s.id
    JOIN data_origins o ON o.id = s.origin_id
    JOIN raw_payloads r ON r.id = s.raw_payload_id
    WHERE s.user_id = $1 AND s.sleep_date BETWEEN (p.start_at AT TIME ZONE 'UTC')::date - 2 AND (p.end_at AT TIME ZONE 'UTC')::date + 2
      AND st.stage = p.code AND abs(extract(epoch FROM st.start_at - p.start_at)) < 1
      AND abs(extract(epoch FROM st.end_at - p.end_at)) < 1 AND o.name = p.origin
      AND r.stream = 'healthkit.samples.v1' AND s.superseded_at IS NULL AND s.deleted_at IS NULL)
  WHEN 'workout' THEN EXISTS (
    SELECT 1 FROM workouts w
    JOIN data_origins o ON o.id = w.origin_id
    JOIN raw_payloads r ON r.id = w.raw_payload_id
    WHERE w.user_id = $1 AND w.sport = p.code
      AND w.start_at > p.start_at - interval '1 second' AND w.start_at < p.start_at + interval '1 second'
      AND abs(extract(epoch FROM w.end_at - p.end_at)) < 1
      AND o.name = p.origin AND r.stream = 'healthkit.samples.v1' AND w.superseded_at IS NULL AND w.deleted_at IS NULL)
  WHEN 'event' THEN EXISTS (
    SELECT 1 FROM health_events e
    JOIN data_origins o ON o.id = e.origin_id
    JOIN raw_payloads r ON r.id = e.raw_payload_id
    WHERE e.user_id = $1 AND e.code = p.code
      AND e.start_at > p.start_at - interval '1 second' AND e.start_at < p.start_at + interval '1 second'
      AND abs(extract(epoch FROM coalesce(e.end_at, e.start_at) - p.end_at)) < 1 AND o.name = p.origin
      AND r.stream = 'healthkit.samples.v1' AND e.superseded_at IS NULL AND e.deleted_at IS NULL)
  ELSE false
END
ORDER BY p.ord
`

type AppleExportOverlapsParams struct {
	UserID  uuid.UUID
	Ords    []int32
	Kinds   []string
	Codes   []string
	Starts  []time.Time
	Ends    []time.Time
	Vals    []float64
	Origins []string
}

// Apple Health export importer (J15.8; docs/architecture/apple-health.md#export-importer-fallback).
// The ordinals (@ords) of the probes that match an active row the HealthKit app synced (raw stream
// healthkit.samples.v1) for the user: same kind and code (metric, sleep stage, sport or event
// code), origin name, start and end (= start for samples) within a second, since the export
// writes whole seconds, and, unless the probe value is NaN, the value in the source unit within a
// relative 1e-4.
func (q *Queries) AppleExportOverlaps(ctx context.Context, arg AppleExportOverlapsParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, appleExportOverlaps,
		arg.UserID,
		arg.Ords,
		arg.Kinds,
		arg.Codes,
		arg.Starts,
		arg.Ends,
		arg.Vals,
		arg.Origins,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var ord int32
		if err := rows.Scan(&ord); err != nil {
			return nil, err
		}
		items = append(items, ord)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertImportRun = `-- name: InsertImportRun :exec
INSERT INTO import_runs (id, user_id, connection_id, source, status, stats, finished_at)
VALUES ($1, $2, $3, $4, 'done', $5, now())
`

type InsertImportRunParams struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	ConnectionID *uuid.UUID
	Source       string
	Stats        json.RawMessage
}

func (q *Queries) InsertImportRun(ctx context.Context, arg InsertImportRunParams) error {
	_, err := q.db.Exec(ctx, insertImportRun,
		arg.ID,
		arg.UserID,
		arg.ConnectionID,
		arg.Source,
		arg.Stats,
	)
	return err
}
