// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hooks.sql

package dbq

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getHookConnection = `-- name: GetHookConnection :one

SELECT c.id, c.user_id, c.status, c.account_key FROM connections c JOIN providers p ON p.id = c.provider_id
WHERE c.hook_token_hash = $1 AND p.code = $2 AND c.status <> 'disabled'
`

type GetHookConnectionParams struct {
	HookTokenHash []byte
	Provider      string
}

type GetHookConnectionRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Status     string
	AccountKey []byte
}

// Provider notification hooks (J08.4); see docs/providers/withings.md#notifications.
// The connection a notification callback token belongs to; disconnected connections have none.
func (q *Queries) GetHookConnection(ctx context.Context, arg GetHookConnectionParams) (GetHookConnectionRow, error) {
	row := q.db.QueryRow(ctx, getHookConnection, arg.HookTokenHash, arg.Provider)
	var i GetHookConnectionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.AccountKey,
	)
	return i, err
}

const getUserSetting = `-- name: GetUserSetting :one
SELECT value FROM settings WHERE user_id = $1 AND key = $2
`

type GetUserSettingParams struct {
	UserID uuid.UUID
	Key    string
}

func (q *Queries) GetUserSetting(ctx context.Context, arg GetUserSettingParams) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, getUserSetting, arg.UserID, arg.Key)
	var value json.RawMessage
	err := row.Scan(&value)
	return value, err
}

const listHookConnections = `-- name: ListHookConnections :many
SELECT c.id, c.status, c.hook_token_hash FROM connections c JOIN providers p ON p.id = c.provider_id
WHERE c.user_id = $1 AND p.code = $2
ORDER BY c.id
`

type ListHookConnectionsParams struct {
	UserID   uuid.UUID
	Provider string
}

type ListHookConnectionsRow struct {
	ID            uuid.UUID
	Status        string
	HookTokenHash []byte
}

func (q *Queries) ListHookConnections(ctx context.Context, arg ListHookConnectionsParams) ([]ListHookConnectionsRow, error) {
	rows, err := q.db.Query(ctx, listHookConnections, arg.UserID, arg.Provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHookConnectionsRow
	for rows.Next() {
		var i ListHookConnectionsRow
		if err := rows.Scan(&i.ID, &i.Status, &i.HookTokenHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putUserSetting = `-- name: PutUserSetting :exec
INSERT INTO settings (user_id, key, value) VALUES ($1, $2, $3)
ON CONFLICT (user_id, key) DO UPDATE SET value = excluded.value, updated_at = now()
`

type PutUserSettingParams struct {
	UserID uuid.UUID
	Key    string
	Value  json.RawMessage
}

func (q *Queries) PutUserSetting(ctx context.Context, arg PutUserSettingParams) error {
	_, err := q.db.Exec(ctx, putUserSetting, arg.UserID, arg.Key, arg.Value)
	return err
}

const setHookTokenHash = `-- name: SetHookTokenHash :exec
UPDATE connections SET hook_token_hash = $1, updated_at = now() WHERE id = $2
`

type SetHookTokenHashParams struct {
	HookTokenHash []byte
	ID            uuid.UUID
}

func (q *Queries) SetHookTokenHash(ctx context.Context, arg SetHookTokenHashParams) error {
	_, err := q.db.Exec(ctx, setHookTokenHash, arg.HookTokenHash, arg.ID)
	return err
}
