// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package dbq

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const aggregatesPending = `-- name: AggregatesPending :one
SELECT EXISTS (
  SELECT 1 FROM resolution_dirty r
  WHERE r.user_id = $1
    AND ($2::text IS NULL OR r.metric_id = (SELECT id FROM metric_catalog WHERE code = $2::text))
    AND ($3::date IS NULL OR r.local_date >= $3::date)
    AND ($4::date IS NULL OR r.local_date <= $4::date))::boolean
`

type AggregatesPendingParams struct {
	UserID   uuid.UUID
	Metric   *string
	FromDate *time.Time
	ToDate   *time.Time
}

// Whether dirty marks (of one metric and range, when given) still wait for the rebuild job.
func (q *Queries) AggregatesPending(ctx context.Context, arg AggregatesPendingParams) (bool, error) {
	row := q.db.QueryRow(ctx, aggregatesPending,
		arg.UserID,
		arg.Metric,
		arg.FromDate,
		arg.ToDate,
	)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const inventoryAnalytes = `-- name: InventoryAnalytes :many
WITH r AS (
  SELECT x.analyte_id, x.id, x.collected_at, x.collected_date, COALESCE(x.canonical_value, x.value_numeric)::float8 AS value,
    (CASE WHEN x.canonical_value IS NOT NULL THEN x.canonical_unit ELSE x.unit_text END)::text AS unit, x.value_text
  FROM lab_results x WHERE x.user_id = $1 AND x.analyte_id IS NOT NULL
), s AS (
  SELECT analyte_id, count(*)::bigint AS n, count(DISTINCT collected_date)::integer AS days,
    min(collected_date)::date AS first_date, max(collected_date)::date AS last_date
  FROM r GROUP BY analyte_id
), t AS (
  SELECT analyte_id, min(collected_at)::timestamptz AS first_at, max(collected_at)::timestamptz AS last_at
  FROM r WHERE collected_at IS NOT NULL GROUP BY analyte_id
), newest AS (
  SELECT DISTINCT ON (analyte_id) analyte_id, collected_at, collected_date, value, unit, value_text
  FROM r ORDER BY analyte_id, collected_date DESC, collected_at DESC NULLS LAST, id DESC
)
SELECT a.code, a.name, a.canonical_unit, s.n AS count, s.days, s.first_date, s.last_date, t.first_at, t.last_at,
  l.collected_at AS latest_at, l.collected_date AS latest_date, l.value AS latest_value, l.unit AS latest_unit,
  l.value_text AS latest_text
FROM s
JOIN analytes a ON a.id = s.analyte_id
LEFT JOIN t ON t.analyte_id = s.analyte_id
LEFT JOIN newest l ON l.analyte_id = s.analyte_id
ORDER BY a.code
`

type InventoryAnalytesRow struct {
	Code          string
	Name          string
	CanonicalUnit *string
	Count         int64
	Days          int32
	FirstDate     time.Time
	LastDate      time.Time
	FirstAt       *time.Time
	LastAt        *time.Time
	LatestAt      *time.Time
	LatestDate    *time.Time
	LatestValue   *float64
	LatestUnit    *string
	LatestText    *string
}

// Confirmed lab results per catalogue analyte, with the newest one: its canonical value and unit,
// else its printed number and unit, and its printed text.
func (q *Queries) InventoryAnalytes(ctx context.Context, userID uuid.UUID) ([]InventoryAnalytesRow, error) {
	rows, err := q.db.Query(ctx, inventoryAnalytes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryAnalytesRow
	for rows.Next() {
		var i InventoryAnalytesRow
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.CanonicalUnit,
			&i.Count,
			&i.Days,
			&i.FirstDate,
			&i.LastDate,
			&i.FirstAt,
			&i.LastAt,
			&i.LatestAt,
			&i.LatestDate,
			&i.LatestValue,
			&i.LatestUnit,
			&i.LatestText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const inventoryMetricBounds = `-- name: InventoryMetricBounds :many

SELECT mc.code AS metric, f.start_at AS first_at, f.local_date AS first_date,
  l.start_at AS last_at, l.local_date AS last_date, l.value AS latest_value
FROM metric_catalog mc
CROSS JOIN LATERAL (
  SELECT x.start_at, x.local_date FROM measurements x
  WHERE x.user_id = $1 AND x.metric_id = mc.id AND x.superseded_at IS NULL AND x.deleted_at IS NULL
  ORDER BY x.start_at LIMIT 1) f
CROSS JOIN LATERAL (
  SELECT x.start_at, x.local_date, x.value FROM measurements x
  WHERE x.user_id = $1 AND x.metric_id = mc.id AND x.superseded_at IS NULL AND x.deleted_at IS NULL
  ORDER BY x.start_at DESC, x.id DESC LIMIT 1) l
ORDER BY mc.code
`

type InventoryMetricBoundsRow struct {
	Metric      string
	FirstAt     time.Time
	FirstDate   time.Time
	LastAt      time.Time
	LastDate    time.Time
	LatestValue float64
}

// Inventory, events and source series (J21.5, J21.6; docs/architecture/api.md). Metric counts come
// from the hourly aggregates plus daily values, so a request never scans the measurements of a
// whole history; the other record tables are small and read directly.
// The first and newest active row of every metric that has one: two index probes per catalogue code.
func (q *Queries) InventoryMetricBounds(ctx context.Context, userID uuid.UUID) ([]InventoryMetricBoundsRow, error) {
	rows, err := q.db.Query(ctx, inventoryMetricBounds, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryMetricBoundsRow
	for rows.Next() {
		var i InventoryMetricBoundsRow
		if err := rows.Scan(
			&i.Metric,
			&i.FirstAt,
			&i.FirstDate,
			&i.LastAt,
			&i.LastDate,
			&i.LatestValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const inventoryMetricSources = `-- name: InventoryMetricSources :many
WITH src AS MATERIALIZED (
  SELECT a.metric_id, a.connection_id, a.device_id, a.origin_id, a.local_date, a.samples::bigint AS n
  FROM source_hourly_aggregates a WHERE a.user_id = $1
  UNION ALL
  SELECT x.metric_id, x.connection_id, x.device_id, x.origin_id, x.local_date, 1::bigint
  FROM measurements x
  WHERE x.user_id = $1 AND x.kind = 'daily_value' AND x.superseded_at IS NULL AND x.deleted_at IS NULL
), days AS (
  SELECT d.metric_id, count(*)::integer AS days FROM (SELECT DISTINCT metric_id, local_date FROM src) d GROUP BY d.metric_id
)
SELECT mc.code AS metric, dy.days, s.n::bigint AS count, p.code AS provider, s.device_id,
  COALESCE(d.device_type, '')::text AS device_type, COALESCE(d.model, '')::text AS device_model,
  COALESCE(o.origin_key, '')::text AS origin_key, COALESCE(o.name, '')::text AS origin_name
FROM (SELECT metric_id, connection_id, device_id, origin_id, sum(n) AS n FROM src GROUP BY 1, 2, 3, 4) s
JOIN days dy ON dy.metric_id = s.metric_id
JOIN metric_catalog mc ON mc.id = s.metric_id
JOIN connections c ON c.id = s.connection_id
JOIN providers p ON p.id = c.provider_id
LEFT JOIN devices d ON d.id = s.device_id
LEFT JOIN data_origins o ON o.id = s.origin_id
ORDER BY mc.code, p.code, s.connection_id
`

type InventoryMetricSourcesRow struct {
	Metric      string
	Days        int32
	Count       int64
	Provider    string
	DeviceID    *uuid.UUID
	DeviceType  string
	DeviceModel string
	OriginKey   string
	OriginName  string
}

// Per metric and source: rows in the hourly aggregates (an interval once per hour it touches)
// plus active daily values, with the metric's local dates that have any.
func (q *Queries) InventoryMetricSources(ctx context.Context, userID uuid.UUID) ([]InventoryMetricSourcesRow, error) {
	rows, err := q.db.Query(ctx, inventoryMetricSources, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryMetricSourcesRow
	for rows.Next() {
		var i InventoryMetricSourcesRow
		if err := rows.Scan(
			&i.Metric,
			&i.Days,
			&i.Count,
			&i.Provider,
			&i.DeviceID,
			&i.DeviceType,
			&i.DeviceModel,
			&i.OriginKey,
			&i.OriginName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const inventoryRecords = `-- name: InventoryRecords :many
WITH r AS MATERIALIZED (
  SELECT 'event'::text AS kind, x.code, x.start_at AS at, x.local_date, x.connection_id, x.device_id, x.origin_id,
    x.value, x.level, NULL::text AS text, NULL::bigint AS group_id
  FROM health_events x WHERE x.user_id = $1 AND x.superseded_at IS NULL AND x.deleted_at IS NULL
  UNION ALL
  SELECT 'group', x.kind, x.measured_at, x.local_date, x.connection_id, x.device_id, x.origin_id, NULL, NULL, NULL, x.id
  FROM measurement_groups x WHERE x.user_id = $1 AND x.superseded_at IS NULL AND x.deleted_at IS NULL
  UNION ALL
  SELECT 'sleep', 'sleep', x.start_at, x.sleep_date, x.connection_id, x.device_id, x.origin_id, x.asleep_s::float8, NULL, NULL, NULL
  FROM sleep_sessions x WHERE x.user_id = $1 AND x.superseded_at IS NULL AND x.deleted_at IS NULL
  UNION ALL
  SELECT 'workouts', 'workouts', x.start_at, x.local_date, x.connection_id, x.device_id, x.origin_id, NULL, NULL, x.sport, NULL
  FROM workouts x WHERE x.user_id = $1 AND x.superseded_at IS NULL AND x.deleted_at IS NULL
), days AS (
  SELECT kind, code, count(DISTINCT local_date)::integer AS days FROM r GROUP BY kind, code
), newest AS (
  SELECT DISTINCT ON (kind, code) kind, code, value, level, text, group_id FROM r ORDER BY kind, code, at DESC
)
SELECT s.kind, s.code, dy.days, s.n AS count, s.first_at, s.last_at, s.first_date, s.last_date,
  l.value AS latest_value, l.level AS latest_level, l.text AS latest_text, l.group_id AS latest_group_id,
  p.code AS provider, s.device_id,
  COALESCE(d.device_type, '')::text AS device_type, COALESCE(d.model, '')::text AS device_model,
  COALESCE(o.origin_key, '')::text AS origin_key, COALESCE(o.name, '')::text AS origin_name
FROM (
  SELECT kind, code, connection_id, device_id, origin_id, count(*)::bigint AS n,
    min(at)::timestamptz AS first_at, max(at)::timestamptz AS last_at,
    min(local_date)::date AS first_date, max(local_date)::date AS last_date
  FROM r GROUP BY 1, 2, 3, 4, 5
) s
JOIN days dy ON dy.kind = s.kind AND dy.code = s.code
LEFT JOIN newest l ON l.kind = s.kind AND l.code = s.code
JOIN connections c ON c.id = s.connection_id
JOIN providers p ON p.id = c.provider_id
LEFT JOIN devices d ON d.id = s.device_id
LEFT JOIN data_origins o ON o.id = s.origin_id
ORDER BY s.kind, s.code, p.code, s.connection_id
`

type InventoryRecordsRow struct {
	Kind          string
	Code          string
	Days          int32
	Count         int64
	FirstAt       time.Time
	LastAt        time.Time
	FirstDate     time.Time
	LastDate      time.Time
	LatestValue   *float64
	LatestLevel   *string
	LatestText    *string
	LatestGroupID *int64
	Provider      string
	DeviceID      *uuid.UUID
	DeviceType    string
	DeviceModel   string
	OriginKey     string
	OriginName    string
}

// Per kind (group, event, sleep, workouts), code and source: active records and their bounds,
// with the code's local dates and its newest record's value, level, text and group id.
func (q *Queries) InventoryRecords(ctx context.Context, userID uuid.UUID) ([]InventoryRecordsRow, error) {
	rows, err := q.db.Query(ctx, inventoryRecords, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryRecordsRow
	for rows.Next() {
		var i InventoryRecordsRow
		if err := rows.Scan(
			&i.Kind,
			&i.Code,
			&i.Days,
			&i.Count,
			&i.FirstAt,
			&i.LastAt,
			&i.FirstDate,
			&i.LastDate,
			&i.LatestValue,
			&i.LatestLevel,
			&i.LatestText,
			&i.LatestGroupID,
			&i.Provider,
			&i.DeviceID,
			&i.DeviceType,
			&i.DeviceModel,
			&i.OriginKey,
			&i.OriginName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readEvents = `-- name: ReadEvents :many
SELECT x.id, x.code, x.start_at, x.end_at, x.tz_offset_min, x.local_date, x.value, x.level, x.context, x.quality_flags,
  p.code AS provider, x.connection_id, x.device_id, d.device_type, o.origin_key, x.external_id, x.dedupe_key,
  x.raw_payload_id, nv.name AS normalizer_name, nv.version AS normalizer_version, x.ingested_at, x.normalized_at,
  x.superseded_at, COALESCE(x.superseded_by::text, '')::text AS superseded_by, x.deleted_at, x.deleted_by_raw_id
FROM health_events x
JOIN providers p ON p.id = x.provider_id
JOIN normalizer_versions nv ON nv.id = x.normalizer_version_id
LEFT JOIN devices d ON d.id = x.device_id
LEFT JOIN data_origins o ON o.id = x.origin_id
WHERE x.user_id = $1
  AND ($2::text[] IS NULL OR x.code = ANY($2::text[]))
  AND ($3::text[] IS NULL OR x.provider_id IN (SELECT id FROM providers WHERE code = ANY($3::text[])))
  AND ($4::uuid[] IS NULL OR x.connection_id = ANY($4::uuid[]))
  AND ($5::uuid[] IS NULL OR x.device_id = ANY($5::uuid[]))
  AND ($6::text[] IS NULL OR x.origin_id IN (SELECT id FROM data_origins WHERE user_id = $1 AND origin_key = ANY($6::text[])))
  AND ($7::timestamptz IS NULL OR x.start_at >= $7::timestamptz)
  AND ($8::timestamptz IS NULL OR x.start_at < $8::timestamptz)
  AND ($9::date IS NULL OR x.local_date >= $9::date)
  AND ($10::date IS NULL OR x.local_date <= $10::date)
  AND ($11::boolean OR x.superseded_at IS NULL)
  AND ($12::boolean OR x.deleted_at IS NULL)
  AND ($13::timestamptz IS NULL OR (x.start_at, x.id) > ($13::timestamptz, $14::uuid))
ORDER BY x.start_at, x.id
LIMIT $15
`

type ReadEventsParams struct {
	UserID         uuid.UUID
	Codes          []string
	Providers      []string
	Connections    []uuid.UUID
	Devices        []uuid.UUID
	Origins        []string
	StartAt        *time.Time
	EndAt          *time.Time
	StartDate      *time.Time
	EndDate        *time.Time
	WithSuperseded bool
	WithDeleted    bool
	AfterKey       *time.Time
	AfterID        uuid.UUID
	Lim            int32
}

type ReadEventsRow struct {
	ID                uuid.UUID
	Code              string
	StartAt           time.Time
	EndAt             *time.Time
	TzOffsetMin       *int16
	LocalDate         time.Time
	Value             *float64
	Level             *string
	Context           json.RawMessage
	QualityFlags      int32
	Provider          string
	ConnectionID      uuid.UUID
	DeviceID          *uuid.UUID
	DeviceType        *string
	OriginKey         *string
	ExternalID        *string
	DedupeKey         []byte
	RawPayloadID      *int64
	NormalizerName    string
	NormalizerVersion int32
	IngestedAt        time.Time
	NormalizedAt      time.Time
	SupersededAt      *time.Time
	SupersededBy      string
	DeletedAt         *time.Time
	DeletedByRawID    *int64
}

func (q *Queries) ReadEvents(ctx context.Context, arg ReadEventsParams) ([]ReadEventsRow, error) {
	rows, err := q.db.Query(ctx, readEvents,
		arg.UserID,
		arg.Codes,
		arg.Providers,
		arg.Connections,
		arg.Devices,
		arg.Origins,
		arg.StartAt,
		arg.EndAt,
		arg.StartDate,
		arg.EndDate,
		arg.WithSuperseded,
		arg.WithDeleted,
		arg.AfterKey,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReadEventsRow
	for rows.Next() {
		var i ReadEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.StartAt,
			&i.EndAt,
			&i.TzOffsetMin,
			&i.LocalDate,
			&i.Value,
			&i.Level,
			&i.Context,
			&i.QualityFlags,
			&i.Provider,
			&i.ConnectionID,
			&i.DeviceID,
			&i.DeviceType,
			&i.OriginKey,
			&i.ExternalID,
			&i.DedupeKey,
			&i.RawPayloadID,
			&i.NormalizerName,
			&i.NormalizerVersion,
			&i.IngestedAt,
			&i.NormalizedAt,
			&i.SupersededAt,
			&i.SupersededBy,
			&i.DeletedAt,
			&i.DeletedByRawID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sourceDailyValues = `-- name: SourceDailyValues :many
SELECT DISTINCT ON (x.connection_id, x.device_id, x.origin_id, x.local_date)
  x.local_date, x.value, x.connection_id, x.device_id, x.origin_id, p.code AS provider,
  COALESCE(d.device_type, '')::text AS device_type, COALESCE(d.model, '')::text AS device_model,
  COALESCE(o.origin_key, '')::text AS origin_key, COALESCE(o.name, '')::text AS origin_name,
  (o.relayed_provider_id IS NOT NULL)::boolean AS relayed
FROM measurements x
JOIN providers p ON p.id = x.provider_id
LEFT JOIN devices d ON d.id = x.device_id
LEFT JOIN data_origins o ON o.id = x.origin_id
WHERE x.user_id = $1 AND x.metric_id = (SELECT id FROM metric_catalog WHERE code = $2::text)
  AND x.kind = 'daily_value' AND x.superseded_at IS NULL AND x.deleted_at IS NULL
  AND x.local_date BETWEEN $3 AND $4
ORDER BY x.connection_id, x.device_id, x.origin_id, x.local_date, x.start_at DESC, x.id DESC
`

type SourceDailyValuesParams struct {
	UserID   uuid.UUID
	Metric   string
	FromDate time.Time
	ToDate   time.Time
}

type SourceDailyValuesRow struct {
	LocalDate    time.Time
	Value        float64
	ConnectionID uuid.UUID
	DeviceID     *uuid.UUID
	OriginID     *uuid.UUID
	Provider     string
	DeviceType   string
	DeviceModel  string
	OriginKey    string
	OriginName   string
	Relayed      bool
}

// One metric's active daily values on the local dates from_date through to_date, the newest per
// source and date, with the source identity.
func (q *Queries) SourceDailyValues(ctx context.Context, arg SourceDailyValuesParams) ([]SourceDailyValuesRow, error) {
	rows, err := q.db.Query(ctx, sourceDailyValues,
		arg.UserID,
		arg.Metric,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SourceDailyValuesRow
	for rows.Next() {
		var i SourceDailyValuesRow
		if err := rows.Scan(
			&i.LocalDate,
			&i.Value,
			&i.ConnectionID,
			&i.DeviceID,
			&i.OriginID,
			&i.Provider,
			&i.DeviceType,
			&i.DeviceModel,
			&i.OriginKey,
			&i.OriginName,
			&i.Relayed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sourceSeriesAggregates = `-- name: SourceSeriesAggregates :many
SELECT min(a.hour_start)::timestamptz AS hour_start, a.local_date,
  a.connection_id, a.device_id, a.origin_id, p.code AS provider,
  COALESCE(d.device_type, '')::text AS device_type, COALESCE(d.model, '')::text AS device_model,
  COALESCE(o.origin_key, '')::text AS origin_key, COALESCE(o.name, '')::text AS origin_name,
  (o.relayed_provider_id IS NOT NULL)::boolean AS relayed,
  sum(a.samples)::integer AS samples, sum(a.buckets)::integer AS buckets, sum(a.bucket_mean_sum)::float8 AS bucket_mean_sum,
  min(a.min_value)::float8 AS min_value, max(a.max_value)::float8 AS max_value, sum(a.interval_sum)::float8 AS interval_sum
FROM source_hourly_aggregates a
JOIN connections c ON c.id = a.connection_id
JOIN providers p ON p.id = c.provider_id
LEFT JOIN devices d ON d.id = a.device_id
LEFT JOIN data_origins o ON o.id = a.origin_id
WHERE a.user_id = $1 AND a.metric_id = (SELECT id FROM metric_catalog WHERE code = $2::text)
  AND a.hour_start >= $3 AND a.hour_start < $4
GROUP BY CASE WHEN $5::boolean THEN NULL ELSE a.hour_start END, a.local_date, a.connection_id, a.device_id, a.origin_id, p.code, d.device_type, d.model, o.origin_key, o.name, o.relayed_provider_id
ORDER BY a.connection_id, a.device_id NULLS FIRST, a.origin_id NULLS FIRST, 1
`

type SourceSeriesAggregatesParams struct {
	UserID uuid.UUID
	Metric string
	FromAt time.Time
	ToAt   time.Time
	ByDay  bool
}

type SourceSeriesAggregatesRow struct {
	HourStart     time.Time
	LocalDate     time.Time
	ConnectionID  uuid.UUID
	DeviceID      *uuid.UUID
	OriginID      *uuid.UUID
	Provider      string
	DeviceType    string
	DeviceModel   string
	OriginKey     string
	OriginName    string
	Relayed       bool
	Samples       int32
	Buckets       int32
	BucketMeanSum float64
	MinValue      float64
	MaxValue      float64
	IntervalSum   float64
}

// One metric's hourly aggregates from from_at to to_at per source with its identity, by local
// hour or (by_day) summed per local date, whose hour_start is then its first hour. Ordered by
// source, then time.
func (q *Queries) SourceSeriesAggregates(ctx context.Context, arg SourceSeriesAggregatesParams) ([]SourceSeriesAggregatesRow, error) {
	rows, err := q.db.Query(ctx, sourceSeriesAggregates,
		arg.UserID,
		arg.Metric,
		arg.FromAt,
		arg.ToAt,
		arg.ByDay,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SourceSeriesAggregatesRow
	for rows.Next() {
		var i SourceSeriesAggregatesRow
		if err := rows.Scan(
			&i.HourStart,
			&i.LocalDate,
			&i.ConnectionID,
			&i.DeviceID,
			&i.OriginID,
			&i.Provider,
			&i.DeviceType,
			&i.DeviceModel,
			&i.OriginKey,
			&i.OriginName,
			&i.Relayed,
			&i.Samples,
			&i.Buckets,
			&i.BucketMeanSum,
			&i.MinValue,
			&i.MaxValue,
			&i.IntervalSum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
