// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: labexport.sql

package dbq

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const exportAnalyteAliases = `-- name: ExportAnalyteAliases :many
SELECT id::bigint AS id, to_jsonb(t)::jsonb AS row FROM analyte_aliases t
WHERE user_id = $1 AND id > $2::bigint ORDER BY id LIMIT $3
`

type ExportAnalyteAliasesParams struct {
	UserID *uuid.UUID
	After  int64
	Lim    int32
}

type ExportAnalyteAliasesRow struct {
	ID  int64
	Row json.RawMessage
}

// Owner aliases only; seeded ones come with the migrations.
func (q *Queries) ExportAnalyteAliases(ctx context.Context, arg ExportAnalyteAliasesParams) ([]ExportAnalyteAliasesRow, error) {
	rows, err := q.db.Query(ctx, exportAnalyteAliases, arg.UserID, arg.After, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportAnalyteAliasesRow
	for rows.Next() {
		var i ExportAnalyteAliasesRow
		if err := rows.Scan(&i.ID, &i.Row); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportAnalytes = `-- name: ExportAnalytes :many

SELECT to_jsonb(t)::jsonb AS row FROM analytes t ORDER BY id
`

// Lab documents in the NDJSON export and importer (J12.6; internal/export/tables.go).
// Never exported: document_keys, the sealed PDF and filename, raw extractor responses.
func (q *Queries) ExportAnalytes(ctx context.Context) ([]json.RawMessage, error) {
	rows, err := q.db.Query(ctx, exportAnalytes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []json.RawMessage
	for rows.Next() {
		var row json.RawMessage
		if err := rows.Scan(&row); err != nil {
			return nil, err
		}
		items = append(items, row)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportDocuments = `-- name: ExportDocuments :many
SELECT id, (to_jsonb(t) - 'sha256' - 'blob_sha256' - 'filename_ciphertext')::jsonb AS row FROM documents t
WHERE user_id = $1 AND id > $2::uuid ORDER BY id LIMIT $3
`

type ExportDocumentsParams struct {
	UserID uuid.UUID
	After  uuid.UUID
	Lim    int32
}

type ExportDocumentsRow struct {
	ID  uuid.UUID
	Row json.RawMessage
}

func (q *Queries) ExportDocuments(ctx context.Context, arg ExportDocumentsParams) ([]ExportDocumentsRow, error) {
	rows, err := q.db.Query(ctx, exportDocuments, arg.UserID, arg.After, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportDocumentsRow
	for rows.Next() {
		var i ExportDocumentsRow
		if err := rows.Scan(&i.ID, &i.Row); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportExtractionRowEdits = `-- name: ExportExtractionRowEdits :many
SELECT t.id::bigint AS id, to_jsonb(t)::jsonb AS row FROM extraction_row_edits t
JOIN lab_extracted_rows r ON r.id = t.row_id
JOIN extraction_runs x ON x.id = r.run_id
WHERE x.user_id = $1 AND t.id > $2::bigint ORDER BY t.id LIMIT $3
`

type ExportExtractionRowEditsParams struct {
	UserID uuid.UUID
	After  int64
	Lim    int32
}

type ExportExtractionRowEditsRow struct {
	ID  int64
	Row json.RawMessage
}

func (q *Queries) ExportExtractionRowEdits(ctx context.Context, arg ExportExtractionRowEditsParams) ([]ExportExtractionRowEditsRow, error) {
	rows, err := q.db.Query(ctx, exportExtractionRowEdits, arg.UserID, arg.After, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportExtractionRowEditsRow
	for rows.Next() {
		var i ExportExtractionRowEditsRow
		if err := rows.Scan(&i.ID, &i.Row); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportExtractionRuns = `-- name: ExportExtractionRuns :many
SELECT id, (to_jsonb(t) - 'response_blob_sha256' - 'job_id')::jsonb AS row FROM extraction_runs t
WHERE user_id = $1 AND id > $2::uuid ORDER BY id LIMIT $3
`

type ExportExtractionRunsParams struct {
	UserID uuid.UUID
	After  uuid.UUID
	Lim    int32
}

type ExportExtractionRunsRow struct {
	ID  uuid.UUID
	Row json.RawMessage
}

func (q *Queries) ExportExtractionRuns(ctx context.Context, arg ExportExtractionRunsParams) ([]ExportExtractionRunsRow, error) {
	rows, err := q.db.Query(ctx, exportExtractionRuns, arg.UserID, arg.After, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportExtractionRunsRow
	for rows.Next() {
		var i ExportExtractionRunsRow
		if err := rows.Scan(&i.ID, &i.Row); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportLabExtractedRows = `-- name: ExportLabExtractedRows :many
SELECT t.id::bigint AS id, to_jsonb(t)::jsonb AS row FROM lab_extracted_rows t
JOIN extraction_runs x ON x.id = t.run_id
WHERE x.user_id = $1 AND t.id > $2::bigint ORDER BY t.id LIMIT $3
`

type ExportLabExtractedRowsParams struct {
	UserID uuid.UUID
	After  int64
	Lim    int32
}

type ExportLabExtractedRowsRow struct {
	ID  int64
	Row json.RawMessage
}

func (q *Queries) ExportLabExtractedRows(ctx context.Context, arg ExportLabExtractedRowsParams) ([]ExportLabExtractedRowsRow, error) {
	rows, err := q.db.Query(ctx, exportLabExtractedRows, arg.UserID, arg.After, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportLabExtractedRowsRow
	for rows.Next() {
		var i ExportLabExtractedRowsRow
		if err := rows.Scan(&i.ID, &i.Row); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportLabReports = `-- name: ExportLabReports :many
SELECT id, to_jsonb(t)::jsonb AS row FROM lab_reports t
WHERE user_id = $1 AND id > $2::uuid ORDER BY id LIMIT $3
`

type ExportLabReportsParams struct {
	UserID uuid.UUID
	After  uuid.UUID
	Lim    int32
}

type ExportLabReportsRow struct {
	ID  uuid.UUID
	Row json.RawMessage
}

func (q *Queries) ExportLabReports(ctx context.Context, arg ExportLabReportsParams) ([]ExportLabReportsRow, error) {
	rows, err := q.db.Query(ctx, exportLabReports, arg.UserID, arg.After, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportLabReportsRow
	for rows.Next() {
		var i ExportLabReportsRow
		if err := rows.Scan(&i.ID, &i.Row); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportLabResultRevisions = `-- name: ExportLabResultRevisions :many
SELECT t.id::bigint AS id, to_jsonb(t)::jsonb AS row FROM lab_result_revisions t
JOIN lab_results r ON r.id = t.result_id
WHERE r.user_id = $1 AND t.id > $2::bigint ORDER BY t.id LIMIT $3
`

type ExportLabResultRevisionsParams struct {
	UserID uuid.UUID
	After  int64
	Lim    int32
}

type ExportLabResultRevisionsRow struct {
	ID  int64
	Row json.RawMessage
}

func (q *Queries) ExportLabResultRevisions(ctx context.Context, arg ExportLabResultRevisionsParams) ([]ExportLabResultRevisionsRow, error) {
	rows, err := q.db.Query(ctx, exportLabResultRevisions, arg.UserID, arg.After, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportLabResultRevisionsRow
	for rows.Next() {
		var i ExportLabResultRevisionsRow
		if err := rows.Scan(&i.ID, &i.Row); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportLabResults = `-- name: ExportLabResults :many
SELECT id, to_jsonb(t)::jsonb AS row FROM lab_results t
WHERE user_id = $1 AND id > $2::uuid ORDER BY id LIMIT $3
`

type ExportLabResultsParams struct {
	UserID uuid.UUID
	After  uuid.UUID
	Lim    int32
}

type ExportLabResultsRow struct {
	ID  uuid.UUID
	Row json.RawMessage
}

func (q *Queries) ExportLabResults(ctx context.Context, arg ExportLabResultsParams) ([]ExportLabResultsRow, error) {
	rows, err := q.db.Query(ctx, exportLabResults, arg.UserID, arg.After, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportLabResultsRow
	for rows.Next() {
		var i ExportLabResultsRow
		if err := rows.Scan(&i.ID, &i.Row); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const importAnalyteAliases = `-- name: ImportAnalyteAliases :execrows
INSERT INTO analyte_aliases (analyte_id, label, label_key, user_id, created_by, created_at)
SELECT p.analyte_id, p.label, p.label_key, p.user_id, p.created_by, p.created_at
FROM jsonb_populate_recordset(NULL::analyte_aliases, $1::jsonb) p
ON CONFLICT DO NOTHING
`

func (q *Queries) ImportAnalyteAliases(ctx context.Context, batch json.RawMessage) (int64, error) {
	result, err := q.db.Exec(ctx, importAnalyteAliases, batch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const importDocuments = `-- name: ImportDocuments :execrows
INSERT INTO documents
SELECT (p).* FROM jsonb_populate_recordset(NULL::documents, $1::jsonb) p
ON CONFLICT DO NOTHING
`

// Rows arrive as tombstones (the importer patches them): the export holds no PDF or key.
func (q *Queries) ImportDocuments(ctx context.Context, batch json.RawMessage) (int64, error) {
	result, err := q.db.Exec(ctx, importDocuments, batch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const importLabReports = `-- name: ImportLabReports :execrows
INSERT INTO lab_reports
SELECT (p).* FROM jsonb_populate_recordset(NULL::lab_reports, $1::jsonb) p
ON CONFLICT DO NOTHING
`

func (q *Queries) ImportLabReports(ctx context.Context, batch json.RawMessage) (int64, error) {
	result, err := q.db.Exec(ctx, importLabReports, batch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const importLabResultRevisions = `-- name: ImportLabResultRevisions :execrows

INSERT INTO lab_result_revisions (result_id, revision, snapshot, reason, changed_by, changed_at)
SELECT p.result_id, p.revision, p.snapshot, p.reason, p.changed_by, p.changed_at
FROM jsonb_populate_recordset(NULL::lab_result_revisions, $1::jsonb) p
ON CONFLICT DO NOTHING
`

// Revisions and aliases get new identity ids: nothing references them, and their natural keys
// (result and revision; owner and label) make a repeated import skip them.
func (q *Queries) ImportLabResultRevisions(ctx context.Context, batch json.RawMessage) (int64, error) {
	result, err := q.db.Exec(ctx, importLabResultRevisions, batch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const importLabResults = `-- name: ImportLabResults :execrows
INSERT INTO lab_results
SELECT (p).* FROM jsonb_populate_recordset(NULL::lab_results, $1::jsonb) p
ON CONFLICT DO NOTHING
`

func (q *Queries) ImportLabResults(ctx context.Context, batch json.RawMessage) (int64, error) {
	result, err := q.db.Exec(ctx, importLabResults, batch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
