// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: localdate.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteTimezonePeriod = `-- name: DeleteTimezonePeriod :execrows
DELETE FROM timezone_periods WHERE id = $1 AND user_id = $2
`

type DeleteTimezonePeriodParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteTimezonePeriod(ctx context.Context, arg DeleteTimezonePeriodParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTimezonePeriod, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertTimezonePeriod = `-- name: InsertTimezonePeriod :exec
INSERT INTO timezone_periods (id, user_id, tz, valid_from) VALUES ($1, $2, $3, $4)
`

type InsertTimezonePeriodParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Tz        string
	ValidFrom time.Time
}

func (q *Queries) InsertTimezonePeriod(ctx context.Context, arg InsertTimezonePeriodParams) error {
	_, err := q.db.Exec(ctx, insertTimezonePeriod,
		arg.ID,
		arg.UserID,
		arg.Tz,
		arg.ValidFrom,
	)
	return err
}

const listEventsForLocalDate = `-- name: ListEventsForLocalDate :many
SELECT id, start_at AS at, local_date FROM health_events
WHERE user_id = $1
  AND tz_offset_min IS NULL AND superseded_at IS NULL AND deleted_at IS NULL
  AND start_at >= $2 AND start_at < $3
  AND (start_at, id) > ($4::timestamptz, $5::uuid)
ORDER BY start_at, id
LIMIT $6
`

type ListEventsForLocalDateParams struct {
	UserID  uuid.UUID
	FromAt  time.Time
	UntilAt time.Time
	AfterAt time.Time
	AfterID uuid.UUID
	Batch   int32
}

type ListEventsForLocalDateRow struct {
	ID        uuid.UUID
	At        time.Time
	LocalDate time.Time
}

func (q *Queries) ListEventsForLocalDate(ctx context.Context, arg ListEventsForLocalDateParams) ([]ListEventsForLocalDateRow, error) {
	rows, err := q.db.Query(ctx, listEventsForLocalDate,
		arg.UserID,
		arg.FromAt,
		arg.UntilAt,
		arg.AfterAt,
		arg.AfterID,
		arg.Batch,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsForLocalDateRow
	for rows.Next() {
		var i ListEventsForLocalDateRow
		if err := rows.Scan(&i.ID, &i.At, &i.LocalDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeasurementGroupsForLocalDate = `-- name: ListMeasurementGroupsForLocalDate :many
SELECT id, measured_at AS at, local_date FROM measurement_groups
WHERE user_id = $1
  AND tz_offset_min IS NULL AND superseded_at IS NULL AND deleted_at IS NULL
  AND measured_at >= $2 AND measured_at < $3
  AND (measured_at, id) > ($4::timestamptz, $5::bigint)
ORDER BY measured_at, id
LIMIT $6
`

type ListMeasurementGroupsForLocalDateParams struct {
	UserID  uuid.UUID
	FromAt  time.Time
	UntilAt time.Time
	AfterAt time.Time
	AfterID int64
	Batch   int32
}

type ListMeasurementGroupsForLocalDateRow struct {
	ID        int64
	At        time.Time
	LocalDate time.Time
}

func (q *Queries) ListMeasurementGroupsForLocalDate(ctx context.Context, arg ListMeasurementGroupsForLocalDateParams) ([]ListMeasurementGroupsForLocalDateRow, error) {
	rows, err := q.db.Query(ctx, listMeasurementGroupsForLocalDate,
		arg.UserID,
		arg.FromAt,
		arg.UntilAt,
		arg.AfterAt,
		arg.AfterID,
		arg.Batch,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMeasurementGroupsForLocalDateRow
	for rows.Next() {
		var i ListMeasurementGroupsForLocalDateRow
		if err := rows.Scan(&i.ID, &i.At, &i.LocalDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeasurementsForLocalDate = `-- name: ListMeasurementsForLocalDate :many

SELECT id, start_at AS at, local_date FROM measurements
WHERE user_id = $1 AND metric_id = $2
  AND tz_offset_min IS NULL AND superseded_at IS NULL AND deleted_at IS NULL
  AND start_at >= $3 AND start_at < $4
  AND (start_at, id) > ($5::timestamptz, $6::bigint)
ORDER BY start_at, id
LIMIT $7
`

type ListMeasurementsForLocalDateParams struct {
	UserID   uuid.UUID
	MetricID int16
	FromAt   time.Time
	UntilAt  time.Time
	AfterAt  time.Time
	AfterID  int64
	Batch    int32
}

type ListMeasurementsForLocalDateRow struct {
	ID        int64
	At        time.Time
	LocalDate time.Time
}

// Rows whose local date derives from timezone_periods (no stored offset), one keyset page at a time.
// Only active rows: superseded and deleted rows are history and keep the date they were written with.
func (q *Queries) ListMeasurementsForLocalDate(ctx context.Context, arg ListMeasurementsForLocalDateParams) ([]ListMeasurementsForLocalDateRow, error) {
	rows, err := q.db.Query(ctx, listMeasurementsForLocalDate,
		arg.UserID,
		arg.MetricID,
		arg.FromAt,
		arg.UntilAt,
		arg.AfterAt,
		arg.AfterID,
		arg.Batch,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMeasurementsForLocalDateRow
	for rows.Next() {
		var i ListMeasurementsForLocalDateRow
		if err := rows.Scan(&i.ID, &i.At, &i.LocalDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetricIDs = `-- name: ListMetricIDs :many
SELECT id FROM metric_catalog ORDER BY id
`

func (q *Queries) ListMetricIDs(ctx context.Context) ([]int16, error) {
	rows, err := q.db.Query(ctx, listMetricIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int16
	for rows.Next() {
		var id int16
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSleepSessionsForLocalDate = `-- name: ListSleepSessionsForLocalDate :many
SELECT id, end_at AS at, sleep_date AS local_date FROM sleep_sessions
WHERE user_id = $1
  AND tz_offset_min IS NULL AND superseded_at IS NULL AND deleted_at IS NULL
  AND end_at >= $2 AND end_at < $3
  AND (end_at, id) > ($4::timestamptz, $5::uuid)
ORDER BY end_at, id
LIMIT $6
`

type ListSleepSessionsForLocalDateParams struct {
	UserID  uuid.UUID
	FromAt  time.Time
	UntilAt time.Time
	AfterAt time.Time
	AfterID uuid.UUID
	Batch   int32
}

type ListSleepSessionsForLocalDateRow struct {
	ID        uuid.UUID
	At        time.Time
	LocalDate time.Time
}

// The local date of a sleep session is the date it ended (sleep_date).
func (q *Queries) ListSleepSessionsForLocalDate(ctx context.Context, arg ListSleepSessionsForLocalDateParams) ([]ListSleepSessionsForLocalDateRow, error) {
	rows, err := q.db.Query(ctx, listSleepSessionsForLocalDate,
		arg.UserID,
		arg.FromAt,
		arg.UntilAt,
		arg.AfterAt,
		arg.AfterID,
		arg.Batch,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSleepSessionsForLocalDateRow
	for rows.Next() {
		var i ListSleepSessionsForLocalDateRow
		if err := rows.Scan(&i.ID, &i.At, &i.LocalDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimezonePeriods = `-- name: ListTimezonePeriods :many

SELECT id, tz, valid_from FROM timezone_periods WHERE user_id = $1 ORDER BY valid_from
`

type ListTimezonePeriodsRow struct {
	ID        uuid.UUID
	Tz        string
	ValidFrom time.Time
}

// Timezone periods and local-date recomputation (J07.2).
func (q *Queries) ListTimezonePeriods(ctx context.Context, userID uuid.UUID) ([]ListTimezonePeriodsRow, error) {
	rows, err := q.db.Query(ctx, listTimezonePeriods, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTimezonePeriodsRow
	for rows.Next() {
		var i ListTimezonePeriodsRow
		if err := rows.Scan(&i.ID, &i.Tz, &i.ValidFrom); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutsForLocalDate = `-- name: ListWorkoutsForLocalDate :many
SELECT id, start_at AS at, local_date FROM workouts
WHERE user_id = $1
  AND tz_offset_min IS NULL AND superseded_at IS NULL AND deleted_at IS NULL
  AND start_at >= $2 AND start_at < $3
  AND (start_at, id) > ($4::timestamptz, $5::uuid)
ORDER BY start_at, id
LIMIT $6
`

type ListWorkoutsForLocalDateParams struct {
	UserID  uuid.UUID
	FromAt  time.Time
	UntilAt time.Time
	AfterAt time.Time
	AfterID uuid.UUID
	Batch   int32
}

type ListWorkoutsForLocalDateRow struct {
	ID        uuid.UUID
	At        time.Time
	LocalDate time.Time
}

func (q *Queries) ListWorkoutsForLocalDate(ctx context.Context, arg ListWorkoutsForLocalDateParams) ([]ListWorkoutsForLocalDateRow, error) {
	rows, err := q.db.Query(ctx, listWorkoutsForLocalDate,
		arg.UserID,
		arg.FromAt,
		arg.UntilAt,
		arg.AfterAt,
		arg.AfterID,
		arg.Batch,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkoutsForLocalDateRow
	for rows.Next() {
		var i ListWorkoutsForLocalDateRow
		if err := rows.Scan(&i.ID, &i.At, &i.LocalDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markLocalDatesDirty = `-- name: MarkLocalDatesDirty :exec
INSERT INTO resolution_dirty (user_id, metric_id, local_date)
SELECT $1, $2, d FROM unnest($3::date[]) AS d
ON CONFLICT DO NOTHING
`

type MarkLocalDatesDirtyParams struct {
	UserID   uuid.UUID
	MetricID int16
	Dates    []time.Time
}

func (q *Queries) MarkLocalDatesDirty(ctx context.Context, arg MarkLocalDatesDirtyParams) error {
	_, err := q.db.Exec(ctx, markLocalDatesDirty, arg.UserID, arg.MetricID, arg.Dates)
	return err
}

const setEventLocalDates = `-- name: SetEventLocalDates :exec
UPDATE health_events e SET local_date = v.d
FROM (SELECT unnest($1::uuid[]) AS id, unnest($2::date[]) AS d) AS v WHERE e.id = v.id
`

type SetEventLocalDatesParams struct {
	Ids   []uuid.UUID
	Dates []time.Time
}

func (q *Queries) SetEventLocalDates(ctx context.Context, arg SetEventLocalDatesParams) error {
	_, err := q.db.Exec(ctx, setEventLocalDates, arg.Ids, arg.Dates)
	return err
}

const setMeasurementGroupLocalDates = `-- name: SetMeasurementGroupLocalDates :exec
UPDATE measurement_groups g SET local_date = v.d
FROM (SELECT unnest($1::bigint[]) AS id, unnest($2::date[]) AS d) AS v WHERE g.id = v.id
`

type SetMeasurementGroupLocalDatesParams struct {
	Ids   []int64
	Dates []time.Time
}

func (q *Queries) SetMeasurementGroupLocalDates(ctx context.Context, arg SetMeasurementGroupLocalDatesParams) error {
	_, err := q.db.Exec(ctx, setMeasurementGroupLocalDates, arg.Ids, arg.Dates)
	return err
}

const setMeasurementLocalDates = `-- name: SetMeasurementLocalDates :exec
UPDATE measurements m SET local_date = v.d
FROM (SELECT unnest($1::bigint[]) AS id, unnest($2::date[]) AS d) AS v WHERE m.id = v.id
`

type SetMeasurementLocalDatesParams struct {
	Ids   []int64
	Dates []time.Time
}

func (q *Queries) SetMeasurementLocalDates(ctx context.Context, arg SetMeasurementLocalDatesParams) error {
	_, err := q.db.Exec(ctx, setMeasurementLocalDates, arg.Ids, arg.Dates)
	return err
}

const setSleepSessionDates = `-- name: SetSleepSessionDates :exec
UPDATE sleep_sessions s SET sleep_date = v.d
FROM (SELECT unnest($1::uuid[]) AS id, unnest($2::date[]) AS d) AS v WHERE s.id = v.id
`

type SetSleepSessionDatesParams struct {
	Ids   []uuid.UUID
	Dates []time.Time
}

func (q *Queries) SetSleepSessionDates(ctx context.Context, arg SetSleepSessionDatesParams) error {
	_, err := q.db.Exec(ctx, setSleepSessionDates, arg.Ids, arg.Dates)
	return err
}

const setWorkoutLocalDates = `-- name: SetWorkoutLocalDates :exec
UPDATE workouts w SET local_date = v.d
FROM (SELECT unnest($1::uuid[]) AS id, unnest($2::date[]) AS d) AS v WHERE w.id = v.id
`

type SetWorkoutLocalDatesParams struct {
	Ids   []uuid.UUID
	Dates []time.Time
}

func (q *Queries) SetWorkoutLocalDates(ctx context.Context, arg SetWorkoutLocalDatesParams) error {
	_, err := q.db.Exec(ctx, setWorkoutLocalDates, arg.Ids, arg.Dates)
	return err
}

const updateTimezonePeriod = `-- name: UpdateTimezonePeriod :execrows
UPDATE timezone_periods SET tz = $1, valid_from = $2 WHERE id = $3 AND user_id = $4
`

type UpdateTimezonePeriodParams struct {
	Tz        string
	ValidFrom time.Time
	ID        uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) UpdateTimezonePeriod(ctx context.Context, arg UpdateTimezonePeriodParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTimezonePeriod,
		arg.Tz,
		arg.ValidFrom,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
