// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// Personal access tokens `vmx_pat_<id>_<secret>`: the id is the lookup prefix, only the secret's SHA-256 is stored.
type ApiKey struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	SecretHash []byte
	Scopes     []string
	CreatedAt  time.Time
	LastUsedAt *time.Time
	ExpiresAt  *time.Time
	RevokedAt  *time.Time
}

// Append-only for the app role. Never holds secrets or health values.
type AuditEvent struct {
	ID         int64
	UserID     *uuid.UUID
	OccurredAt time.Time
	// Who acted: owner, an API key, a client, or system.
	Actor      string
	Action     string
	TargetType *string
	TargetID   *string
	Detail     json.RawMessage
}

type Backfill struct {
	ID           uuid.UUID
	ConnectionID uuid.UUID
	Stream       string
	RangeStart   time.Time
	RangeEnd     time.Time
	Status       string
	CreatedAt    time.Time
	FinishedAt   *time.Time
}

type BackfillUnit struct {
	BackfillID     uuid.UUID
	RangeStart     time.Time
	RangeEnd       time.Time
	Status         string
	Attempts       int32
	LastErrorClass *string
	UpdatedAt      time.Time
}

// Content-addressed files in the blob volume, keyed by the SHA-256 of the uncompressed content.
type Blob struct {
	Sha256      []byte
	SizeBytes   int64
	StoredBytes int64
	Compression string
	// Encryption key reference; null when the blob is not app-encrypted.
	KeyID     *string
	Refcount  int32
	CreatedAt time.Time
}

// Ingest tokens `vmx_cli_<id>_<secret>` scoped to one connection; only the secret's SHA-256 is stored.
type Client struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	ConnectionID uuid.UUID
	Kind         string
	Name         string
	TokenHash    []byte
	Metadata     json.RawMessage
	CreatedAt    time.Time
	LastSeenAt   *time.Time
	RevokedAt    *time.Time
}

type Connection struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	ProviderID int16
	// SHA-256 of the provider account id; null until the account is known.
	AccountKey          []byte
	Mode                string
	Status              string
	Config              json.RawMessage
	LastSuccessAt       *time.Time
	LastErrorClass      *string
	ConsecutiveFailures int32
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

// Provider tokens, sealed by internal/crypto (purpose credentials, AAD bound to the connection).
type Credential struct {
	ConnectionID    uuid.UUID
	Ciphertext      []byte
	KeyID           string
	AccessExpiresAt *time.Time
	// Incremented on every refresh; guards the single-flight refresh.
	Version   int32
	UpdatedAt time.Time
}

// Apps that recorded data inside a transport provider, e.g. HealthKit bundle ids.
type DataOrigin struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	ProviderID int16
	OriginKey  string
	Name       *string
	// Set when the origin relays another vendor's data (e.g. Garmin Connect into HealthKit).
	RelayedProviderID *int16
	IsNative          bool
	CreatedAt         time.Time
}

type Device struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	ProviderID  int16
	Fingerprint string
	// Rule selector, e.g. watch, phone, scale, bp_monitor, ring.
	DeviceType      *string
	Manufacturer    *string
	Model           *string
	HardwareVersion *string
	SoftwareVersion *string
	CreatedAt       time.Time
}

// Items already imported, so re-running an importer skips them.
type ImportItem struct {
	ID           int64
	ImportRunID  uuid.UUID
	Source       string
	ItemKey      string
	Checksum     []byte
	Status       string
	RawPayloadID *int64
	CreatedAt    time.Time
}

type ImportRun struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	ConnectionID *uuid.UUID
	// Importer, e.g. apple_health_export, ndjson.
	Source     string
	Status     string
	FileSha256 []byte
	Stats      json.RawMessage
	StartedAt  time.Time
	FinishedAt *time.Time
}

type IngestBatch struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	ConnectionID uuid.UUID
	// Pushing client; null for in-process syncs.
	ClientID        *uuid.UUID
	SourceKind      string
	MigrationSource *string
	IdempotencyKey  *string
	ReceivedAt      time.Time
}

type Job struct {
	ID           uuid.UUID
	Kind         string
	Status       string
	ConnectionID *uuid.UUID
	Exclusive    bool
	// Lower runs first.
	Priority  int16
	RunAt     time.Time
	DedupeKey *string
	// Job parameters. Never secrets, passwords or MFA codes.
	Payload        json.RawMessage
	Attempts       int32
	MaxAttempts    int32
	LeaseOwner     *string
	LeaseExpiresAt *time.Time
	CreatedAt      time.Time
	StartedAt      *time.Time
	FinishedAt     *time.Time
}

// One row per execution; outcome is null while running. Kept 90 days.
type JobRun struct {
	ID         int64
	JobID      uuid.UUID
	Attempt    int32
	StartedAt  time.Time
	FinishedAt *time.Time
	Outcome    *string
	ErrorClass *string
	// Sanitized: no secrets, bodies or health values.
	ErrorMessage *string
	Stats        json.RawMessage
}

// Editable defaults for data_origins.relayed_provider_id.
type KnownRelayOrigin struct {
	ID         int16
	ProviderID int16
	// LIKE pattern matched against data_origins.origin_key.
	OriginPattern     string
	RelayedProviderID int16
}

type Measurement struct {
	ID          int64
	UserID      uuid.UUID
	MetricID    int16
	Kind        string
	StartAt     time.Time
	EndAt       *time.Time
	TzOffsetMin *int16
	LocalDate   time.Time
	// In the metric's canonical unit.
	Value float64
	// Original value and unit, only when conversion changed the value.
	SourceValue  *float64
	SourceUnitID *int16
	ProviderID   int16
	ConnectionID uuid.UUID
	DeviceID     *uuid.UUID
	OriginID     *uuid.UUID
	GroupID      *int64
	ExternalID   *string
	// First 16 bytes of SHA-256 over the versioned key string (data-model.md#identifiers-and-dedupe-keys).
	DedupeKey []byte
	// Bitset defined in code: manual_entry, motion_context, implausible, relayed, migrated_without_raw, prorated_source.
	QualityFlags int32
	// Null only for rows migrated without raw (quality flag).
	RawPayloadID        *int64
	NormalizerVersionID int32
	IngestedAt          time.Time
	NormalizedAt        time.Time
	SupersededAt        *time.Time
	SupersededBy        *int64
	DeletedAt           *time.Time
	DeletedByRawID      *int64
}

// Readings taken together (blood pressure, weigh-ins); components are measurements with group_id.
type MeasurementGroup struct {
	ID                  int64
	UserID              uuid.UUID
	Kind                string
	MeasuredAt          time.Time
	TzOffsetMin         *int16
	LocalDate           time.Time
	Context             json.RawMessage
	ProviderID          int16
	ConnectionID        uuid.UUID
	DeviceID            *uuid.UUID
	OriginID            *uuid.UUID
	ExternalID          *string
	DedupeKey           []byte
	RawPayloadID        *int64
	NormalizerVersionID int32
	IngestedAt          time.Time
	NormalizedAt        time.Time
	SupersededAt        *time.Time
	SupersededBy        *int64
	DeletedAt           *time.Time
	DeletedByRawID      *int64
}

// Metrics owned by internal/catalog. Sources combine only when they share a code.
type MetricCatalog struct {
	ID     int16
	Code   string
	UnitID int16
}

type NormalizerVersion struct {
	ID           int32
	Name         string
	Version      int32
	GitSha       string
	RegisteredAt time.Time
}

// Data vendors and transports. Seeded by migrations; read-only for the app role.
type Provider struct {
	ID   int16
	Code string
	Name string
}

// Shared Retry-After state, so a restart keeps honouring provider rate limits.
type ProviderRateState struct {
	ProviderID   int16
	BlockedUntil time.Time
	UpdatedAt    time.Time
}

type RawPayload struct {
	ID           int64
	UserID       uuid.UUID
	ConnectionID uuid.UUID
	BatchID      uuid.UUID
	Stream       string
	ExternalKey  string
	Version      int32
	// Content hash and blob key: the verbatim payload is the blob.
	ContentSha256 []byte
	ContentType   string
	FetchedAt     time.Time
	StoredAt      time.Time
	// Sanitized request (endpoint, params); never tokens.
	RequestMeta      json.RawMessage
	ShapeFingerprint *string
	Status           string
}

// Days whose resolved values must be recomputed; written in the canonical writer's transaction.
type ResolutionDirty struct {
	UserID    uuid.UUID
	MetricID  int16
	LocalDate time.Time
	MarkedAt  time.Time
}

type Schedule struct {
	ID           uuid.UUID
	ConnectionID uuid.UUID
	Stream       string
	RunInterval  pgtype.Interval
	Lookback     pgtype.Interval
	NextRunAt    time.Time
	Enabled      bool
}

// Server-side UI sessions; the cookie holds the token, the row only its SHA-256.
type Session struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TokenHash  []byte
	CreatedAt  time.Time
	LastSeenAt time.Time
	ExpiresAt  time.Time
}

// Owner settings as key/value.
type Setting struct {
	UserID    uuid.UUID
	Key       string
	Value     json.RawMessage
	UpdatedAt time.Time
}

type SleepSession struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	StartAt     time.Time
	EndAt       time.Time
	TzOffsetMin *int16
	// Local date of waking up.
	SleepDate time.Time
	IsNap     bool
	HasStages bool
	// Whether the *_s totals are provider-reported or summed from stages.
	TotalsBasis         string
	AsleepS             *int32
	DeepS               *int32
	LightS              *int32
	RemS                *int32
	AwakeS              *int32
	LatencyS            *int32
	ProviderID          int16
	ConnectionID        uuid.UUID
	DeviceID            *uuid.UUID
	OriginID            *uuid.UUID
	ExternalID          *string
	DedupeKey           []byte
	RawPayloadID        *int64
	NormalizerVersionID int32
	IngestedAt          time.Time
	NormalizedAt        time.Time
	SupersededAt        *time.Time
	SupersededBy        *uuid.UUID
	DeletedAt           *time.Time
	DeletedByRawID      *int64
}

type SleepStage struct {
	ID        int64
	SessionID uuid.UUID
	Stage     string
	StartAt   time.Time
	EndAt     time.Time
}

type SyncCursor struct {
	ConnectionID  uuid.UUID
	Stream        string
	Cursor        []byte
	HighWatermark *time.Time
	Status        string
	// Why the stream is degraded, e.g. schema_drift.
	StatusReason *string
	UpdatedAt    time.Time
}

// IANA timezone in effect from valid_from until the next period; used for local dates when a source has no offset.
type TimezonePeriod struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Tz        string
	ValidFrom time.Time
	CreatedAt time.Time
}

type Unit struct {
	ID   int16
	Code string
}

// The owner account. No signup; created by `vitamux admin create-owner`.
type User struct {
	ID       uuid.UUID
	Username string
	// argon2id PHC string.
	PasswordHash string
	// Sealed TOTP secret (internal/crypto format, purpose credentials).
	TotpCiphertext []byte
	// Master key id of totp_ciphertext, for rotation.
	TotpKeyID *string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Workout struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	StartAt       time.Time
	EndAt         time.Time
	TzOffsetMin   *int16
	LocalDate     time.Time
	Sport         string
	ProviderSport *string
	DistanceM     *float64
	EnergyKcal    *float64
	AvgHrBpm      *float64
	MaxHrBpm      *float64
	// Original activity file (FIT, GPX), if any.
	FileBlobSha256      []byte
	ProviderID          int16
	ConnectionID        uuid.UUID
	DeviceID            *uuid.UUID
	OriginID            *uuid.UUID
	ExternalID          *string
	DedupeKey           []byte
	RawPayloadID        *int64
	NormalizerVersionID int32
	IngestedAt          time.Time
	NormalizedAt        time.Time
	SupersededAt        *time.Time
	SupersededBy        *uuid.UUID
	DeletedAt           *time.Time
	DeletedByRawID      *int64
}

type WorkoutSegment struct {
	WorkoutID uuid.UUID
	Seq       int32
	Kind      string
	StartAt   time.Time
	EndAt     *time.Time
	Data      json.RawMessage
}
