// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

// The rule version in effect per metric. No row: the built-in default applies, if there is one.
type ActiveRule struct {
	UserID      uuid.UUID
	Metric      string
	Version     int32
	ActivatedBy string
	ActivatedAt time.Time
}

// Lab analytes owned by internal/documents/analytes. No reference ranges: ranges come from the printed report.
type Analyte struct {
	ID   int16
	Code string
	Name string
	// Null when values are kept as printed only. Conversions are owned by code.
	CanonicalUnit *string
	// Only from a verified loinc.org lookup, never guessed.
	Loinc *string
}

// Printed labels mapped to analytes: seeded rows (user_id null, read-only by convention) and owner aliases, which take precedence.
type AnalyteAlias struct {
	ID        int64
	AnalyteID int16
	Label     string
	// analytes.LabelKey(label): lower case, punctuation runs collapsed to one space.
	LabelKey  string
	UserID    *uuid.UUID
	CreatedBy *string
	CreatedAt time.Time
}

// Personal access tokens `vmx_pat_<id>_<secret>`: the id is the lookup prefix, only the secret's SHA-256 is stored.
type ApiKey struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	SecretHash []byte
	Scopes     []string
	CreatedAt  time.Time
	LastUsedAt *time.Time
	ExpiresAt  *time.Time
	RevokedAt  *time.Time
}

// Append-only for the app role. Never holds secrets or health values.
type AuditEvent struct {
	ID         int64
	UserID     *uuid.UUID
	OccurredAt time.Time
	// Who acted: owner, an API key, a client, or system.
	Actor      string
	Action     string
	TargetType *string
	TargetID   *string
	Detail     json.RawMessage
}

type Backfill struct {
	ID           uuid.UUID
	ConnectionID uuid.UUID
	Stream       string
	RangeStart   time.Time
	RangeEnd     time.Time
	Status       string
	CreatedAt    time.Time
	FinishedAt   *time.Time
}

type BackfillUnit struct {
	BackfillID     uuid.UUID
	RangeStart     time.Time
	RangeEnd       time.Time
	Status         string
	Attempts       int32
	LastErrorClass *string
	UpdatedAt      time.Time
}

// Content-addressed files in the blob volume, keyed by the SHA-256 of the uncompressed content.
type Blob struct {
	Sha256      []byte
	SizeBytes   int64
	StoredBytes int64
	Compression string
	// Encryption key reference; null when the blob is not app-encrypted.
	KeyID     *string
	Refcount  int32
	CreatedAt time.Time
}

// Ingest tokens `vmx_cli_<id>_<secret>` scoped to one connection; only the secret's SHA-256 is stored.
type Client struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	ConnectionID uuid.UUID
	Kind         string
	Name         string
	TokenHash    []byte
	Metadata     json.RawMessage
	CreatedAt    time.Time
	LastSeenAt   *time.Time
	RevokedAt    *time.Time
	// Device anchor resets the owner requested: HealthKit type identifier (or * for every type) to the latest request time. The device applies those newer than the last it applied.
	AnchorResets json.RawMessage
}

type Connection struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	ProviderID int16
	// SHA-256 of the provider account id; null until the account is known.
	AccountKey          []byte
	Mode                string
	Status              string
	Config              json.RawMessage
	LastSuccessAt       *time.Time
	LastErrorClass      *string
	ConsecutiveFailures int32
	CreatedAt           time.Time
	UpdatedAt           time.Time
	// SHA-256 of the random token in the notification callback URL /webhooks/<provider>/<token>; null while not subscribed. The token itself is only sent to the provider.
	HookTokenHash []byte
	// Upstream package a sidecar connector wraps: {package, version, source_url}; null for in-process connectors.
	Upstream []byte
}

// Provider tokens, sealed by internal/crypto (purpose credentials, AAD bound to the connection).
type Credential struct {
	ConnectionID    uuid.UUID
	Ciphertext      []byte
	KeyID           string
	AccessExpiresAt *time.Time
	// Incremented on every refresh; guards the single-flight refresh.
	Version   int32
	UpdatedAt time.Time
}

// Apps that recorded data inside a transport provider, e.g. HealthKit bundle ids.
type DataOrigin struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	ProviderID int16
	OriginKey  string
	Name       *string
	// Set when the origin relays another vendor's data (e.g. Garmin Connect into HealthKit).
	RelayedProviderID *int16
	IsNative          bool
	CreatedAt         time.Time
}

type Device struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	ProviderID  int16
	Fingerprint string
	// Rule selector, e.g. watch, phone, scale, bp_monitor, ring.
	DeviceType      *string
	Manufacturer    *string
	Model           *string
	HardwareVersion *string
	SoftwareVersion *string
	CreatedAt       time.Time
	// The owner's label; null shows the model or fingerprint.
	Name *string
	// The owner set device_type; normalizers no longer change it.
	DeviceTypeByOwner bool
	// The device this one was merged into (same owner and provider, never itself merged). Records of this fingerprint are written to that device.
	MergedInto *uuid.UUID
}

// Uploaded lab PDFs. A deleted document stays as a tombstone (no hash, blob or filename) so kept lab results still name their source.
type Document struct {
	ID     uuid.UUID
	UserID uuid.UUID
	Status string
	// SHA-256 of the PDF; a re-upload of the same content links to the live document.
	Sha256 []byte
	// Blob holding the PDF sealed with the document key (internal/documents format), so its hash says nothing about the PDF.
	BlobSha256 []byte
	// Original filename sealed with the document key; null when none was given.
	FilenameCiphertext []byte
	SizeBytes          int64
	PageCount          int32
	UploadedAt         time.Time
	UploadedBy         string
	// uploaded_at + documents.retention_days at the time of the last policy change; the document_retention job deletes the original after it.
	RetentionUntil *time.Time
	DeletedAt      *time.Time
}

// Per-document AES-256-GCM data key, sealed with the master key (purpose documents, AAD document_keys:<document id>). Deleting the row crypto-shreds the document.
type DocumentKey struct {
	DocumentID uuid.UUID
	Ciphertext []byte
	// Master key id of ciphertext, for rotation.
	KeyID     string
	CreatedAt time.Time
}

// Export zips (blob_sha256 holds a blob reference); deleted with their blob after expires_at.
type Export struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	JobID      *uuid.UUID
	Format     string
	IncludeRaw bool
	CreatedAt  time.Time
	FinishedAt *time.Time
	ExpiresAt  *time.Time
	SizeBytes  *int64
	BlobSha256 []byte
	// SHA-256 of the current one-time download token; a new token replaces it.
	TokenHash      []byte
	TokenExpiresAt *time.Time
	TokenUsedAt    *time.Time
}

// Append-only review trail of each extracted row.
type ExtractionRowEdit struct {
	ID     int64
	RowID  int64
	Action string
	// {"field": {"from": old, "to": new}} for edits.
	Changes   json.RawMessage
	Actor     string
	CreatedAt time.Time
}

// One extraction attempt of a document. Re-extraction adds a run; runs can be compared. Deleted with the document original.
type ExtractionRun struct {
	ID         uuid.UUID
	DocumentID uuid.UUID
	UserID     uuid.UUID
	JobID      *uuid.UUID
	Status     string
	Provider   string
	Model      *string
	External   bool
	// {provider, model, acknowledged_at} the owner gave for an external provider.
	Consent           []byte
	SchemaVersion     string
	PromptVersion     string
	ProviderRequestID *string
	// Raw provider response, sealed with the document key before Put.
	ResponseBlobSha256 []byte
	// Document-level fields the extractor read (laboratory, dates).
	DocMeta    json.RawMessage
	Usage      json.RawMessage
	Warnings   []string
	ErrorClass *string
	CreatedBy  string
	CreatedAt  time.Time
	StartedAt  *time.Time
	FinishedAt *time.Time
}

// Typed events (alerts, results) with a level or value; codes are owned by internal/catalog (Events).
type HealthEvent struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Code        string
	StartAt     time.Time
	EndAt       *time.Time
	TzOffsetMin *int16
	LocalDate   time.Time
	Value       *float64
	// Provider level mapped to a code-owned word, e.g. initial_low; null when the event has none.
	Level *string
	// Source metadata kept as given, e.g. HealthKit thresholds.
	Context json.RawMessage
	// measurements.quality_flags bitset (manual_entry, relayed).
	QualityFlags        int32
	ProviderID          int16
	ConnectionID        uuid.UUID
	DeviceID            *uuid.UUID
	OriginID            *uuid.UUID
	ExternalID          *string
	DedupeKey           []byte
	RawPayloadID        *int64
	NormalizerVersionID int32
	IngestedAt          time.Time
	NormalizedAt        time.Time
	SupersededAt        *time.Time
	SupersededBy        *uuid.UUID
	DeletedAt           *time.Time
	DeletedByRawID      *int64
}

// First successful response per (client, Idempotency-Key), replayed for the same request; another request with the key is a conflict.
type IdempotencyKey struct {
	ClientID uuid.UUID
	Key      string
	// SHA-256 over the route and the decompressed request body.
	RequestSha256 []byte
	// Null only inside the claiming transaction, so never in a committed row.
	ResponseStatus *int16
	// Batch or blob receipt: ids, external keys and outcomes; never payload bodies.
	ResponseBody []byte
	CreatedAt    time.Time
}

// Items already imported, so re-running an importer skips them.
type ImportItem struct {
	ID           int64
	ImportRunID  uuid.UUID
	Source       string
	ItemKey      string
	Checksum     []byte
	Status       string
	RawPayloadID *int64
	CreatedAt    time.Time
}

type ImportRun struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	ConnectionID *uuid.UUID
	// Importer, e.g. apple_health_export, ndjson.
	Source     string
	Status     string
	FileSha256 []byte
	Stats      json.RawMessage
	StartedAt  time.Time
	FinishedAt *time.Time
}

type IngestBatch struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	ConnectionID uuid.UUID
	// Pushing client; null for in-process syncs.
	ClientID        *uuid.UUID
	SourceKind      string
	MigrationSource *string
	IdempotencyKey  *string
	ReceivedAt      time.Time
}

type Job struct {
	ID           uuid.UUID
	Kind         string
	Status       string
	ConnectionID *uuid.UUID
	Exclusive    bool
	// Lower runs first.
	Priority  int16
	RunAt     time.Time
	DedupeKey *string
	// Job parameters. Never secrets, passwords or MFA codes.
	Payload        json.RawMessage
	Attempts       int32
	MaxAttempts    int32
	LeaseOwner     *string
	LeaseExpiresAt *time.Time
	CreatedAt      time.Time
	StartedAt      *time.Time
	FinishedAt     *time.Time
	// Progress saved by the handler; a re-claimed job resumes from it. Never secrets or health values.
	Checkpoint []byte
}

// One row per execution; outcome is null while running. Kept 90 days.
type JobRun struct {
	ID         int64
	JobID      uuid.UUID
	Attempt    int32
	StartedAt  time.Time
	FinishedAt *time.Time
	Outcome    *string
	ErrorClass *string
	// Sanitized: no secrets, bodies or health values.
	ErrorMessage *string
	Stats        json.RawMessage
}

// Editable defaults for data_origins.relayed_provider_id.
type KnownRelayOrigin struct {
	ID         int16
	ProviderID int16
	// LIKE pattern matched against data_origins.origin_key.
	OriginPattern     string
	RelayedProviderID int16
}

// Extracted row schema v1 (lab-documents.md#extracted-row-schema-v1), verbatim from the extractor and edited in review.
type LabExtractedRow struct {
	ID                  int64
	RunID               uuid.UUID
	RowIndex            int32
	Page                *int32
	AnalyteLabel        string
	ValueText           *string
	ValueNumeric        *float64
	Comparator          *string
	UnitText            *string
	ReferenceRangeText  *string
	RefLow              *float64
	RefHigh             *float64
	AbnormalFlagPrinted *string
	SpecimenType        *string
	// ISO 8601 local time without offset, as extracted; the owner's timezone applies at confirmation.
	CollectedAt  *string
	ReportedAt   *string
	Laboratory   *string
	EvidenceText *string
	Bbox         []byte
	// Extractor hint only; never a reason to skip review.
	Confidence *float32
	Warnings   []string
	// From analyte_aliases; a suggestion until the owner confirms.
	SuggestedAnalyteID *int16
	ReviewStatus       string
	ReviewedAt         *time.Time
}

// A confirmed extraction. Extractor versions are copied from the run so they survive deleting the original.
type LabReport struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	DocumentID    uuid.UUID
	RunID         *uuid.UUID
	Laboratory    *string
	ReportedAt    *time.Time
	Provider      string
	Model         *string
	SchemaVersion string
	PromptVersion string
	ConfirmedBy   string
	ConfirmedAt   time.Time
}

// Confirmed lab values. The printed label, value text, unit, range and flag are always kept; no interpretation is stored.
type LabResult struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	ReportID    uuid.UUID
	SourceRowID *int64
	// Null for an unknown analyte, which stays confirmable with its printed values.
	AnalyteID     *int16
	OriginalLabel string
	ValueText     string
	ValueNumeric  *float64
	Comparator    *string
	// Printed unit; null means the owner confirmed the value as unitless.
	UnitText            *string
	ReferenceRangeText  *string
	RefLow              *float64
	RefHigh             *float64
	AbnormalFlagPrinted *string
	SpecimenType        *string
	// Only when the analyte has a conversion for unit_text (internal/documents/analytes); never computed otherwise.
	CanonicalValue *float64
	CanonicalUnit  *string
	// Factor and offset applied (canonical = value * factor + offset), so conventions such as insulin µIU/mL stay traceable.
	ConversionFactor *float64
	ConversionOffset *float64
	CatalogVersion   *int32
	CollectedAt      *time.Time
	// Collection date in the owner's timezone.
	CollectedDate time.Time
	Page          *int32
	EvidenceText  *string
	Revision      int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// Append-only: the values of lab_results revision N before an edit made it N + 1.
type LabResultRevision struct {
	ID        int64
	ResultID  uuid.UUID
	Revision  int32
	Snapshot  json.RawMessage
	Reason    *string
	ChangedBy string
	ChangedAt time.Time
}

// Owner corrections scoped to (metric, window kind, window key). Never delete: a revoke sets revoked_at and the row stays as history.
type ManualOverride struct {
	ID     uuid.UUID
	UserID uuid.UUID
	// Rule metric: catalogue code or rule family (sleep, blood_pressure), so no foreign key to metric_catalog.
	Metric     string
	WindowKind string
	// resolve.Window.Key: date for local_day and local_night, UTC start for bucket, hour and sleep_episode, as_of for latest, g:<id> or m:<id> for reading.
	WindowKey string
	// Local date the window belongs to; the resolution_dirty mark written with the override.
	LocalDate time.Time
	Action    string
	// exclude_input: measurements.id. No foreign key; a correction replaces the row, and the override is then reported as ignored.
	InputID *int64
	// force_source: the rule group id to use for the window.
	SourceGroup *string
	// set_value: the window value in the metric's canonical unit (unit).
	Value *float64
	Unit  *string
	// set_value: why; required.
	Note *string
	// Audit actor: owner, api_key:<id> or system.
	CreatedBy string
	CreatedAt time.Time
	RevokedAt *time.Time
	RevokedBy *string
}

type Measurement struct {
	ID          int64
	UserID      uuid.UUID
	MetricID    int16
	Kind        string
	StartAt     time.Time
	EndAt       *time.Time
	TzOffsetMin *int16
	LocalDate   time.Time
	// In the metric's canonical unit.
	Value float64
	// Original value and unit, only when conversion changed the value.
	SourceValue  *float64
	SourceUnitID *int16
	ProviderID   int16
	ConnectionID uuid.UUID
	DeviceID     *uuid.UUID
	OriginID     *uuid.UUID
	GroupID      *int64
	ExternalID   *string
	// First 16 bytes of SHA-256 over the versioned key string (data-model.md#identifiers-and-dedupe-keys).
	DedupeKey []byte
	// Bitset defined in code: manual_entry, motion_context, implausible, relayed, migrated_without_raw, prorated_source.
	QualityFlags int32
	// Null only for rows migrated without raw (quality flag).
	RawPayloadID        *int64
	NormalizerVersionID int32
	IngestedAt          time.Time
	NormalizedAt        time.Time
	SupersededAt        *time.Time
	SupersededBy        *int64
	DeletedAt           *time.Time
	DeletedByRawID      *int64
}

// Readings taken together (blood pressure, weigh-ins); components are measurements with group_id.
type MeasurementGroup struct {
	ID                  int64
	UserID              uuid.UUID
	Kind                string
	MeasuredAt          time.Time
	TzOffsetMin         *int16
	LocalDate           time.Time
	Context             json.RawMessage
	ProviderID          int16
	ConnectionID        uuid.UUID
	DeviceID            *uuid.UUID
	OriginID            *uuid.UUID
	ExternalID          *string
	DedupeKey           []byte
	RawPayloadID        *int64
	NormalizerVersionID int32
	IngestedAt          time.Time
	NormalizedAt        time.Time
	SupersededAt        *time.Time
	SupersededBy        *int64
	DeletedAt           *time.Time
	DeletedByRawID      *int64
}

// Metrics owned by internal/catalog. Sources combine only when they share a code.
type MetricCatalog struct {
	ID     int16
	Code   string
	UnitID int16
}

type NormalizerVersion struct {
	ID           int32
	Name         string
	Version      int32
	GitSha       string
	RegisteredAt time.Time
}

// One row per pending authorization step; the callback or the next continue deletes it (single use). Logging out deletes it with the session.
type OauthState struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	SessionID  uuid.UUID
	ProviderID int16
	// Connection being reauthorized; null for a new connection or a reconnect recognised by account.
	ConnectionID *uuid.UUID
	ExpiresAt    time.Time
	CreatedAt    time.Time
	// Opaque connector continuation (e.g. a PKCE verifier or a login session), sealed by internal/crypto (purpose credentials, AAD auth-session:<id>). Never sent to the browser; rows live minutes, so key rotation skips them.
	Session []byte
}

// Short-lived, single-use codes a device exchanges for a client token at POST /api/ingest/v1/devices/pair. Only the code's SHA-256 is stored.
type PairingCode struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	CodeHash  []byte
	CreatedAt time.Time
	ExpiresAt time.Time
	UsedAt    *time.Time
}

// Data vendors and transports. Seeded by migrations; read-only for the app role.
type Provider struct {
	ID   int16
	Code string
	Name string
}

// The owner's own OAuth application per provider, entered in the panel. Environment values (e.g. VITAMUX_WITHINGS_CLIENT_ID and _SECRET) win over the row.
type ProviderAppCredential struct {
	Provider string
	ClientID string
	// Client secret, sealed (purpose credentials, AAD provider_app:<provider>). Write-only: never returned by the API.
	Ciphertext []byte
	KeyID      string
	UpdatedAt  time.Time
	UpdatedBy  *uuid.UUID
}

// Shared Retry-After state, so a restart keeps honouring provider rate limits.
type ProviderRateState struct {
	ProviderID   int16
	BlockedUntil time.Time
	UpdatedAt    time.Time
}

type RawPayload struct {
	ID           int64
	UserID       uuid.UUID
	ConnectionID uuid.UUID
	BatchID      uuid.UUID
	Stream       string
	ExternalKey  string
	Version      int32
	// Content hash and blob key: the verbatim payload is the blob.
	ContentSha256 []byte
	ContentType   string
	FetchedAt     time.Time
	StoredAt      time.Time
	// Sanitized request (endpoint, params); never tokens.
	RequestMeta      json.RawMessage
	ShapeFingerprint *string
	Status           string
	// Previous version of the same (connection, stream, external_key); null for version 1, and for a later version whose predecessor prune_raw deleted.
	SupersedesID *int64
	// Normalizer version of the last normalization attempt, failed ones included; null until one ran.
	NormalizerVersionID *int32
	// When the last attempt finished.
	NormalizedAt *time.Time
	// Short code and reason for normalize_failed (no_normalizer, normalizer_error, normalizer_panic, invalid_output) or a skip (superseded_raw). Never payload content.
	StatusDetail *string
	// Non-fatal findings of the last attempt: [{code, detail}]. Never health values.
	Warnings json.RawMessage
}

// Single-use TOTP recovery codes; only the SHA-256 of each 80-bit code is stored.
type RecoveryCode struct {
	UserID    uuid.UUID
	CodeHash  []byte
	CreatedAt time.Time
	UsedAt    *time.Time
}

// Days whose resolved values must be recomputed; written in the canonical writer's transaction.
type ResolutionDirty struct {
	UserID    uuid.UUID
	MetricID  int16
	LocalDate time.Time
	MarkedAt  time.Time
}

// Immutable rule versions; an edit inserts version + 1. Insert-only for the app role.
type ResolutionRule struct {
	ID     uuid.UUID
	UserID uuid.UUID
	// Catalogue code or rule family (sleep, blood_pressure), so no foreign key to metric_catalog.
	Metric  string
	Version int32
	// Rule JSON, schemas/resolution-rule.v1.json; validated by internal/resolve before insert.
	Spec json.RawMessage
	// Built-in (builtin:<metric>:<n>) or default rule (default:<metric>:<hash>) this version copied; set on the copy only.
	BasedOn *string
	Note    *string
	// Audit actor: owner, api_key:<id> or system.
	CreatedBy string
	CreatedAt time.Time
}

// The results of one local date's windows of a metric under one rule version and set of overrides. Never authoritative.
type ResolvedCache struct {
	UserID     uuid.UUID
	Metric     string
	WindowKind string
	LocalDate  time.Time
	RuleRef    string
	// Hash of the active overrides of the date and its neighbours; empty without any.
	OverridesFp string
	Results     json.RawMessage
	// Catalogue codes and rule metrics the results read (followed leaders, derived source codes, sleep, wear, "workouts"); a change to any of them inside dep_from..dep_to deletes the row.
	Deps    []string
	DepFrom time.Time
	DepTo   time.Time
	// When every window of the date had closed; a request whose now is earlier recomputes.
	CompleteAt time.Time
	ComputedAt time.Time
}

type Schedule struct {
	ID           uuid.UUID
	ConnectionID uuid.UUID
	Stream       string
	RunInterval  time.Duration
	Lookback     time.Duration
	NextRunAt    time.Time
	Enabled      bool
	// incremental follows the cursor; correction re-fetches the lookback window ending at each slot.
	Mode string
}

// Server-side UI sessions; the cookie holds the token, the row only its SHA-256.
type Session struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TokenHash  []byte
	CreatedAt  time.Time
	LastSeenAt time.Time
	ExpiresAt  time.Time
}

// Owner settings as key/value.
type Setting struct {
	UserID    uuid.UUID
	Key       string
	Value     json.RawMessage
	UpdatedAt time.Time
}

// Remote sidecar connectors added in the panel (name = provider code); those of VITAMUX_SIDECARS are not stored.
type Sidecar struct {
	Name string
	Url  string
	// Shared bearer secret generated by Vitamux and shown once, sealed (purpose credentials, AAD sidecar:<name>).
	Ciphertext []byte
	KeyID      string
	CreatedAt  time.Time
	CreatedBy  *uuid.UUID
}

type SleepSession struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	StartAt     time.Time
	EndAt       time.Time
	TzOffsetMin *int16
	// Local date of waking up.
	SleepDate time.Time
	IsNap     bool
	HasStages bool
	// Whether the *_s totals are provider-reported or summed from stages.
	TotalsBasis         string
	AsleepS             *int32
	DeepS               *int32
	LightS              *int32
	RemS                *int32
	AwakeS              *int32
	LatencyS            *int32
	ProviderID          int16
	ConnectionID        uuid.UUID
	DeviceID            *uuid.UUID
	OriginID            *uuid.UUID
	ExternalID          *string
	DedupeKey           []byte
	RawPayloadID        *int64
	NormalizerVersionID int32
	IngestedAt          time.Time
	NormalizedAt        time.Time
	SupersededAt        *time.Time
	SupersededBy        *uuid.UUID
	DeletedAt           *time.Time
	DeletedByRawID      *int64
}

type SleepStage struct {
	ID        int64
	SessionID uuid.UUID
	Stage     string
	StartAt   time.Time
	EndAt     time.Time
}

// Per source and local hour of the owner's timeline: active sample and interval rows (daily values excluded). Rebuilt from resolution_dirty by the rebuild_aggregates job.
type SourceHourlyAggregate struct {
	UserID   uuid.UUID
	MetricID int16
	// connection_id/device_id/origin_id, with - for a missing device or origin.
	SourceKey    string
	HourStart    time.Time
	LocalDate    time.Time
	ConnectionID uuid.UUID
	DeviceID     *uuid.UUID
	OriginID     *uuid.UUID
	Samples      int32
	// UTC-aligned 5-minute buckets holding a sample or part of an interval; bucket_mean_sum adds the sample mean of each.
	Buckets       int16
	BucketMeanSum float64
	MinValue      float64
	MaxValue      float64
	// Interval values pro-rated linearly to the hour (additive metrics).
	IntervalSum float64
	FirstAt     time.Time
	LastAt      time.Time
}

type SyncCursor struct {
	ConnectionID  uuid.UUID
	Stream        string
	Cursor        []byte
	HighWatermark *time.Time
	Status        string
	// Why the stream is degraded, e.g. schema_drift.
	StatusReason *string
	UpdatedAt    time.Time
}

// IANA timezone in effect from valid_from until the next period; used for local dates when a source has no offset.
type TimezonePeriod struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Tz        string
	ValidFrom time.Time
	CreatedAt time.Time
}

type Unit struct {
	ID   int16
	Code string
}

// The owner account. No signup; created by `vitamux admin create-owner`.
type User struct {
	ID       uuid.UUID
	Username string
	// argon2id PHC string.
	PasswordHash string
	// Sealed TOTP secret (internal/crypto format, purpose credentials).
	TotpCiphertext []byte
	// Master key id of totp_ciphertext, for rotation.
	TotpKeyID *string
	CreatedAt time.Time
	UpdatedAt time.Time
	// Set when enrolment is confirmed; a sealed secret without it is a pending enrolment.
	TotpEnabledAt *time.Time
	// Last accepted TOTP time step; a code is accepted only for a later step (no replay).
	TotpLastStep *int64
}

type Workout struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	StartAt       time.Time
	EndAt         time.Time
	TzOffsetMin   *int16
	LocalDate     time.Time
	Sport         string
	ProviderSport *string
	DistanceM     *float64
	EnergyKcal    *float64
	AvgHrBpm      *float64
	MaxHrBpm      *float64
	// Original activity file (FIT, GPX), if any.
	FileBlobSha256      []byte
	ProviderID          int16
	ConnectionID        uuid.UUID
	DeviceID            *uuid.UUID
	OriginID            *uuid.UUID
	ExternalID          *string
	DedupeKey           []byte
	RawPayloadID        *int64
	NormalizerVersionID int32
	IngestedAt          time.Time
	NormalizedAt        time.Time
	SupersededAt        *time.Time
	SupersededBy        *uuid.UUID
	DeletedAt           *time.Time
	DeletedByRawID      *int64
}

type WorkoutSegment struct {
	WorkoutID uuid.UUID
	Seq       int32
	Kind      string
	StartAt   time.Time
	EndAt     *time.Time
	Data      json.RawMessage
}
