// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: normalize_job.sql

package dbq

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const listBatchPendingRaw = `-- name: ListBatchPendingRaw :many
SELECT id FROM raw_payloads WHERE batch_id = $1 AND status = 'stored' ORDER BY id
`

func (q *Queries) ListBatchPendingRaw(ctx context.Context, batchID uuid.UUID) ([]int64, error) {
	rows, err := q.db.Query(ctx, listBatchPendingRaw, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReprocessCandidates = `-- name: ListReprocessCandidates :many
SELECT r.id, r.stream, r.shape_fingerprint, r.normalizer_version_id
FROM raw_payloads r
WHERE r.id > $1 AND r.status <> 'quarantined'
  AND ($2::text = '' OR r.stream = $2)
  AND ($3::timestamptz IS NULL OR r.fetched_at >= $3)
  AND ($4::timestamptz IS NULL OR r.fetched_at < $4)
  AND NOT EXISTS (SELECT 1 FROM raw_payloads n WHERE n.supersedes_id = r.id)
ORDER BY r.id
LIMIT $5
`

type ListReprocessCandidatesParams struct {
	After   int64
	Stream  string
	Since   *time.Time
	Until   *time.Time
	MaxRows int32
}

type ListReprocessCandidatesRow struct {
	ID                  int64
	Stream              string
	ShapeFingerprint    *string
	NormalizerVersionID *int32
}

// Newest raw version of each record only: an older version's output was superseded on purpose.
func (q *Queries) ListReprocessCandidates(ctx context.Context, arg ListReprocessCandidatesParams) ([]ListReprocessCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listReprocessCandidates,
		arg.After,
		arg.Stream,
		arg.Since,
		arg.Until,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReprocessCandidatesRow
	for rows.Next() {
		var i ListReprocessCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Stream,
			&i.ShapeFingerprint,
			&i.NormalizerVersionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRawForNormalize = `-- name: LockRawForNormalize :one

SELECT r.id, r.connection_id, r.stream, r.external_key, r.content_type, r.fetched_at, r.request_meta,
       r.content_sha256, r.shape_fingerprint, r.status, r.normalizer_version_id, p.code AS provider,
       EXISTS (SELECT 1 FROM raw_payloads n WHERE n.supersedes_id = r.id) AS superseded
FROM raw_payloads r
JOIN connections c ON c.id = r.connection_id
JOIN providers p ON p.id = c.provider_id
WHERE r.id = $1
FOR UPDATE OF r
`

type LockRawForNormalizeRow struct {
	ID                  int64
	ConnectionID        uuid.UUID
	Stream              string
	ExternalKey         string
	ContentType         string
	FetchedAt           time.Time
	RequestMeta         json.RawMessage
	ContentSha256       []byte
	ShapeFingerprint    *string
	Status              string
	NormalizerVersionID *int32
	Provider            string
	Superseded          bool
}

// Normalization jobs (J07.5): batch normalize and reprocess.
// Locks the raw row so two workers never normalize one payload at once. superseded: a newer raw
// version of the same record exists, so this one must not write canonical rows.
func (q *Queries) LockRawForNormalize(ctx context.Context, id int64) (LockRawForNormalizeRow, error) {
	row := q.db.QueryRow(ctx, lockRawForNormalize, id)
	var i LockRawForNormalizeRow
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.Stream,
		&i.ExternalKey,
		&i.ContentType,
		&i.FetchedAt,
		&i.RequestMeta,
		&i.ContentSha256,
		&i.ShapeFingerprint,
		&i.Status,
		&i.NormalizerVersionID,
		&i.Provider,
		&i.Superseded,
	)
	return i, err
}

const setRawNormalizeResult = `-- name: SetRawNormalizeResult :exec
UPDATE raw_payloads
SET normalizer_version_id = $1, normalized_at = now(),
    status_detail = $2, warnings = $3
WHERE id = $4
`

type SetRawNormalizeResultParams struct {
	NormalizerVersionID *int32
	StatusDetail        *string
	Warnings            json.RawMessage
	ID                  int64
}

// Records the outcome next to the status change made with ingest.SetStatus.
func (q *Queries) SetRawNormalizeResult(ctx context.Context, arg SetRawNormalizeResultParams) error {
	_, err := q.db.Exec(ctx, setRawNormalizeResult,
		arg.NormalizerVersionID,
		arg.StatusDetail,
		arg.Warnings,
		arg.ID,
	)
	return err
}
