// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeOAuthState = `-- name: ConsumeOAuthState :one
DELETE FROM oauth_states o
USING providers p, sessions s
WHERE o.id = $1 AND p.id = o.provider_id AND p.code = $2 AND o.expires_at > now()
  AND s.id = o.session_id AND s.expires_at > now()
RETURNING o.user_id, o.session_id, o.connection_id, o.session, o.return_to
`

type ConsumeOAuthStateParams struct {
	ID       uuid.UUID
	Provider string
}

type ConsumeOAuthStateRow struct {
	UserID       uuid.UUID
	SessionID    uuid.UUID
	ConnectionID *uuid.UUID
	Session      []byte
	ReturnTo     string
}

// Single use: the row is gone after the first callback or continue, whatever happens next. A
// state of an ended session or another provider is refused.
func (q *Queries) ConsumeOAuthState(ctx context.Context, arg ConsumeOAuthStateParams) (ConsumeOAuthStateRow, error) {
	row := q.db.QueryRow(ctx, consumeOAuthState, arg.ID, arg.Provider)
	var i ConsumeOAuthStateRow
	err := row.Scan(
		&i.UserID,
		&i.SessionID,
		&i.ConnectionID,
		&i.Session,
		&i.ReturnTo,
	)
	return i, err
}

const deleteCredentials = `-- name: DeleteCredentials :exec
DELETE FROM credentials WHERE connection_id = $1
`

func (q *Queries) DeleteCredentials(ctx context.Context, connectionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCredentials, connectionID)
	return err
}

const deleteExpiredOAuthStates = `-- name: DeleteExpiredOAuthStates :exec
DELETE FROM oauth_states WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredOAuthStates(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredOAuthStates)
	return err
}

const disableConnection = `-- name: DisableConnection :execrows
UPDATE connections SET status = 'disabled', updated_at = now()
WHERE id = $1 AND user_id = $2
`

type DisableConnectionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DisableConnection(ctx context.Context, arg DisableConnectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, disableConnection, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getConnectionAccount = `-- name: GetConnectionAccount :one
SELECT c.account_key FROM connections c JOIN providers p ON p.id = c.provider_id
WHERE c.id = $1 AND c.user_id = $2 AND p.code = $3
`

type GetConnectionAccountParams struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	Provider string
}

func (q *Queries) GetConnectionAccount(ctx context.Context, arg GetConnectionAccountParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getConnectionAccount, arg.ID, arg.UserID, arg.Provider)
	var account_key []byte
	err := row.Scan(&account_key)
	return account_key, err
}

const insertOAuthState = `-- name: InsertOAuthState :exec

INSERT INTO oauth_states (id, user_id, session_id, provider_id, connection_id, expires_at, session, return_to, ticket_hash, start_url, binding)
SELECT $1, $2, $3, p.id, $4, $5, $6, $7,
  $8, $9, $10
FROM providers p WHERE p.code = $11
`

type InsertOAuthStateParams struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	SessionID    uuid.UUID
	ConnectionID *uuid.UUID
	ExpiresAt    time.Time
	Session      []byte
	ReturnTo     string
	TicketHash   []byte
	StartUrl     *string
	Binding      []byte
	Provider     string
}

// OAuth connection flow (J08.2); see docs/architecture/connectors.md#oauth-connection-flow.
func (q *Queries) InsertOAuthState(ctx context.Context, arg InsertOAuthStateParams) error {
	_, err := q.db.Exec(ctx, insertOAuthState,
		arg.ID,
		arg.UserID,
		arg.SessionID,
		arg.ConnectionID,
		arg.ExpiresAt,
		arg.Session,
		arg.ReturnTo,
		arg.TicketHash,
		arg.StartUrl,
		arg.Binding,
		arg.Provider,
	)
	return err
}

const reauthorizeConnection = `-- name: ReauthorizeConnection :exec
UPDATE connections
SET account_key = coalesce(account_key, $1), status = 'active', last_error_class = NULL,
    consecutive_failures = 0, upstream = coalesce($2, upstream), updated_at = now()
WHERE id = $3
`

type ReauthorizeConnectionParams struct {
	AccountKey []byte
	Upstream   []byte
	ID         uuid.UUID
}

func (q *Queries) ReauthorizeConnection(ctx context.Context, arg ReauthorizeConnectionParams) error {
	_, err := q.db.Exec(ctx, reauthorizeConnection, arg.AccountKey, arg.Upstream, arg.ID)
	return err
}

const upsertOAuthConnection = `-- name: UpsertOAuthConnection :one
INSERT INTO connections (id, user_id, provider_id, account_key, mode, status, upstream)
SELECT $1, $2, p.id, $3, $4, $5, $6 FROM providers p WHERE p.code = $7
ON CONFLICT (user_id, provider_id, account_key) DO UPDATE
SET status = 'active', last_error_class = NULL, consecutive_failures = 0,
    upstream = coalesce(EXCLUDED.upstream, connections.upstream), updated_at = now()
RETURNING id, (xmax = 0) AS created
`

type UpsertOAuthConnectionParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	AccountKey []byte
	Mode       string
	Status     string
	Upstream   []byte
	Provider   string
}

type UpsertOAuthConnectionRow struct {
	ID      uuid.UUID
	Created bool
}

// Reconnecting the same provider account reuses its connection (UNIQUE user, provider, account_key)
// and makes it active; @status applies to a new connection only.
func (q *Queries) UpsertOAuthConnection(ctx context.Context, arg UpsertOAuthConnectionParams) (UpsertOAuthConnectionRow, error) {
	row := q.db.QueryRow(ctx, upsertOAuthConnection,
		arg.ID,
		arg.UserID,
		arg.AccountKey,
		arg.Mode,
		arg.Status,
		arg.Upstream,
		arg.Provider,
	)
	var i UpsertOAuthConnectionRow
	err := row.Scan(&i.ID, &i.Created)
	return i, err
}

const useOAuthTicket = `-- name: UseOAuthTicket :one
UPDATE oauth_states o SET ticket_hash = NULL
FROM providers p, sessions s
WHERE o.ticket_hash = $1 AND p.id = o.provider_id AND p.code = $2
  AND o.created_at > $3 AND o.expires_at > now()
  AND s.id = o.session_id AND s.expires_at > now()
RETURNING o.id, o.start_url::text AS start_url, o.binding::bytea AS binding
`

type UseOAuthTicketParams struct {
	TicketHash  []byte
	Provider    string
	IssuedAfter time.Time
}

type UseOAuthTicketRow struct {
	ID       uuid.UUID
	StartUrl string
	Binding  []byte
}

// Single use: the start route clears the ticket; the state row stays for the callback. A
// ticket issued before @issued_after, of another provider or of an ended session is refused.
func (q *Queries) UseOAuthTicket(ctx context.Context, arg UseOAuthTicketParams) (UseOAuthTicketRow, error) {
	row := q.db.QueryRow(ctx, useOAuthTicket, arg.TicketHash, arg.Provider, arg.IssuedAfter)
	var i UseOAuthTicketRow
	err := row.Scan(&i.ID, &i.StartUrl, &i.Binding)
	return i, err
}
