// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeOAuthState = `-- name: ConsumeOAuthState :one
DELETE FROM oauth_states o
USING providers p, sessions s
WHERE o.id = $1 AND p.id = o.provider_id AND p.code = $2 AND o.expires_at > now()
  AND s.id = o.session_id AND s.expires_at > now()
RETURNING o.user_id, o.connection_id
`

type ConsumeOAuthStateParams struct {
	ID       uuid.UUID
	Provider string
}

type ConsumeOAuthStateRow struct {
	UserID       uuid.UUID
	ConnectionID *uuid.UUID
}

// Single use: the row is gone after the first callback, whatever happens next. A state of an
// ended session or another provider is refused.
func (q *Queries) ConsumeOAuthState(ctx context.Context, arg ConsumeOAuthStateParams) (ConsumeOAuthStateRow, error) {
	row := q.db.QueryRow(ctx, consumeOAuthState, arg.ID, arg.Provider)
	var i ConsumeOAuthStateRow
	err := row.Scan(&i.UserID, &i.ConnectionID)
	return i, err
}

const deleteCredentials = `-- name: DeleteCredentials :exec
DELETE FROM credentials WHERE connection_id = $1
`

func (q *Queries) DeleteCredentials(ctx context.Context, connectionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCredentials, connectionID)
	return err
}

const deleteExpiredOAuthStates = `-- name: DeleteExpiredOAuthStates :exec
DELETE FROM oauth_states WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredOAuthStates(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredOAuthStates)
	return err
}

const disableConnection = `-- name: DisableConnection :execrows
UPDATE connections SET status = 'disabled', updated_at = now()
WHERE id = $1 AND user_id = $2
`

type DisableConnectionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DisableConnection(ctx context.Context, arg DisableConnectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, disableConnection, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getConnectionAccount = `-- name: GetConnectionAccount :one
SELECT c.account_key FROM connections c JOIN providers p ON p.id = c.provider_id
WHERE c.id = $1 AND c.user_id = $2 AND p.code = $3
`

type GetConnectionAccountParams struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	Provider string
}

func (q *Queries) GetConnectionAccount(ctx context.Context, arg GetConnectionAccountParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getConnectionAccount, arg.ID, arg.UserID, arg.Provider)
	var account_key []byte
	err := row.Scan(&account_key)
	return account_key, err
}

const insertOAuthState = `-- name: InsertOAuthState :exec

INSERT INTO oauth_states (id, user_id, session_id, provider_id, connection_id, expires_at)
SELECT $1, $2, $3, p.id, $4, $5
FROM providers p WHERE p.code = $6
`

type InsertOAuthStateParams struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	SessionID    uuid.UUID
	ConnectionID *uuid.UUID
	ExpiresAt    time.Time
	Provider     string
}

// OAuth connection flow (J08.2); see docs/architecture/connectors.md#oauth-connection-flow.
func (q *Queries) InsertOAuthState(ctx context.Context, arg InsertOAuthStateParams) error {
	_, err := q.db.Exec(ctx, insertOAuthState,
		arg.ID,
		arg.UserID,
		arg.SessionID,
		arg.ConnectionID,
		arg.ExpiresAt,
		arg.Provider,
	)
	return err
}

const reauthorizeConnection = `-- name: ReauthorizeConnection :exec
UPDATE connections
SET account_key = coalesce(account_key, $1), status = 'active', last_error_class = NULL,
    consecutive_failures = 0, updated_at = now()
WHERE id = $2
`

type ReauthorizeConnectionParams struct {
	AccountKey []byte
	ID         uuid.UUID
}

func (q *Queries) ReauthorizeConnection(ctx context.Context, arg ReauthorizeConnectionParams) error {
	_, err := q.db.Exec(ctx, reauthorizeConnection, arg.AccountKey, arg.ID)
	return err
}

const upsertOAuthConnection = `-- name: UpsertOAuthConnection :one
INSERT INTO connections (id, user_id, provider_id, account_key, mode, status)
SELECT $1, $2, p.id, $3, 'in_process', 'active' FROM providers p WHERE p.code = $4
ON CONFLICT (user_id, provider_id, account_key) DO UPDATE
SET status = 'active', last_error_class = NULL, consecutive_failures = 0, updated_at = now()
RETURNING id, (xmax = 0) AS created
`

type UpsertOAuthConnectionParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	AccountKey []byte
	Provider   string
}

type UpsertOAuthConnectionRow struct {
	ID      uuid.UUID
	Created bool
}

// Reconnecting the same provider account reuses its connection (UNIQUE user, provider, account_key).
func (q *Queries) UpsertOAuthConnection(ctx context.Context, arg UpsertOAuthConnectionParams) (UpsertOAuthConnectionRow, error) {
	row := q.db.QueryRow(ctx, upsertOAuthConnection,
		arg.ID,
		arg.UserID,
		arg.AccountKey,
		arg.Provider,
	)
	var i UpsertOAuthConnectionRow
	err := row.Scan(&i.ID, &i.Created)
	return i, err
}
