// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: origins.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listOwnerOrigins = `-- name: ListOwnerOrigins :many

SELECT o.id, p.code AS provider, o.origin_key, o.name, o.is_native, rp.code AS relayed_provider, o.created_at
FROM data_origins o
JOIN providers p ON p.id = o.provider_id
LEFT JOIN providers rp ON rp.id = o.relayed_provider_id
WHERE o.user_id = $1
ORDER BY p.code, o.origin_key
`

type ListOwnerOriginsRow struct {
	ID              uuid.UUID
	Provider        string
	OriginKey       string
	Name            *string
	IsNative        bool
	RelayedProvider *string
	CreatedAt       time.Time
}

// Origins and source devices the configurator lists (J15.6; docs/architecture/apple-health.md#origins-and-relays).
func (q *Queries) ListOwnerOrigins(ctx context.Context, userID uuid.UUID) ([]ListOwnerOriginsRow, error) {
	rows, err := q.db.Query(ctx, listOwnerOrigins, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOwnerOriginsRow
	for rows.Next() {
		var i ListOwnerOriginsRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.OriginKey,
			&i.Name,
			&i.IsNative,
			&i.RelayedProvider,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelayTargets = `-- name: ListRelayTargets :many
SELECT DISTINCT p.code, p.name FROM known_relay_origins k JOIN providers p ON p.id = k.relayed_provider_id ORDER BY p.name
`

type ListRelayTargetsRow struct {
	Code string
	Name string
}

// The vendors an origin can relay: those known_relay_origins already maps an origin to.
func (q *Queries) ListRelayTargets(ctx context.Context) ([]ListRelayTargetsRow, error) {
	rows, err := q.db.Query(ctx, listRelayTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRelayTargetsRow
	for rows.Next() {
		var i ListRelayTargetsRow
		if err := rows.Scan(&i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceDevices = `-- name: ListSourceDevices :many
SELECT d.id, p.code AS provider, d.device_type, d.manufacturer, d.model
FROM devices d JOIN providers p ON p.id = d.provider_id
WHERE d.user_id = $1
ORDER BY p.code, d.device_type, d.model, d.id
`

type ListSourceDevicesRow struct {
	ID           uuid.UUID
	Provider     string
	DeviceType   *string
	Manufacturer *string
	Model        *string
}

func (q *Queries) ListSourceDevices(ctx context.Context, userID uuid.UUID) ([]ListSourceDevicesRow, error) {
	rows, err := q.db.Query(ctx, listSourceDevices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSourceDevicesRow
	for rows.Next() {
		var i ListSourceDevicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.DeviceType,
			&i.Manufacturer,
			&i.Model,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOriginRelay = `-- name: SetOriginRelay :execrows
UPDATE data_origins o SET relayed_provider_id = (SELECT p.id FROM providers p WHERE p.code = $1::text)
WHERE o.id = $2 AND o.user_id = $3
`

type SetOriginRelayParams struct {
	RelayedProvider *string
	ID              uuid.UUID
	UserID          uuid.UUID
}

// Sets or clears (null) the vendor an origin relays. The edit wins over known_relay_origins, which
// only seeds new origins (UpsertOrigin); a trigger clears the owner's resolved cache.
func (q *Queries) SetOriginRelay(ctx context.Context, arg SetOriginRelayParams) (int64, error) {
	result, err := q.db.Exec(ctx, setOriginRelay, arg.RelayedProvider, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
