// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: overrides.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getOverride = `-- name: GetOverride :one
SELECT id, user_id, metric, window_kind, window_key, local_date, action, input_id, source_group, value, unit, note, created_by, created_at, revoked_at, revoked_by FROM manual_overrides WHERE id = $1 AND user_id = $2
`

type GetOverrideParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetOverride(ctx context.Context, arg GetOverrideParams) (ManualOverride, error) {
	row := q.db.QueryRow(ctx, getOverride, arg.ID, arg.UserID)
	var i ManualOverride
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Metric,
		&i.WindowKind,
		&i.WindowKey,
		&i.LocalDate,
		&i.Action,
		&i.InputID,
		&i.SourceGroup,
		&i.Value,
		&i.Unit,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.RevokedBy,
	)
	return i, err
}

const insertOverride = `-- name: InsertOverride :one

INSERT INTO manual_overrides (id, user_id, metric, window_kind, window_key, local_date, action,
                              input_id, source_group, value, unit, note, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, $11, $12, $13)
RETURNING id, user_id, metric, window_kind, window_key, local_date, action, input_id, source_group, value, unit, note, created_by, created_at, revoked_at, revoked_by
`

type InsertOverrideParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Metric      string
	WindowKind  string
	WindowKey   string
	LocalDate   time.Time
	Action      string
	InputID     *int64
	SourceGroup *string
	Value       *float64
	Unit        *string
	Note        *string
	CreatedBy   string
}

// Manual overrides (J09.7). Rows are never deleted; a revoke sets revoked_at.
func (q *Queries) InsertOverride(ctx context.Context, arg InsertOverrideParams) (ManualOverride, error) {
	row := q.db.QueryRow(ctx, insertOverride,
		arg.ID,
		arg.UserID,
		arg.Metric,
		arg.WindowKind,
		arg.WindowKey,
		arg.LocalDate,
		arg.Action,
		arg.InputID,
		arg.SourceGroup,
		arg.Value,
		arg.Unit,
		arg.Note,
		arg.CreatedBy,
	)
	var i ManualOverride
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Metric,
		&i.WindowKind,
		&i.WindowKey,
		&i.LocalDate,
		&i.Action,
		&i.InputID,
		&i.SourceGroup,
		&i.Value,
		&i.Unit,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.RevokedBy,
	)
	return i, err
}

const listActiveOverrides = `-- name: ListActiveOverrides :many
SELECT id, user_id, metric, window_kind, window_key, local_date, action, input_id, source_group, value, unit, note, created_by, created_at, revoked_at, revoked_by FROM manual_overrides
WHERE user_id = $1 AND metric = $2 AND revoked_at IS NULL
  AND local_date BETWEEN $3::date AND $4::date
ORDER BY created_at, id
`

type ListActiveOverridesParams struct {
	UserID   uuid.UUID
	Metric   string
	FromDate time.Time
	ToDate   time.Time
}

func (q *Queries) ListActiveOverrides(ctx context.Context, arg ListActiveOverridesParams) ([]ManualOverride, error) {
	rows, err := q.db.Query(ctx, listActiveOverrides,
		arg.UserID,
		arg.Metric,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManualOverride
	for rows.Next() {
		var i ManualOverride
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Metric,
			&i.WindowKind,
			&i.WindowKey,
			&i.LocalDate,
			&i.Action,
			&i.InputID,
			&i.SourceGroup,
			&i.Value,
			&i.Unit,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.RevokedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOverrideDirty = `-- name: MarkOverrideDirty :exec
INSERT INTO resolution_dirty (user_id, metric_id, local_date)
SELECT $1::uuid, id, $2::date FROM metric_catalog WHERE code = ANY($3::text[])
ON CONFLICT (user_id, metric_id, local_date) DO UPDATE SET marked_at = now()
`

type MarkOverrideDirtyParams struct {
	UserID    uuid.UUID
	LocalDate time.Time
	Codes     []string
}

func (q *Queries) MarkOverrideDirty(ctx context.Context, arg MarkOverrideDirtyParams) error {
	_, err := q.db.Exec(ctx, markOverrideDirty, arg.UserID, arg.LocalDate, arg.Codes)
	return err
}

const revokeOverride = `-- name: RevokeOverride :one
UPDATE manual_overrides SET revoked_at = now(), revoked_by = $1
WHERE id = $2 AND user_id = $3 AND revoked_at IS NULL
RETURNING id, user_id, metric, window_kind, window_key, local_date, action, input_id, source_group, value, unit, note, created_by, created_at, revoked_at, revoked_by
`

type RevokeOverrideParams struct {
	RevokedBy *string
	ID        uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) RevokeOverride(ctx context.Context, arg RevokeOverrideParams) (ManualOverride, error) {
	row := q.db.QueryRow(ctx, revokeOverride, arg.RevokedBy, arg.ID, arg.UserID)
	var i ManualOverride
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Metric,
		&i.WindowKind,
		&i.WindowKey,
		&i.LocalDate,
		&i.Action,
		&i.InputID,
		&i.SourceGroup,
		&i.Value,
		&i.Unit,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.RevokedBy,
	)
	return i, err
}
