// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push.sql

package dbq

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const claimIdempotencyKey = `-- name: ClaimIdempotencyKey :execrows
INSERT INTO idempotency_keys (client_id, key, request_sha256)
VALUES ($1, $2, $3)
ON CONFLICT (client_id, key) DO NOTHING
`

type ClaimIdempotencyKeyParams struct {
	ClientID      uuid.UUID
	Key           string
	RequestSha256 []byte
}

// A concurrent claim of the same key waits for the claiming transaction, then inserts nothing.
func (q *Queries) ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimIdempotencyKey, arg.ClientID, arg.Key, arg.RequestSha256)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT request_sha256, response_status, response_body FROM idempotency_keys
WHERE client_id = $1 AND key = $2
`

type GetIdempotencyKeyParams struct {
	ClientID uuid.UUID
	Key      string
}

type GetIdempotencyKeyRow struct {
	RequestSha256  []byte
	ResponseStatus *int16
	ResponseBody   []byte
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (GetIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.ClientID, arg.Key)
	var i GetIdempotencyKeyRow
	err := row.Scan(&i.RequestSha256, &i.ResponseStatus, &i.ResponseBody)
	return i, err
}

const getIngestBatch = `-- name: GetIngestBatch :one
SELECT id, connection_id, received_at FROM ingest_batches WHERE id = $1
`

type GetIngestBatchRow struct {
	ID           uuid.UUID
	ConnectionID uuid.UUID
	ReceivedAt   time.Time
}

func (q *Queries) GetIngestBatch(ctx context.Context, id uuid.UUID) (GetIngestBatchRow, error) {
	row := q.db.QueryRow(ctx, getIngestBatch, id)
	var i GetIngestBatchRow
	err := row.Scan(&i.ID, &i.ConnectionID, &i.ReceivedAt)
	return i, err
}

const latestNormalizeJobStatus = `-- name: LatestNormalizeJobStatus :one
SELECT status FROM jobs
WHERE kind = 'normalize_batch' AND payload->>'batch_id' = $1::text
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) LatestNormalizeJobStatus(ctx context.Context, batchID string) (string, error) {
	row := q.db.QueryRow(ctx, latestNormalizeJobStatus, batchID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const listBatchRaw = `-- name: ListBatchRaw :many
SELECT id, external_key, status FROM raw_payloads WHERE batch_id = $1 ORDER BY id
`

type ListBatchRawRow struct {
	ID          int64
	ExternalKey string
	Status      string
}

func (q *Queries) ListBatchRaw(ctx context.Context, batchID uuid.UUID) ([]ListBatchRawRow, error) {
	rows, err := q.db.Query(ctx, listBatchRaw, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBatchRawRow
	for rows.Next() {
		var i ListBatchRawRow
		if err := rows.Scan(&i.ID, &i.ExternalKey, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setClientHeartbeat = `-- name: SetClientHeartbeat :execrows
UPDATE clients SET metadata = metadata || jsonb_build_object('heartbeat', $1::jsonb)
WHERE id = $2
  AND (metadata->'heartbeat'->>'sent_at' IS NULL OR (metadata->'heartbeat'->>'sent_at')::timestamptz <= $3::timestamptz)
`

type SetClientHeartbeatParams struct {
	Heartbeat json.RawMessage
	ID        uuid.UUID
	SentAt    time.Time
}

// Skips a heartbeat older than the one already recorded (sent_at), so a late retry cannot
// roll the state back.
func (q *Queries) SetClientHeartbeat(ctx context.Context, arg SetClientHeartbeatParams) (int64, error) {
	result, err := q.db.Exec(ctx, setClientHeartbeat, arg.Heartbeat, arg.ID, arg.SentAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setIdempotencyResponse = `-- name: SetIdempotencyResponse :one
UPDATE idempotency_keys SET response_status = $1::smallint, response_body = $2::jsonb
WHERE client_id = $3 AND key = $4
RETURNING response_body
`

type SetIdempotencyResponseParams struct {
	ResponseStatus int16
	ResponseBody   json.RawMessage
	ClientID       uuid.UUID
	Key            string
}

// Returns the body as stored (jsonb reorders keys), so the first answer equals every replay.
func (q *Queries) SetIdempotencyResponse(ctx context.Context, arg SetIdempotencyResponseParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, setIdempotencyResponse,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.ClientID,
		arg.Key,
	)
	var response_body []byte
	err := row.Scan(&response_body)
	return response_body, err
}

const upsertPushCursor = `-- name: UpsertPushCursor :exec
INSERT INTO sync_cursors (connection_id, stream, cursor, high_watermark, status, status_reason, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (connection_id, stream) DO UPDATE
SET cursor = COALESCE(EXCLUDED.cursor, sync_cursors.cursor),
    high_watermark = COALESCE(EXCLUDED.high_watermark, sync_cursors.high_watermark),
    status = EXCLUDED.status, status_reason = EXCLUDED.status_reason, updated_at = now()
`

type UpsertPushCursorParams struct {
	ConnectionID  uuid.UUID
	Stream        string
	Cursor        []byte
	HighWatermark *time.Time
	Status        string
	StatusReason  *string
}

// A push client's checkpoint for one stream, as reported in its heartbeat.
func (q *Queries) UpsertPushCursor(ctx context.Context, arg UpsertPushCursorParams) error {
	_, err := q.db.Exec(ctx, upsertPushCursor,
		arg.ConnectionID,
		arg.Stream,
		arg.Cursor,
		arg.HighWatermark,
		arg.Status,
		arg.StatusReason,
	)
	return err
}
