// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: raw.sql

package dbq

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const getRawStatus = `-- name: GetRawStatus :one
SELECT status FROM raw_payloads WHERE id = $1
`

func (q *Queries) GetRawStatus(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, getRawStatus, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const insertIngestBatch = `-- name: InsertIngestBatch :exec
INSERT INTO ingest_batches (id, user_id, connection_id, client_id, source_kind, migration_source, idempotency_key)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertIngestBatchParams struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	ConnectionID    uuid.UUID
	ClientID        *uuid.UUID
	SourceKind      string
	MigrationSource *string
	IdempotencyKey  *string
}

func (q *Queries) InsertIngestBatch(ctx context.Context, arg InsertIngestBatchParams) error {
	_, err := q.db.Exec(ctx, insertIngestBatch,
		arg.ID,
		arg.UserID,
		arg.ConnectionID,
		arg.ClientID,
		arg.SourceKind,
		arg.MigrationSource,
		arg.IdempotencyKey,
	)
	return err
}

const insertRawPayload = `-- name: InsertRawPayload :one
INSERT INTO raw_payloads (user_id, connection_id, batch_id, stream, external_key, version, supersedes_id,
                          content_sha256, content_type, fetched_at, request_meta, shape_fingerprint, status)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, $11, $12, $13)
RETURNING id
`

type InsertRawPayloadParams struct {
	UserID           uuid.UUID
	ConnectionID     uuid.UUID
	BatchID          uuid.UUID
	Stream           string
	ExternalKey      string
	Version          int32
	SupersedesID     *int64
	ContentSha256    []byte
	ContentType      string
	FetchedAt        time.Time
	RequestMeta      json.RawMessage
	ShapeFingerprint *string
	Status           string
}

func (q *Queries) InsertRawPayload(ctx context.Context, arg InsertRawPayloadParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertRawPayload,
		arg.UserID,
		arg.ConnectionID,
		arg.BatchID,
		arg.Stream,
		arg.ExternalKey,
		arg.Version,
		arg.SupersedesID,
		arg.ContentSha256,
		arg.ContentType,
		arg.FetchedAt,
		arg.RequestMeta,
		arg.ShapeFingerprint,
		arg.Status,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const latestRawVersion = `-- name: LatestRawVersion :one
SELECT id, version, content_sha256 FROM raw_payloads
WHERE connection_id = $1 AND stream = $2 AND external_key = $3
ORDER BY version DESC
LIMIT 1
`

type LatestRawVersionParams struct {
	ConnectionID uuid.UUID
	Stream       string
	ExternalKey  string
}

type LatestRawVersionRow struct {
	ID            int64
	Version       int32
	ContentSha256 []byte
}

func (q *Queries) LatestRawVersion(ctx context.Context, arg LatestRawVersionParams) (LatestRawVersionRow, error) {
	row := q.db.QueryRow(ctx, latestRawVersion, arg.ConnectionID, arg.Stream, arg.ExternalKey)
	var i LatestRawVersionRow
	err := row.Scan(&i.ID, &i.Version, &i.ContentSha256)
	return i, err
}

const lockRawKey = `-- name: LockRawKey :exec
SELECT pg_advisory_xact_lock($1::integer, hashtext($2::text))
`

type LockRawKeyParams struct {
	Class int32
	Key   string
}

// Serializes versioning of one (connection, stream, external_key) until commit.
func (q *Queries) LockRawKey(ctx context.Context, arg LockRawKeyParams) error {
	_, err := q.db.Exec(ctx, lockRawKey, arg.Class, arg.Key)
	return err
}

const setRawStatus = `-- name: SetRawStatus :execrows
UPDATE raw_payloads SET status = $1 WHERE id = $2 AND status = ANY($3::text[])
`

type SetRawStatusParams struct {
	Status     string
	ID         int64
	FromStatus []string
}

func (q *Queries) SetRawStatus(ctx context.Context, arg SetRawStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setRawStatus, arg.Status, arg.ID, arg.FromStatus)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
