// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: remote.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
)

const registerProvider = `-- name: RegisterProvider :exec

SELECT register_provider($1::text, $2::text)
`

type RegisterProviderParams struct {
	Code string
	Name string
}

// Remote sidecar connectors (J17.2); see docs/architecture/connectors.md#remote-sidecar-mode.
// A sidecar's provider code; a known code keeps its name and id.
func (q *Queries) RegisterProvider(ctx context.Context, arg RegisterProviderParams) error {
	_, err := q.db.Exec(ctx, registerProvider, arg.Code, arg.Name)
	return err
}

const updateConnectionUpstream = `-- name: UpdateConnectionUpstream :many
WITH old AS (
  SELECT c.id, c.upstream FROM connections c JOIN providers p ON p.id = c.provider_id
  WHERE p.code = $2 AND c.mode = 'remote' AND c.upstream IS DISTINCT FROM $1::jsonb
  FOR UPDATE OF c
)
UPDATE connections c SET upstream = $1::jsonb, updated_at = now()
FROM old WHERE c.id = old.id
RETURNING c.id, c.user_id, old.upstream AS previous
`

type UpdateConnectionUpstreamParams struct {
	Upstream []byte
	Provider string
}

type UpdateConnectionUpstreamRow struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	Previous []byte
}

// Records a sidecar's upstream package on its connections; returns the ones that changed, with
// the previous value, for the audit trail.
func (q *Queries) UpdateConnectionUpstream(ctx context.Context, arg UpdateConnectionUpstreamParams) ([]UpdateConnectionUpstreamRow, error) {
	rows, err := q.db.Query(ctx, updateConnectionUpstream, arg.Upstream, arg.Provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UpdateConnectionUpstreamRow
	for rows.Next() {
		var i UpdateConnectionUpstreamRow
		if err := rows.Scan(&i.ID, &i.UserID, &i.Previous); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
