// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resolved.sql

package dbq

import (
	"context"

	"github.com/google/uuid"
)

const resolvedSourceProvenance = `-- name: ResolvedSourceProvenance :many

SELECT k.src::integer AS src,
  COALESCE(array_agg(DISTINCT x.raw_payload_id ORDER BY x.raw_payload_id) FILTER (WHERE x.raw_payload_id IS NOT NULL), '{}')::bigint[] AS raw_payload_ids,
  string_agg(DISTINCT nv.name || '@' || nv.version::text, ', ')::text AS normalizer,
  COALESCE(max(rp.code), '')::text AS relayed_provider
FROM (SELECT unnest($1::bigint[]) AS id, unnest($2::integer[]) AS src) AS k
JOIN measurements x ON x.id = k.id AND x.user_id = $3
JOIN normalizer_versions nv ON nv.id = x.normalizer_version_id
LEFT JOIN data_origins o ON o.id = x.origin_id
LEFT JOIN providers rp ON rp.id = o.relayed_provider_id
GROUP BY k.src
ORDER BY k.src
`

type ResolvedSourceProvenanceParams struct {
	Ids    []int64
	Srcs   []int32
	UserID uuid.UUID
}

type ResolvedSourceProvenanceRow struct {
	Src             int32
	RawPayloadIds   []int64
	Normalizer      string
	RelayedProvider string
}

// Resolved endpoints (J10.3, internal/api/resolved.go).
// Provenance of the all-sources drilldown: the rows of each source (src, 0-based, parallel to
// ids) with their raw payloads, normalizers and the provider an origin relays.
func (q *Queries) ResolvedSourceProvenance(ctx context.Context, arg ResolvedSourceProvenanceParams) ([]ResolvedSourceProvenanceRow, error) {
	rows, err := q.db.Query(ctx, resolvedSourceProvenance, arg.Ids, arg.Srcs, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResolvedSourceProvenanceRow
	for rows.Next() {
		var i ResolvedSourceProvenanceRow
		if err := rows.Scan(
			&i.Src,
			&i.RawPayloadIds,
			&i.Normalizer,
			&i.RelayedProvider,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
