// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resolve.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const resolveMeasurements = `-- name: ResolveMeasurements :many

SELECT x.id, array_position($1::text[], mc.code)::integer AS metric_idx, x.kind, x.start_at, x.end_at,
  x.local_date, x.value, x.quality_flags, COALESCE(x.group_id, 0)::bigint AS group_id, x.provider_id, x.connection_id,
  x.device_id, x.origin_id
FROM measurements x
JOIN metric_catalog mc ON mc.id = x.metric_id
WHERE x.user_id = $2
  AND x.metric_id IN (SELECT id FROM metric_catalog WHERE code = ANY($1::text[]))
  AND x.start_at >= $3 AND x.start_at < $4
  AND x.superseded_at IS NULL AND x.deleted_at IS NULL
ORDER BY x.start_at, x.id
`

type ResolveMeasurementsParams struct {
	Metrics []string
	UserID  uuid.UUID
	FromAt  time.Time
	ToAt    time.Time
}

type ResolveMeasurementsRow struct {
	ID           int64
	MetricIdx    int32
	Kind         string
	StartAt      time.Time
	EndAt        *time.Time
	LocalDate    time.Time
	Value        float64
	QualityFlags int32
	GroupID      int64
	ProviderID   int16
	ConnectionID uuid.UUID
	DeviceID     *uuid.UUID
	OriginID     *uuid.UUID
}

// Resolution reads (J09.8, internal/resolve/load.go): active canonical rows with the selector
// identity rules match on (docs/architecture/resolution.md#selectors-and-validation).
// Active rows of the metrics starting from from_at and before to_at. Callers pad the range so
// intervals crossing into a window and rows of its local dates are included. metric_idx is the
// 1-based position of the row's code in metrics; the source ids resolve through
// ResolveSourceIdentities, which keeps a dense series small on the wire.
func (q *Queries) ResolveMeasurements(ctx context.Context, arg ResolveMeasurementsParams) ([]ResolveMeasurementsRow, error) {
	rows, err := q.db.Query(ctx, resolveMeasurements,
		arg.Metrics,
		arg.UserID,
		arg.FromAt,
		arg.ToAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResolveMeasurementsRow
	for rows.Next() {
		var i ResolveMeasurementsRow
		if err := rows.Scan(
			&i.ID,
			&i.MetricIdx,
			&i.Kind,
			&i.StartAt,
			&i.EndAt,
			&i.LocalDate,
			&i.Value,
			&i.QualityFlags,
			&i.GroupID,
			&i.ProviderID,
			&i.ConnectionID,
			&i.DeviceID,
			&i.OriginID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveSleepSessions = `-- name: ResolveSleepSessions :many
SELECT x.id, x.start_at, x.end_at, x.tz_offset_min, x.is_nap, x.has_stages,
  x.asleep_s, x.deep_s, x.light_s, x.rem_s, x.awake_s, x.latency_s,
  p.code AS provider, x.connection_id, x.device_id,
  COALESCE(d.device_type, '')::text AS device_type, COALESCE(d.model, '')::text AS device_model,
  COALESCE(o.origin_key, '')::text AS origin_key, COALESCE(o.name, '')::text AS origin_name,
  (o.relayed_provider_id IS NOT NULL)::boolean AS relayed
FROM sleep_sessions x
JOIN providers p ON p.id = x.provider_id
LEFT JOIN devices d ON d.id = x.device_id
LEFT JOIN data_origins o ON o.id = x.origin_id
WHERE x.user_id = $1 AND x.sleep_date BETWEEN $2 AND $3
  AND x.superseded_at IS NULL AND x.deleted_at IS NULL
ORDER BY x.start_at, x.id
`

type ResolveSleepSessionsParams struct {
	UserID   uuid.UUID
	FromDate time.Time
	ToDate   time.Time
}

type ResolveSleepSessionsRow struct {
	ID           uuid.UUID
	StartAt      time.Time
	EndAt        time.Time
	TzOffsetMin  *int16
	IsNap        bool
	HasStages    bool
	AsleepS      *int32
	DeepS        *int32
	LightS       *int32
	RemS         *int32
	AwakeS       *int32
	LatencyS     *int32
	Provider     string
	ConnectionID uuid.UUID
	DeviceID     *uuid.UUID
	DeviceType   string
	DeviceModel  string
	OriginKey    string
	OriginName   string
	Relayed      bool
}

// Active sleep sessions with sleep_date from from_date through to_date. A night reads its own
// date and the day before.
func (q *Queries) ResolveSleepSessions(ctx context.Context, arg ResolveSleepSessionsParams) ([]ResolveSleepSessionsRow, error) {
	rows, err := q.db.Query(ctx, resolveSleepSessions, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResolveSleepSessionsRow
	for rows.Next() {
		var i ResolveSleepSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.StartAt,
			&i.EndAt,
			&i.TzOffsetMin,
			&i.IsNap,
			&i.HasStages,
			&i.AsleepS,
			&i.DeepS,
			&i.LightS,
			&i.RemS,
			&i.AwakeS,
			&i.LatencyS,
			&i.Provider,
			&i.ConnectionID,
			&i.DeviceID,
			&i.DeviceType,
			&i.DeviceModel,
			&i.OriginKey,
			&i.OriginName,
			&i.Relayed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveSleepStages = `-- name: ResolveSleepStages :many
SELECT session_id, stage, start_at, end_at FROM sleep_stages
WHERE session_id = ANY($1::uuid[])
ORDER BY session_id, start_at, id
`

type ResolveSleepStagesRow struct {
	SessionID uuid.UUID
	Stage     string
	StartAt   time.Time
	EndAt     time.Time
}

func (q *Queries) ResolveSleepStages(ctx context.Context, sessionIds []uuid.UUID) ([]ResolveSleepStagesRow, error) {
	rows, err := q.db.Query(ctx, resolveSleepStages, sessionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResolveSleepStagesRow
	for rows.Next() {
		var i ResolveSleepStagesRow
		if err := rows.Scan(
			&i.SessionID,
			&i.Stage,
			&i.StartAt,
			&i.EndAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveSourceIdentities = `-- name: ResolveSourceIdentities :many
SELECT k.i::integer AS i, p.code AS provider,
  COALESCE(d.device_type, '')::text AS device_type, COALESCE(d.model, '')::text AS device_model,
  COALESCE(o.origin_key, '')::text AS origin_key, COALESCE(o.name, '')::text AS origin_name,
  (o.relayed_provider_id IS NOT NULL)::boolean AS relayed
FROM (SELECT unnest($1::smallint[]) AS provider_id, unnest($2::uuid[]) AS device_id,
             unnest($3::uuid[]) AS origin_id,
             generate_series(1, cardinality($1::smallint[])) AS i) AS k
JOIN providers p ON p.id = k.provider_id
LEFT JOIN devices d ON d.id = k.device_id
LEFT JOIN data_origins o ON o.id = k.origin_id
`

type ResolveSourceIdentitiesParams struct {
	ProviderIds []int16
	DeviceIds   []uuid.UUID
	OriginIds   []uuid.UUID
}

type ResolveSourceIdentitiesRow struct {
	I           int32
	Provider    string
	DeviceType  string
	DeviceModel string
	OriginKey   string
	OriginName  string
	Relayed     bool
}

// The selector identity of (provider, device, origin) id triples; uuid.Nil stands for none.
// i is the 1-based position of the triple.
func (q *Queries) ResolveSourceIdentities(ctx context.Context, arg ResolveSourceIdentitiesParams) ([]ResolveSourceIdentitiesRow, error) {
	rows, err := q.db.Query(ctx, resolveSourceIdentities, arg.ProviderIds, arg.DeviceIds, arg.OriginIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResolveSourceIdentitiesRow
	for rows.Next() {
		var i ResolveSourceIdentitiesRow
		if err := rows.Scan(
			&i.I,
			&i.Provider,
			&i.DeviceType,
			&i.DeviceModel,
			&i.OriginKey,
			&i.OriginName,
			&i.Relayed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveWearBuckets = `-- name: ResolveWearBuckets :many
SELECT b.bucket::timestamptz AS bucket, p.code AS provider, b.connection_id, b.device_id,
  COALESCE(d.device_type, '')::text AS device_type, COALESCE(d.model, '')::text AS device_model,
  COALESCE(o.origin_key, '')::text AS origin_key, COALESCE(o.name, '')::text AS origin_name,
  (o.relayed_provider_id IS NOT NULL)::boolean AS relayed
FROM (
  SELECT date_bin('5 minutes', x.start_at, TIMESTAMPTZ '2000-01-01 00:00:00+00') AS bucket,
    x.provider_id, x.connection_id, x.device_id, x.origin_id
  FROM measurements x
  WHERE x.user_id = $1
    AND x.metric_id = (SELECT id FROM metric_catalog WHERE code = $2::text)
    AND x.start_at >= $3 AND x.start_at < $4
    AND x.superseded_at IS NULL AND x.deleted_at IS NULL
    AND x.quality_flags & $5::integer = 0
  GROUP BY 1, 2, 3, 4, 5
) b
JOIN providers p ON p.id = b.provider_id
LEFT JOIN devices d ON d.id = b.device_id
LEFT JOIN data_origins o ON o.id = b.origin_id
WHERE p.code <> 'manual'
ORDER BY 1
`

type ResolveWearBucketsParams struct {
	UserID  uuid.UUID
	Metric  string
	FromAt  time.Time
	ToAt    time.Time
	NotWear int32
}

type ResolveWearBucketsRow struct {
	Bucket       time.Time
	Provider     string
	ConnectionID uuid.UUID
	DeviceID     *uuid.UUID
	DeviceType   string
	DeviceModel  string
	OriginKey    string
	OriginName   string
	Relayed      bool
}

// The wear series of quality.require_wear (E3) as the UTC-aligned 5-minute buckets in which each
// source has a row of the metric starting from from_at and before to_at. Manual and implausible
// rows are not wear (not_wear holds those flag bits). A bucket stands for its rows: the wear gate
// only asks whether a device has a row in a base bucket.
func (q *Queries) ResolveWearBuckets(ctx context.Context, arg ResolveWearBucketsParams) ([]ResolveWearBucketsRow, error) {
	rows, err := q.db.Query(ctx, resolveWearBuckets,
		arg.UserID,
		arg.Metric,
		arg.FromAt,
		arg.ToAt,
		arg.NotWear,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResolveWearBucketsRow
	for rows.Next() {
		var i ResolveWearBucketsRow
		if err := rows.Scan(
			&i.Bucket,
			&i.Provider,
			&i.ConnectionID,
			&i.DeviceID,
			&i.DeviceType,
			&i.DeviceModel,
			&i.OriginKey,
			&i.OriginName,
			&i.Relayed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveWorkouts = `-- name: ResolveWorkouts :many
SELECT x.id, x.start_at, x.end_at, x.sport, x.distance_m, x.energy_kcal, x.avg_hr_bpm, x.max_hr_bpm,
  p.code AS provider, x.connection_id, x.device_id,
  COALESCE(d.device_type, '')::text AS device_type, COALESCE(d.model, '')::text AS device_model,
  COALESCE(o.origin_key, '')::text AS origin_key, COALESCE(o.name, '')::text AS origin_name,
  (o.relayed_provider_id IS NOT NULL)::boolean AS relayed
FROM workouts x
JOIN providers p ON p.id = x.provider_id
LEFT JOIN devices d ON d.id = x.device_id
LEFT JOIN data_origins o ON o.id = x.origin_id
WHERE x.user_id = $1
  AND x.start_at >= $2 AND x.start_at < $3 AND x.end_at > $4
  AND x.superseded_at IS NULL AND x.deleted_at IS NULL
ORDER BY x.start_at, x.id
`

type ResolveWorkoutsParams struct {
	UserID     uuid.UUID
	StartsFrom time.Time
	ToAt       time.Time
	FromAt     time.Time
}

type ResolveWorkoutsRow struct {
	ID           uuid.UUID
	StartAt      time.Time
	EndAt        time.Time
	Sport        string
	DistanceM    *float64
	EnergyKcal   *float64
	AvgHrBpm     *float64
	MaxHrBpm     *float64
	Provider     string
	ConnectionID uuid.UUID
	DeviceID     *uuid.UUID
	DeviceType   string
	DeviceModel  string
	OriginKey    string
	OriginName   string
	Relayed      bool
}

// Active workouts overlapping from_at to to_at. Callers set starts_from a day before from_at.
func (q *Queries) ResolveWorkouts(ctx context.Context, arg ResolveWorkoutsParams) ([]ResolveWorkoutsRow, error) {
	rows, err := q.db.Query(ctx, resolveWorkouts,
		arg.UserID,
		arg.StartsFrom,
		arg.ToAt,
		arg.FromAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResolveWorkoutsRow
	for rows.Next() {
		var i ResolveWorkoutsRow
		if err := rows.Scan(
			&i.ID,
			&i.StartAt,
			&i.EndAt,
			&i.Sport,
			&i.DistanceM,
			&i.EnergyKcal,
			&i.AvgHrBpm,
			&i.MaxHrBpm,
			&i.Provider,
			&i.ConnectionID,
			&i.DeviceID,
			&i.DeviceType,
			&i.DeviceModel,
			&i.OriginKey,
			&i.OriginName,
			&i.Relayed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
