// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resolve.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const resolveMeasurements = `-- name: ResolveMeasurements :many

SELECT x.id, mc.code AS metric, x.kind, x.start_at, x.end_at, x.local_date, x.value, x.quality_flags,
  COALESCE(x.group_id, 0)::bigint AS group_id, p.code AS provider, x.connection_id, x.device_id,
  COALESCE(d.device_type, '')::text AS device_type, COALESCE(d.model, '')::text AS device_model,
  COALESCE(o.origin_key, '')::text AS origin_key, COALESCE(o.name, '')::text AS origin_name,
  (o.relayed_provider_id IS NOT NULL)::boolean AS relayed
FROM measurements x
JOIN metric_catalog mc ON mc.id = x.metric_id
JOIN providers p ON p.id = x.provider_id
LEFT JOIN devices d ON d.id = x.device_id
LEFT JOIN data_origins o ON o.id = x.origin_id
WHERE x.user_id = $1
  AND x.metric_id IN (SELECT id FROM metric_catalog WHERE code = ANY($2::text[]))
  AND x.start_at >= $3 AND x.start_at < $4
  AND x.superseded_at IS NULL AND x.deleted_at IS NULL
ORDER BY x.start_at, x.id
`

type ResolveMeasurementsParams struct {
	UserID  uuid.UUID
	Metrics []string
	FromAt  time.Time
	ToAt    time.Time
}

type ResolveMeasurementsRow struct {
	ID           int64
	Metric       string
	Kind         string
	StartAt      time.Time
	EndAt        *time.Time
	LocalDate    time.Time
	Value        float64
	QualityFlags int32
	GroupID      int64
	Provider     string
	ConnectionID uuid.UUID
	DeviceID     *uuid.UUID
	DeviceType   string
	DeviceModel  string
	OriginKey    string
	OriginName   string
	Relayed      bool
}

// Resolution reads (J09.8, internal/resolve/load.go): active canonical rows with the selector
// identity rules match on (docs/architecture/resolution.md#selectors-and-validation).
// Active rows of the metrics starting from from_at and before to_at. Callers pad the range so
// intervals crossing into a window and rows of its local dates are included.
func (q *Queries) ResolveMeasurements(ctx context.Context, arg ResolveMeasurementsParams) ([]ResolveMeasurementsRow, error) {
	rows, err := q.db.Query(ctx, resolveMeasurements,
		arg.UserID,
		arg.Metrics,
		arg.FromAt,
		arg.ToAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResolveMeasurementsRow
	for rows.Next() {
		var i ResolveMeasurementsRow
		if err := rows.Scan(
			&i.ID,
			&i.Metric,
			&i.Kind,
			&i.StartAt,
			&i.EndAt,
			&i.LocalDate,
			&i.Value,
			&i.QualityFlags,
			&i.GroupID,
			&i.Provider,
			&i.ConnectionID,
			&i.DeviceID,
			&i.DeviceType,
			&i.DeviceModel,
			&i.OriginKey,
			&i.OriginName,
			&i.Relayed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveSleepSessions = `-- name: ResolveSleepSessions :many
SELECT x.id, x.start_at, x.end_at, x.tz_offset_min, x.is_nap, x.has_stages,
  x.asleep_s, x.deep_s, x.light_s, x.rem_s, x.awake_s, x.latency_s,
  p.code AS provider, x.connection_id, x.device_id,
  COALESCE(d.device_type, '')::text AS device_type, COALESCE(d.model, '')::text AS device_model,
  COALESCE(o.origin_key, '')::text AS origin_key, COALESCE(o.name, '')::text AS origin_name,
  (o.relayed_provider_id IS NOT NULL)::boolean AS relayed
FROM sleep_sessions x
JOIN providers p ON p.id = x.provider_id
LEFT JOIN devices d ON d.id = x.device_id
LEFT JOIN data_origins o ON o.id = x.origin_id
WHERE x.user_id = $1 AND x.sleep_date BETWEEN $2 AND $3
  AND x.superseded_at IS NULL AND x.deleted_at IS NULL
ORDER BY x.start_at, x.id
`

type ResolveSleepSessionsParams struct {
	UserID   uuid.UUID
	FromDate time.Time
	ToDate   time.Time
}

type ResolveSleepSessionsRow struct {
	ID           uuid.UUID
	StartAt      time.Time
	EndAt        time.Time
	TzOffsetMin  *int16
	IsNap        bool
	HasStages    bool
	AsleepS      *int32
	DeepS        *int32
	LightS       *int32
	RemS         *int32
	AwakeS       *int32
	LatencyS     *int32
	Provider     string
	ConnectionID uuid.UUID
	DeviceID     *uuid.UUID
	DeviceType   string
	DeviceModel  string
	OriginKey    string
	OriginName   string
	Relayed      bool
}

// Active sleep sessions with sleep_date from from_date through to_date. A night reads its own
// date and the day before.
func (q *Queries) ResolveSleepSessions(ctx context.Context, arg ResolveSleepSessionsParams) ([]ResolveSleepSessionsRow, error) {
	rows, err := q.db.Query(ctx, resolveSleepSessions, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResolveSleepSessionsRow
	for rows.Next() {
		var i ResolveSleepSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.StartAt,
			&i.EndAt,
			&i.TzOffsetMin,
			&i.IsNap,
			&i.HasStages,
			&i.AsleepS,
			&i.DeepS,
			&i.LightS,
			&i.RemS,
			&i.AwakeS,
			&i.LatencyS,
			&i.Provider,
			&i.ConnectionID,
			&i.DeviceID,
			&i.DeviceType,
			&i.DeviceModel,
			&i.OriginKey,
			&i.OriginName,
			&i.Relayed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveSleepStages = `-- name: ResolveSleepStages :many
SELECT session_id, stage, start_at, end_at FROM sleep_stages
WHERE session_id = ANY($1::uuid[])
ORDER BY session_id, start_at, id
`

type ResolveSleepStagesRow struct {
	SessionID uuid.UUID
	Stage     string
	StartAt   time.Time
	EndAt     time.Time
}

func (q *Queries) ResolveSleepStages(ctx context.Context, sessionIds []uuid.UUID) ([]ResolveSleepStagesRow, error) {
	rows, err := q.db.Query(ctx, resolveSleepStages, sessionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResolveSleepStagesRow
	for rows.Next() {
		var i ResolveSleepStagesRow
		if err := rows.Scan(
			&i.SessionID,
			&i.Stage,
			&i.StartAt,
			&i.EndAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveWorkouts = `-- name: ResolveWorkouts :many
SELECT x.id, x.start_at, x.end_at, x.sport, x.distance_m, x.energy_kcal, x.avg_hr_bpm, x.max_hr_bpm,
  p.code AS provider, x.connection_id, x.device_id,
  COALESCE(d.device_type, '')::text AS device_type, COALESCE(d.model, '')::text AS device_model,
  COALESCE(o.origin_key, '')::text AS origin_key, COALESCE(o.name, '')::text AS origin_name,
  (o.relayed_provider_id IS NOT NULL)::boolean AS relayed
FROM workouts x
JOIN providers p ON p.id = x.provider_id
LEFT JOIN devices d ON d.id = x.device_id
LEFT JOIN data_origins o ON o.id = x.origin_id
WHERE x.user_id = $1
  AND x.start_at >= $2 AND x.start_at < $3 AND x.end_at > $4
  AND x.superseded_at IS NULL AND x.deleted_at IS NULL
ORDER BY x.start_at, x.id
`

type ResolveWorkoutsParams struct {
	UserID     uuid.UUID
	StartsFrom time.Time
	ToAt       time.Time
	FromAt     time.Time
}

type ResolveWorkoutsRow struct {
	ID           uuid.UUID
	StartAt      time.Time
	EndAt        time.Time
	Sport        string
	DistanceM    *float64
	EnergyKcal   *float64
	AvgHrBpm     *float64
	MaxHrBpm     *float64
	Provider     string
	ConnectionID uuid.UUID
	DeviceID     *uuid.UUID
	DeviceType   string
	DeviceModel  string
	OriginKey    string
	OriginName   string
	Relayed      bool
}

// Active workouts overlapping from_at to to_at. Callers set starts_from a day before from_at.
func (q *Queries) ResolveWorkouts(ctx context.Context, arg ResolveWorkoutsParams) ([]ResolveWorkoutsRow, error) {
	rows, err := q.db.Query(ctx, resolveWorkouts,
		arg.UserID,
		arg.StartsFrom,
		arg.ToAt,
		arg.FromAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResolveWorkoutsRow
	for rows.Next() {
		var i ResolveWorkoutsRow
		if err := rows.Scan(
			&i.ID,
			&i.StartAt,
			&i.EndAt,
			&i.Sport,
			&i.DistanceM,
			&i.EnergyKcal,
			&i.AvgHrBpm,
			&i.MaxHrBpm,
			&i.Provider,
			&i.ConnectionID,
			&i.DeviceID,
			&i.DeviceType,
			&i.DeviceModel,
			&i.OriginKey,
			&i.OriginName,
			&i.Relayed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
