// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review.sql

package dbq

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const deleteLabReport = `-- name: DeleteLabReport :exec
DELETE FROM lab_reports WHERE id = $1
`

func (q *Queries) DeleteLabReport(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLabReport, id)
	return err
}

const deleteLabResult = `-- name: DeleteLabResult :exec
DELETE FROM lab_results WHERE id = $1
`

func (q *Queries) DeleteLabResult(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLabResult, id)
	return err
}

const getDocumentReport = `-- name: GetDocumentReport :one
SELECT id, user_id, document_id, run_id, laboratory, reported_at, provider, model, schema_version, prompt_version, confirmed_by, confirmed_at FROM lab_reports WHERE document_id = $1 ORDER BY confirmed_at LIMIT 1
`

// The confirmed report of a document (one per document).
func (q *Queries) GetDocumentReport(ctx context.Context, documentID uuid.UUID) (LabReport, error) {
	row := q.db.QueryRow(ctx, getDocumentReport, documentID)
	var i LabReport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DocumentID,
		&i.RunID,
		&i.Laboratory,
		&i.ReportedAt,
		&i.Provider,
		&i.Model,
		&i.SchemaVersion,
		&i.PromptVersion,
		&i.ConfirmedBy,
		&i.ConfirmedAt,
	)
	return i, err
}

const getLabResult = `-- name: GetLabResult :one
SELECT r.id, r.user_id, r.report_id, r.source_row_id, r.analyte_id, r.original_label, r.value_text, r.value_numeric, r.comparator, r.unit_text, r.reference_range_text, r.ref_low, r.ref_high, r.abnormal_flag_printed, r.specimen_type, r.canonical_value, r.canonical_unit, r.conversion_factor, r.conversion_offset, r.catalog_version, r.collected_at, r.collected_date, r.page, r.evidence_text, r.revision, r.created_at, r.updated_at, a.code AS analyte_code, p.document_id, p.run_id, p.laboratory, p.reported_at, p.provider, p.model,
       p.schema_version, p.prompt_version, p.confirmed_by, p.confirmed_at, x.row_index
FROM lab_results r
JOIN lab_reports p ON p.id = r.report_id
LEFT JOIN analytes a ON a.id = r.analyte_id
LEFT JOIN lab_extracted_rows x ON x.id = r.source_row_id
WHERE r.user_id = $1 AND r.id = $2
`

type GetLabResultParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

type GetLabResultRow struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	ReportID            uuid.UUID
	SourceRowID         *int64
	AnalyteID           *int16
	OriginalLabel       string
	ValueText           string
	ValueNumeric        *float64
	Comparator          *string
	UnitText            *string
	ReferenceRangeText  *string
	RefLow              *float64
	RefHigh             *float64
	AbnormalFlagPrinted *string
	SpecimenType        *string
	CanonicalValue      *float64
	CanonicalUnit       *string
	ConversionFactor    *float64
	ConversionOffset    *float64
	CatalogVersion      *int32
	CollectedAt         *time.Time
	CollectedDate       time.Time
	Page                *int32
	EvidenceText        *string
	Revision            int32
	CreatedAt           time.Time
	UpdatedAt           time.Time
	AnalyteCode         *string
	DocumentID          uuid.UUID
	RunID               *uuid.UUID
	Laboratory          *string
	ReportedAt          *time.Time
	Provider            string
	Model               *string
	SchemaVersion       string
	PromptVersion       string
	ConfirmedBy         string
	ConfirmedAt         time.Time
	RowIndex            *int32
}

func (q *Queries) GetLabResult(ctx context.Context, arg GetLabResultParams) (GetLabResultRow, error) {
	row := q.db.QueryRow(ctx, getLabResult, arg.UserID, arg.ID)
	var i GetLabResultRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ReportID,
		&i.SourceRowID,
		&i.AnalyteID,
		&i.OriginalLabel,
		&i.ValueText,
		&i.ValueNumeric,
		&i.Comparator,
		&i.UnitText,
		&i.ReferenceRangeText,
		&i.RefLow,
		&i.RefHigh,
		&i.AbnormalFlagPrinted,
		&i.SpecimenType,
		&i.CanonicalValue,
		&i.CanonicalUnit,
		&i.ConversionFactor,
		&i.ConversionOffset,
		&i.CatalogVersion,
		&i.CollectedAt,
		&i.CollectedDate,
		&i.Page,
		&i.EvidenceText,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AnalyteCode,
		&i.DocumentID,
		&i.RunID,
		&i.Laboratory,
		&i.ReportedAt,
		&i.Provider,
		&i.Model,
		&i.SchemaVersion,
		&i.PromptVersion,
		&i.ConfirmedBy,
		&i.ConfirmedAt,
		&i.RowIndex,
	)
	return i, err
}

const getOwnerExtractionRun = `-- name: GetOwnerExtractionRun :one

SELECT id, document_id, user_id, job_id, status, provider, model, external, consent, schema_version, prompt_version, provider_request_id, response_blob_sha256, doc_meta, usage, warnings, error_class, created_by, created_at, started_at, finished_at FROM extraction_runs WHERE id = $1 AND user_id = $2
`

type GetOwnerExtractionRunParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Extraction review, confirmation and lab results (J12.4); see docs/architecture/lab-documents.md#review-and-confirmation.
func (q *Queries) GetOwnerExtractionRun(ctx context.Context, arg GetOwnerExtractionRunParams) (ExtractionRun, error) {
	row := q.db.QueryRow(ctx, getOwnerExtractionRun, arg.ID, arg.UserID)
	var i ExtractionRun
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.UserID,
		&i.JobID,
		&i.Status,
		&i.Provider,
		&i.Model,
		&i.External,
		&i.Consent,
		&i.SchemaVersion,
		&i.PromptVersion,
		&i.ProviderRequestID,
		&i.ResponseBlobSha256,
		&i.DocMeta,
		&i.Usage,
		&i.Warnings,
		&i.ErrorClass,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertLabReport = `-- name: InsertLabReport :exec
INSERT INTO lab_reports (id, user_id, document_id, run_id, laboratory, reported_at, provider, model, schema_version, prompt_version, confirmed_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9,
  $10, $11)
`

type InsertLabReportParams struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	DocumentID    uuid.UUID
	RunID         *uuid.UUID
	Laboratory    *string
	ReportedAt    *time.Time
	Provider      string
	Model         *string
	SchemaVersion string
	PromptVersion string
	ConfirmedBy   string
}

func (q *Queries) InsertLabReport(ctx context.Context, arg InsertLabReportParams) error {
	_, err := q.db.Exec(ctx, insertLabReport,
		arg.ID,
		arg.UserID,
		arg.DocumentID,
		arg.RunID,
		arg.Laboratory,
		arg.ReportedAt,
		arg.Provider,
		arg.Model,
		arg.SchemaVersion,
		arg.PromptVersion,
		arg.ConfirmedBy,
	)
	return err
}

const insertLabResult = `-- name: InsertLabResult :exec
INSERT INTO lab_results (id, user_id, report_id, source_row_id, analyte_id, original_label, value_text, value_numeric, comparator,
  unit_text, reference_range_text, ref_low, ref_high, abnormal_flag_printed, specimen_type, canonical_value, canonical_unit,
  conversion_factor, conversion_offset, catalog_version, collected_at, collected_date, page, evidence_text)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
  $9, $10, $11, $12, $13,
  $14, $15, $16, $17,
  $18, $19, $20, $21, $22,
  $23, $24)
`

type InsertLabResultParams struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	ReportID            uuid.UUID
	SourceRowID         *int64
	AnalyteID           *int16
	OriginalLabel       string
	ValueText           string
	ValueNumeric        *float64
	Comparator          *string
	UnitText            *string
	ReferenceRangeText  *string
	RefLow              *float64
	RefHigh             *float64
	AbnormalFlagPrinted *string
	SpecimenType        *string
	CanonicalValue      *float64
	CanonicalUnit       *string
	ConversionFactor    *float64
	ConversionOffset    *float64
	CatalogVersion      *int32
	CollectedAt         *time.Time
	CollectedDate       time.Time
	Page                *int32
	EvidenceText        *string
}

func (q *Queries) InsertLabResult(ctx context.Context, arg InsertLabResultParams) error {
	_, err := q.db.Exec(ctx, insertLabResult,
		arg.ID,
		arg.UserID,
		arg.ReportID,
		arg.SourceRowID,
		arg.AnalyteID,
		arg.OriginalLabel,
		arg.ValueText,
		arg.ValueNumeric,
		arg.Comparator,
		arg.UnitText,
		arg.ReferenceRangeText,
		arg.RefLow,
		arg.RefHigh,
		arg.AbnormalFlagPrinted,
		arg.SpecimenType,
		arg.CanonicalValue,
		arg.CanonicalUnit,
		arg.ConversionFactor,
		arg.ConversionOffset,
		arg.CatalogVersion,
		arg.CollectedAt,
		arg.CollectedDate,
		arg.Page,
		arg.EvidenceText,
	)
	return err
}

const insertLabResultRevision = `-- name: InsertLabResultRevision :exec
INSERT INTO lab_result_revisions (result_id, revision, snapshot, reason, changed_by)
VALUES ($1, $2, $3, $4, $5)
`

type InsertLabResultRevisionParams struct {
	ResultID  uuid.UUID
	Revision  int32
	Snapshot  json.RawMessage
	Reason    *string
	ChangedBy string
}

func (q *Queries) InsertLabResultRevision(ctx context.Context, arg InsertLabResultRevisionParams) error {
	_, err := q.db.Exec(ctx, insertLabResultRevision,
		arg.ResultID,
		arg.Revision,
		arg.Snapshot,
		arg.Reason,
		arg.ChangedBy,
	)
	return err
}

const insertRowEdit = `-- name: InsertRowEdit :exec
INSERT INTO extraction_row_edits (row_id, action, changes, actor) VALUES ($1, $2, $3, $4)
`

type InsertRowEditParams struct {
	RowID   int64
	Action  string
	Changes json.RawMessage
	Actor   string
}

func (q *Queries) InsertRowEdit(ctx context.Context, arg InsertRowEditParams) error {
	_, err := q.db.Exec(ctx, insertRowEdit,
		arg.RowID,
		arg.Action,
		arg.Changes,
		arg.Actor,
	)
	return err
}

const listConfirmedAnalyteDates = `-- name: ListConfirmedAnalyteDates :many
SELECT DISTINCT a.code, r.collected_date
FROM lab_results r JOIN lab_reports p ON p.id = r.report_id JOIN analytes a ON a.id = r.analyte_id
WHERE r.user_id = $1 AND a.code = ANY($2::text[])
  AND p.run_id IS DISTINCT FROM $3::uuid
`

type ListConfirmedAnalyteDatesParams struct {
	UserID uuid.UUID
	Codes  []string
	RunID  uuid.UUID
}

type ListConfirmedAnalyteDatesRow struct {
	Code          string
	CollectedDate time.Time
}

// Analytes and collection dates already confirmed from other runs, for duplicate warnings.
func (q *Queries) ListConfirmedAnalyteDates(ctx context.Context, arg ListConfirmedAnalyteDatesParams) ([]ListConfirmedAnalyteDatesRow, error) {
	rows, err := q.db.Query(ctx, listConfirmedAnalyteDates, arg.UserID, arg.Codes, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConfirmedAnalyteDatesRow
	for rows.Next() {
		var i ListConfirmedAnalyteDatesRow
		if err := rows.Scan(&i.Code, &i.CollectedDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabResultRevisions = `-- name: ListLabResultRevisions :many
SELECT id, result_id, revision, snapshot, reason, changed_by, changed_at FROM lab_result_revisions WHERE result_id = $1 ORDER BY revision DESC
`

// Older revisions, newest first.
func (q *Queries) ListLabResultRevisions(ctx context.Context, resultID uuid.UUID) ([]LabResultRevision, error) {
	rows, err := q.db.Query(ctx, listLabResultRevisions, resultID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LabResultRevision
	for rows.Next() {
		var i LabResultRevision
		if err := rows.Scan(
			&i.ID,
			&i.ResultID,
			&i.Revision,
			&i.Snapshot,
			&i.Reason,
			&i.ChangedBy,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabResults = `-- name: ListLabResults :many
SELECT r.id, r.user_id, r.report_id, r.source_row_id, r.analyte_id, r.original_label, r.value_text, r.value_numeric, r.comparator, r.unit_text, r.reference_range_text, r.ref_low, r.ref_high, r.abnormal_flag_printed, r.specimen_type, r.canonical_value, r.canonical_unit, r.conversion_factor, r.conversion_offset, r.catalog_version, r.collected_at, r.collected_date, r.page, r.evidence_text, r.revision, r.created_at, r.updated_at, a.code AS analyte_code, p.document_id, p.run_id, p.laboratory, p.reported_at, p.provider, p.model,
       p.schema_version, p.prompt_version, p.confirmed_by, p.confirmed_at, x.row_index
FROM lab_results r
JOIN lab_reports p ON p.id = r.report_id
LEFT JOIN analytes a ON a.id = r.analyte_id
LEFT JOIN lab_extracted_rows x ON x.id = r.source_row_id
WHERE r.user_id = $1
  AND ($2::date IS NULL OR r.collected_date >= $2::date)
  AND ($3::date IS NULL OR r.collected_date <= $3::date)
  AND ($4::date IS NULL OR (r.collected_date, r.id) > ($4::date, $5::uuid))
ORDER BY r.collected_date, r.id
LIMIT $6
`

type ListLabResultsParams struct {
	UserID    uuid.UUID
	StartDate *time.Time
	EndDate   *time.Time
	AfterDate *time.Time
	AfterID   uuid.UUID
	Lim       int32
}

type ListLabResultsRow struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	ReportID            uuid.UUID
	SourceRowID         *int64
	AnalyteID           *int16
	OriginalLabel       string
	ValueText           string
	ValueNumeric        *float64
	Comparator          *string
	UnitText            *string
	ReferenceRangeText  *string
	RefLow              *float64
	RefHigh             *float64
	AbnormalFlagPrinted *string
	SpecimenType        *string
	CanonicalValue      *float64
	CanonicalUnit       *string
	ConversionFactor    *float64
	ConversionOffset    *float64
	CatalogVersion      *int32
	CollectedAt         *time.Time
	CollectedDate       time.Time
	Page                *int32
	EvidenceText        *string
	Revision            int32
	CreatedAt           time.Time
	UpdatedAt           time.Time
	AnalyteCode         *string
	DocumentID          uuid.UUID
	RunID               *uuid.UUID
	Laboratory          *string
	ReportedAt          *time.Time
	Provider            string
	Model               *string
	SchemaVersion       string
	PromptVersion       string
	ConfirmedBy         string
	ConfirmedAt         time.Time
	RowIndex            *int32
}

// Keyset page by (collected_date, id) with the provenance of each result.
func (q *Queries) ListLabResults(ctx context.Context, arg ListLabResultsParams) ([]ListLabResultsRow, error) {
	rows, err := q.db.Query(ctx, listLabResults,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
		arg.AfterDate,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLabResultsRow
	for rows.Next() {
		var i ListLabResultsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ReportID,
			&i.SourceRowID,
			&i.AnalyteID,
			&i.OriginalLabel,
			&i.ValueText,
			&i.ValueNumeric,
			&i.Comparator,
			&i.UnitText,
			&i.ReferenceRangeText,
			&i.RefLow,
			&i.RefHigh,
			&i.AbnormalFlagPrinted,
			&i.SpecimenType,
			&i.CanonicalValue,
			&i.CanonicalUnit,
			&i.ConversionFactor,
			&i.ConversionOffset,
			&i.CatalogVersion,
			&i.CollectedAt,
			&i.CollectedDate,
			&i.Page,
			&i.EvidenceText,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AnalyteCode,
			&i.DocumentID,
			&i.RunID,
			&i.Laboratory,
			&i.ReportedAt,
			&i.Provider,
			&i.Model,
			&i.SchemaVersion,
			&i.PromptVersion,
			&i.ConfirmedBy,
			&i.ConfirmedAt,
			&i.RowIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportResults = `-- name: ListReportResults :many
SELECT r.id, r.user_id, r.report_id, r.source_row_id, r.analyte_id, r.original_label, r.value_text, r.value_numeric, r.comparator, r.unit_text, r.reference_range_text, r.ref_low, r.ref_high, r.abnormal_flag_printed, r.specimen_type, r.canonical_value, r.canonical_unit, r.conversion_factor, r.conversion_offset, r.catalog_version, r.collected_at, r.collected_date, r.page, r.evidence_text, r.revision, r.created_at, r.updated_at, a.code AS analyte_code FROM lab_results r LEFT JOIN analytes a ON a.id = r.analyte_id
WHERE r.report_id = $1 ORDER BY r.id
`

type ListReportResultsRow struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	ReportID            uuid.UUID
	SourceRowID         *int64
	AnalyteID           *int16
	OriginalLabel       string
	ValueText           string
	ValueNumeric        *float64
	Comparator          *string
	UnitText            *string
	ReferenceRangeText  *string
	RefLow              *float64
	RefHigh             *float64
	AbnormalFlagPrinted *string
	SpecimenType        *string
	CanonicalValue      *float64
	CanonicalUnit       *string
	ConversionFactor    *float64
	ConversionOffset    *float64
	CatalogVersion      *int32
	CollectedAt         *time.Time
	CollectedDate       time.Time
	Page                *int32
	EvidenceText        *string
	Revision            int32
	CreatedAt           time.Time
	UpdatedAt           time.Time
	AnalyteCode         *string
}

func (q *Queries) ListReportResults(ctx context.Context, reportID uuid.UUID) ([]ListReportResultsRow, error) {
	rows, err := q.db.Query(ctx, listReportResults, reportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReportResultsRow
	for rows.Next() {
		var i ListReportResultsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ReportID,
			&i.SourceRowID,
			&i.AnalyteID,
			&i.OriginalLabel,
			&i.ValueText,
			&i.ValueNumeric,
			&i.Comparator,
			&i.UnitText,
			&i.ReferenceRangeText,
			&i.RefLow,
			&i.RefHigh,
			&i.AbnormalFlagPrinted,
			&i.SpecimenType,
			&i.CanonicalValue,
			&i.CanonicalUnit,
			&i.ConversionFactor,
			&i.ConversionOffset,
			&i.CatalogVersion,
			&i.CollectedAt,
			&i.CollectedDate,
			&i.Page,
			&i.EvidenceText,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AnalyteCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewRows = `-- name: ListReviewRows :many
SELECT x.id, x.run_id, x.row_index, x.page, x.analyte_label, x.value_text, x.value_numeric, x.comparator, x.unit_text, x.reference_range_text, x.ref_low, x.ref_high, x.abnormal_flag_printed, x.specimen_type, x.collected_at, x.reported_at, x.laboratory, x.evidence_text, x.bbox, x.confidence, x.warnings, x.suggested_analyte_id, x.review_status, x.reviewed_at, a.code AS analyte_code, r.id AS result_id
FROM lab_extracted_rows x
LEFT JOIN analytes a ON a.id = x.suggested_analyte_id
LEFT JOIN lab_results r ON r.source_row_id = x.id
WHERE x.run_id = $1
ORDER BY x.row_index
`

type ListReviewRowsRow struct {
	ID                  int64
	RunID               uuid.UUID
	RowIndex            int32
	Page                *int32
	AnalyteLabel        string
	ValueText           *string
	ValueNumeric        *float64
	Comparator          *string
	UnitText            *string
	ReferenceRangeText  *string
	RefLow              *float64
	RefHigh             *float64
	AbnormalFlagPrinted *string
	SpecimenType        *string
	CollectedAt         *string
	ReportedAt          *string
	Laboratory          *string
	EvidenceText        *string
	Bbox                []byte
	Confidence          *float32
	Warnings            []string
	SuggestedAnalyteID  *int16
	ReviewStatus        string
	ReviewedAt          *time.Time
	AnalyteCode         *string
	ResultID            *uuid.UUID
}

// The rows of a run with the analyte code stored at review and the confirmed result, if any.
func (q *Queries) ListReviewRows(ctx context.Context, runID uuid.UUID) ([]ListReviewRowsRow, error) {
	rows, err := q.db.Query(ctx, listReviewRows, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewRowsRow
	for rows.Next() {
		var i ListReviewRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.RowIndex,
			&i.Page,
			&i.AnalyteLabel,
			&i.ValueText,
			&i.ValueNumeric,
			&i.Comparator,
			&i.UnitText,
			&i.ReferenceRangeText,
			&i.RefLow,
			&i.RefHigh,
			&i.AbnormalFlagPrinted,
			&i.SpecimenType,
			&i.CollectedAt,
			&i.ReportedAt,
			&i.Laboratory,
			&i.EvidenceText,
			&i.Bbox,
			&i.Confidence,
			&i.Warnings,
			&i.SuggestedAnalyteID,
			&i.ReviewStatus,
			&i.ReviewedAt,
			&i.AnalyteCode,
			&i.ResultID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunRowEdits = `-- name: ListRunRowEdits :many
SELECT e.id, e.row_id, e.action, e.changes, e.actor, e.created_at FROM extraction_row_edits e JOIN lab_extracted_rows x ON x.id = e.row_id
WHERE x.run_id = $1
ORDER BY e.id
`

func (q *Queries) ListRunRowEdits(ctx context.Context, runID uuid.UUID) ([]ExtractionRowEdit, error) {
	rows, err := q.db.Query(ctx, listRunRowEdits, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExtractionRowEdit
	for rows.Next() {
		var i ExtractionRowEdit
		if err := rows.Scan(
			&i.ID,
			&i.RowID,
			&i.Action,
			&i.Changes,
			&i.Actor,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockExtractedRow = `-- name: LockExtractedRow :one
SELECT x.id, x.run_id, x.row_index, x.page, x.analyte_label, x.value_text, x.value_numeric, x.comparator, x.unit_text, x.reference_range_text, x.ref_low, x.ref_high, x.abnormal_flag_printed, x.specimen_type, x.collected_at, x.reported_at, x.laboratory, x.evidence_text, x.bbox, x.confidence, x.warnings, x.suggested_analyte_id, x.review_status, x.reviewed_at, a.code AS analyte_code FROM lab_extracted_rows x LEFT JOIN analytes a ON a.id = x.suggested_analyte_id
WHERE x.run_id = $1 AND x.row_index = $2
FOR UPDATE OF x
`

type LockExtractedRowParams struct {
	RunID    uuid.UUID
	RowIndex int32
}

type LockExtractedRowRow struct {
	ID                  int64
	RunID               uuid.UUID
	RowIndex            int32
	Page                *int32
	AnalyteLabel        string
	ValueText           *string
	ValueNumeric        *float64
	Comparator          *string
	UnitText            *string
	ReferenceRangeText  *string
	RefLow              *float64
	RefHigh             *float64
	AbnormalFlagPrinted *string
	SpecimenType        *string
	CollectedAt         *string
	ReportedAt          *string
	Laboratory          *string
	EvidenceText        *string
	Bbox                []byte
	Confidence          *float32
	Warnings            []string
	SuggestedAnalyteID  *int16
	ReviewStatus        string
	ReviewedAt          *time.Time
	AnalyteCode         *string
}

func (q *Queries) LockExtractedRow(ctx context.Context, arg LockExtractedRowParams) (LockExtractedRowRow, error) {
	row := q.db.QueryRow(ctx, lockExtractedRow, arg.RunID, arg.RowIndex)
	var i LockExtractedRowRow
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.RowIndex,
		&i.Page,
		&i.AnalyteLabel,
		&i.ValueText,
		&i.ValueNumeric,
		&i.Comparator,
		&i.UnitText,
		&i.ReferenceRangeText,
		&i.RefLow,
		&i.RefHigh,
		&i.AbnormalFlagPrinted,
		&i.SpecimenType,
		&i.CollectedAt,
		&i.ReportedAt,
		&i.Laboratory,
		&i.EvidenceText,
		&i.Bbox,
		&i.Confidence,
		&i.Warnings,
		&i.SuggestedAnalyteID,
		&i.ReviewStatus,
		&i.ReviewedAt,
		&i.AnalyteCode,
	)
	return i, err
}

const reviewExtractedRow = `-- name: ReviewExtractedRow :exec
UPDATE lab_extracted_rows
SET analyte_label = $1, value_text = $2, value_numeric = $3,
    comparator = $4, unit_text = $5, reference_range_text = $6,
    ref_low = $7, ref_high = $8, abnormal_flag_printed = $9,
    specimen_type = $10, collected_at = $11, reported_at = $12,
    laboratory = $13,
    suggested_analyte_id = (SELECT an.id FROM analytes an WHERE an.code = $14::text),
    review_status = $15, reviewed_at = now()
WHERE lab_extracted_rows.id = $16
`

type ReviewExtractedRowParams struct {
	AnalyteLabel        string
	ValueText           *string
	ValueNumeric        *float64
	Comparator          *string
	UnitText            *string
	ReferenceRangeText  *string
	RefLow              *float64
	RefHigh             *float64
	AbnormalFlagPrinted *string
	SpecimenType        *string
	CollectedAt         *string
	ReportedAt          *string
	Laboratory          *string
	Analyte             *string
	ReviewStatus        string
	ID                  int64
}

// Writes the reviewed values; suggested_analyte_id becomes the analyte the owner reviewed.
func (q *Queries) ReviewExtractedRow(ctx context.Context, arg ReviewExtractedRowParams) error {
	_, err := q.db.Exec(ctx, reviewExtractedRow,
		arg.AnalyteLabel,
		arg.ValueText,
		arg.ValueNumeric,
		arg.Comparator,
		arg.UnitText,
		arg.ReferenceRangeText,
		arg.RefLow,
		arg.RefHigh,
		arg.AbnormalFlagPrinted,
		arg.SpecimenType,
		arg.CollectedAt,
		arg.ReportedAt,
		arg.Laboratory,
		arg.Analyte,
		arg.ReviewStatus,
		arg.ID,
	)
	return err
}

const reviseLabResult = `-- name: ReviseLabResult :exec
UPDATE lab_results
SET analyte_id = $1, original_label = $2, value_text = $3, value_numeric = $4,
    comparator = $5, unit_text = $6, reference_range_text = $7,
    ref_low = $8, ref_high = $9, abnormal_flag_printed = $10,
    specimen_type = $11, canonical_value = $12, canonical_unit = $13,
    conversion_factor = $14, conversion_offset = $15,
    catalog_version = $16, collected_at = $17, collected_date = $18,
    page = $19, evidence_text = $20, revision = revision + 1, updated_at = now()
WHERE id = $21
`

type ReviseLabResultParams struct {
	AnalyteID           *int16
	OriginalLabel       string
	ValueText           string
	ValueNumeric        *float64
	Comparator          *string
	UnitText            *string
	ReferenceRangeText  *string
	RefLow              *float64
	RefHigh             *float64
	AbnormalFlagPrinted *string
	SpecimenType        *string
	CanonicalValue      *float64
	CanonicalUnit       *string
	ConversionFactor    *float64
	ConversionOffset    *float64
	CatalogVersion      *int32
	CollectedAt         *time.Time
	CollectedDate       time.Time
	Page                *int32
	EvidenceText        *string
	ID                  uuid.UUID
}

// The caller stored the previous values in lab_result_revisions first.
func (q *Queries) ReviseLabResult(ctx context.Context, arg ReviseLabResultParams) error {
	_, err := q.db.Exec(ctx, reviseLabResult,
		arg.AnalyteID,
		arg.OriginalLabel,
		arg.ValueText,
		arg.ValueNumeric,
		arg.Comparator,
		arg.UnitText,
		arg.ReferenceRangeText,
		arg.RefLow,
		arg.RefHigh,
		arg.AbnormalFlagPrinted,
		arg.SpecimenType,
		arg.CanonicalValue,
		arg.CanonicalUnit,
		arg.ConversionFactor,
		arg.ConversionOffset,
		arg.CatalogVersion,
		arg.CollectedAt,
		arg.CollectedDate,
		arg.Page,
		arg.EvidenceText,
		arg.ID,
	)
	return err
}

const setExtractionRunStatus = `-- name: SetExtractionRunStatus :exec
UPDATE extraction_runs SET status = $1 WHERE id = $2
`

type SetExtractionRunStatusParams struct {
	Status string
	ID     uuid.UUID
}

func (q *Queries) SetExtractionRunStatus(ctx context.Context, arg SetExtractionRunStatusParams) error {
	_, err := q.db.Exec(ctx, setExtractionRunStatus, arg.Status, arg.ID)
	return err
}

const setLiveDocumentStatus = `-- name: SetLiveDocumentStatus :exec
UPDATE documents SET status = $1 WHERE id = $2 AND status <> 'deleted'
`

type SetLiveDocumentStatusParams struct {
	Status string
	ID     uuid.UUID
}

// Confirmation moves a live document to confirmed and back to needs_review.
func (q *Queries) SetLiveDocumentStatus(ctx context.Context, arg SetLiveDocumentStatusParams) error {
	_, err := q.db.Exec(ctx, setLiveDocumentStatus, arg.Status, arg.ID)
	return err
}
