// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rules.sql

package dbq

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getRuleVersion = `-- name: GetRuleVersion :one
SELECT id, user_id, metric, version, spec, based_on, note, created_by, created_at FROM resolution_rules WHERE user_id = $1 AND metric = $2 AND version = $3
`

type GetRuleVersionParams struct {
	UserID  uuid.UUID
	Metric  string
	Version int32
}

func (q *Queries) GetRuleVersion(ctx context.Context, arg GetRuleVersionParams) (ResolutionRule, error) {
	row := q.db.QueryRow(ctx, getRuleVersion, arg.UserID, arg.Metric, arg.Version)
	var i ResolutionRule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Metric,
		&i.Version,
		&i.Spec,
		&i.BasedOn,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertRuleVersion = `-- name: InsertRuleVersion :one
INSERT INTO resolution_rules (id, user_id, metric, version, spec, based_on, note, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, metric, version, spec, based_on, note, created_by, created_at
`

type InsertRuleVersionParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Metric    string
	Version   int32
	Spec      json.RawMessage
	BasedOn   *string
	Note      *string
	CreatedBy string
}

func (q *Queries) InsertRuleVersion(ctx context.Context, arg InsertRuleVersionParams) (ResolutionRule, error) {
	row := q.db.QueryRow(ctx, insertRuleVersion,
		arg.ID,
		arg.UserID,
		arg.Metric,
		arg.Version,
		arg.Spec,
		arg.BasedOn,
		arg.Note,
		arg.CreatedBy,
	)
	var i ResolutionRule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Metric,
		&i.Version,
		&i.Spec,
		&i.BasedOn,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const latestRuleVersion = `-- name: LatestRuleVersion :one

SELECT coalesce(max(version), 0)::integer AS version
FROM resolution_rules WHERE user_id = $1 AND metric = $2
`

type LatestRuleVersionParams struct {
	UserID uuid.UUID
	Metric string
}

// Resolution rule versions (J09.2). Rows of resolution_rules are never updated.
func (q *Queries) LatestRuleVersion(ctx context.Context, arg LatestRuleVersionParams) (int32, error) {
	row := q.db.QueryRow(ctx, latestRuleVersion, arg.UserID, arg.Metric)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const listActiveRules = `-- name: ListActiveRules :many
SELECT r.id, r.user_id, r.metric, r.version, r.spec, r.based_on, r.note, r.created_by, r.created_at FROM active_rules a
JOIN resolution_rules r ON r.user_id = a.user_id AND r.metric = a.metric AND r.version = a.version
WHERE a.user_id = $1
ORDER BY r.metric
`

func (q *Queries) ListActiveRules(ctx context.Context, userID uuid.UUID) ([]ResolutionRule, error) {
	rows, err := q.db.Query(ctx, listActiveRules, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResolutionRule
	for rows.Next() {
		var i ResolutionRule
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Metric,
			&i.Version,
			&i.Spec,
			&i.BasedOn,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuleVersions = `-- name: ListRuleVersions :many
SELECT r.id, r.user_id, r.metric, r.version, r.spec, r.based_on, r.note, r.created_by, r.created_at, (a.version IS NOT NULL)::boolean AS active
FROM resolution_rules r
LEFT JOIN active_rules a ON a.user_id = r.user_id AND a.metric = r.metric AND a.version = r.version
WHERE r.user_id = $1 AND r.metric = $2
ORDER BY r.version DESC
`

type ListRuleVersionsParams struct {
	UserID uuid.UUID
	Metric string
}

type ListRuleVersionsRow struct {
	ResolutionRule ResolutionRule
	Active         bool
}

func (q *Queries) ListRuleVersions(ctx context.Context, arg ListRuleVersionsParams) ([]ListRuleVersionsRow, error) {
	rows, err := q.db.Query(ctx, listRuleVersions, arg.UserID, arg.Metric)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRuleVersionsRow
	for rows.Next() {
		var i ListRuleVersionsRow
		if err := rows.Scan(
			&i.ResolutionRule.ID,
			&i.ResolutionRule.UserID,
			&i.ResolutionRule.Metric,
			&i.ResolutionRule.Version,
			&i.ResolutionRule.Spec,
			&i.ResolutionRule.BasedOn,
			&i.ResolutionRule.Note,
			&i.ResolutionRule.CreatedBy,
			&i.ResolutionRule.CreatedAt,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setActiveRule = `-- name: SetActiveRule :exec
INSERT INTO active_rules (user_id, metric, version, activated_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, metric) DO UPDATE
SET version = EXCLUDED.version, activated_by = EXCLUDED.activated_by, activated_at = now()
`

type SetActiveRuleParams struct {
	UserID      uuid.UUID
	Metric      string
	Version     int32
	ActivatedBy string
}

func (q *Queries) SetActiveRule(ctx context.Context, arg SetActiveRuleParams) error {
	_, err := q.db.Exec(ctx, setActiveRule,
		arg.UserID,
		arg.Metric,
		arg.Version,
		arg.ActivatedBy,
	)
	return err
}
