// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedules.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const advanceSchedule = `-- name: AdvanceSchedule :exec
UPDATE schedules SET next_run_at = $1 WHERE id = $2
`

type AdvanceScheduleParams struct {
	NextRunAt time.Time
	ID        uuid.UUID
}

func (q *Queries) AdvanceSchedule(ctx context.Context, arg AdvanceScheduleParams) error {
	_, err := q.db.Exec(ctx, advanceSchedule, arg.NextRunAt, arg.ID)
	return err
}

const getSchedule = `-- name: GetSchedule :one
SELECT id, connection_id, stream, run_interval, lookback, next_run_at, enabled, mode FROM schedules WHERE id = $1
`

func (q *Queries) GetSchedule(ctx context.Context, id uuid.UUID) (Schedule, error) {
	row := q.db.QueryRow(ctx, getSchedule, id)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.Stream,
		&i.RunInterval,
		&i.Lookback,
		&i.NextRunAt,
		&i.Enabled,
		&i.Mode,
	)
	return i, err
}

const getScheduleByStream = `-- name: GetScheduleByStream :one
SELECT id, connection_id, stream, run_interval, lookback, next_run_at, enabled, mode FROM schedules WHERE connection_id = $1 AND stream = $2 AND mode = $3
`

type GetScheduleByStreamParams struct {
	ConnectionID uuid.UUID
	Stream       string
	Mode         string
}

func (q *Queries) GetScheduleByStream(ctx context.Context, arg GetScheduleByStreamParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, getScheduleByStream, arg.ConnectionID, arg.Stream, arg.Mode)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.Stream,
		&i.RunInterval,
		&i.Lookback,
		&i.NextRunAt,
		&i.Enabled,
		&i.Mode,
	)
	return i, err
}

const insertSchedule = `-- name: InsertSchedule :one

INSERT INTO schedules (id, connection_id, stream, mode, run_interval, lookback, next_run_at)
VALUES ($1, $2, $3, $4, $5, $6, now() + $5)
ON CONFLICT (connection_id, stream, mode) DO NOTHING
RETURNING id, connection_id, stream, run_interval, lookback, next_run_at, enabled, mode
`

type InsertScheduleParams struct {
	ID           uuid.UUID
	ConnectionID uuid.UUID
	Stream       string
	Mode         string
	RunInterval  time.Duration
	Lookback     time.Duration
}

// Schedules (J06.3); see docs/architecture/reliability.md#scheduler.
func (q *Queries) InsertSchedule(ctx context.Context, arg InsertScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, insertSchedule,
		arg.ID,
		arg.ConnectionID,
		arg.Stream,
		arg.Mode,
		arg.RunInterval,
		arg.Lookback,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.Stream,
		&i.RunInterval,
		&i.Lookback,
		&i.NextRunAt,
		&i.Enabled,
		&i.Mode,
	)
	return i, err
}

const listSchedules = `-- name: ListSchedules :many
SELECT id, connection_id, stream, run_interval, lookback, next_run_at, enabled, mode FROM schedules
WHERE $1::uuid IS NULL OR connection_id = $1
ORDER BY connection_id, stream, mode
`

func (q *Queries) ListSchedules(ctx context.Context, connectionID *uuid.UUID) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, listSchedules, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schedule
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.Stream,
			&i.RunInterval,
			&i.Lookback,
			&i.NextRunAt,
			&i.Enabled,
			&i.Mode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDueSchedules = `-- name: LockDueSchedules :many
SELECT s.id, s.connection_id, s.stream, s.run_interval, s.lookback, s.next_run_at, s.enabled, s.mode FROM schedules s JOIN connections c ON c.id = s.connection_id
WHERE s.enabled AND s.next_run_at <= $1 AND c.status IN ('active', 'degraded')
ORDER BY s.next_run_at
LIMIT $2
FOR UPDATE OF s SKIP LOCKED
`

type LockDueSchedulesParams struct {
	Now     time.Time
	MaxRows int32
}

// Schedules of paused, needs_reauth, error or disabled connections wait until it is active again.
func (q *Queries) LockDueSchedules(ctx context.Context, arg LockDueSchedulesParams) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, lockDueSchedules, arg.Now, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schedule
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.Stream,
			&i.RunInterval,
			&i.Lookback,
			&i.NextRunAt,
			&i.Enabled,
			&i.Mode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSchedule = `-- name: UpdateSchedule :one
UPDATE schedules SET run_interval = $1, lookback = $2, enabled = $3,
       next_run_at = CASE WHEN run_interval = $1 THEN next_run_at
                          ELSE least(next_run_at, now() + $1) END
WHERE id = $4
RETURNING id, connection_id, stream, run_interval, lookback, next_run_at, enabled, mode
`

type UpdateScheduleParams struct {
	RunInterval time.Duration
	Lookback    time.Duration
	Enabled     bool
	ID          uuid.UUID
}

// A changed interval may only bring the next run closer, never push it out by a full old interval.
func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, updateSchedule,
		arg.RunInterval,
		arg.Lookback,
		arg.Enabled,
		arg.ID,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.Stream,
		&i.RunInterval,
		&i.Lookback,
		&i.NextRunAt,
		&i.Enabled,
		&i.Mode,
	)
	return i, err
}
