// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedules.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const advanceSchedule = `-- name: AdvanceSchedule :exec
UPDATE schedules SET next_run_at = $1 WHERE id = $2
`

type AdvanceScheduleParams struct {
	NextRunAt time.Time
	ID        uuid.UUID
}

func (q *Queries) AdvanceSchedule(ctx context.Context, arg AdvanceScheduleParams) error {
	_, err := q.db.Exec(ctx, advanceSchedule, arg.NextRunAt, arg.ID)
	return err
}

const getSchedule = `-- name: GetSchedule :one
SELECT id, connection_id, stream, run_interval, lookback, next_run_at, enabled, mode FROM schedules WHERE id = $1
`

func (q *Queries) GetSchedule(ctx context.Context, id uuid.UUID) (Schedule, error) {
	row := q.db.QueryRow(ctx, getSchedule, id)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.Stream,
		&i.RunInterval,
		&i.Lookback,
		&i.NextRunAt,
		&i.Enabled,
		&i.Mode,
	)
	return i, err
}

const getScheduleByStream = `-- name: GetScheduleByStream :one
SELECT id, connection_id, stream, run_interval, lookback, next_run_at, enabled, mode FROM schedules WHERE connection_id = $1 AND stream = $2 AND mode = $3
`

type GetScheduleByStreamParams struct {
	ConnectionID uuid.UUID
	Stream       string
	Mode         string
}

func (q *Queries) GetScheduleByStream(ctx context.Context, arg GetScheduleByStreamParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, getScheduleByStream, arg.ConnectionID, arg.Stream, arg.Mode)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.Stream,
		&i.RunInterval,
		&i.Lookback,
		&i.NextRunAt,
		&i.Enabled,
		&i.Mode,
	)
	return i, err
}

const insertSchedule = `-- name: InsertSchedule :one

INSERT INTO schedules (id, connection_id, stream, mode, run_interval, lookback, next_run_at)
VALUES ($1, $2, $3, $4, $5, $6, now() + $5)
ON CONFLICT (connection_id, stream, mode) DO NOTHING
RETURNING id, connection_id, stream, run_interval, lookback, next_run_at, enabled, mode
`

type InsertScheduleParams struct {
	ID           uuid.UUID
	ConnectionID uuid.UUID
	Stream       string
	Mode         string
	RunInterval  time.Duration
	Lookback     time.Duration
}

// Schedules (J06.3); see docs/architecture/reliability.md#scheduler.
func (q *Queries) InsertSchedule(ctx context.Context, arg InsertScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, insertSchedule,
		arg.ID,
		arg.ConnectionID,
		arg.Stream,
		arg.Mode,
		arg.RunInterval,
		arg.Lookback,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.Stream,
		&i.RunInterval,
		&i.Lookback,
		&i.NextRunAt,
		&i.Enabled,
		&i.Mode,
	)
	return i, err
}

const listProviderConnections = `-- name: ListProviderConnections :many
SELECT c.id FROM connections c JOIN providers p ON p.id = c.provider_id WHERE p.code = $1
`

func (q *Queries) ListProviderConnections(ctx context.Context, provider string) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listProviderConnections, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedules = `-- name: ListSchedules :many
SELECT id, connection_id, stream, run_interval, lookback, next_run_at, enabled, mode FROM schedules
WHERE $1::uuid IS NULL OR connection_id = $1
ORDER BY connection_id, stream, mode
`

func (q *Queries) ListSchedules(ctx context.Context, connectionID *uuid.UUID) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, listSchedules, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schedule
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.Stream,
			&i.RunInterval,
			&i.Lookback,
			&i.NextRunAt,
			&i.Enabled,
			&i.Mode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsedStreams = `-- name: ListUsedStreams :many
SELECT sc.stream FROM schedules sc WHERE sc.connection_id = $1
UNION
SELECT cu.stream FROM sync_cursors cu WHERE cu.connection_id = $1
`

// Streams a connection still has schedules or cursors for.
func (q *Queries) ListUsedStreams(ctx context.Context, connectionID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listUsedStreams, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var stream string
		if err := rows.Scan(&stream); err != nil {
			return nil, err
		}
		items = append(items, stream)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDueSchedules = `-- name: LockDueSchedules :many
SELECT s.id, s.connection_id, s.stream, s.run_interval, s.lookback, s.next_run_at, s.enabled, s.mode FROM schedules s JOIN connections c ON c.id = s.connection_id
WHERE s.enabled AND s.next_run_at <= $1 AND c.status IN ('active', 'degraded')
ORDER BY s.next_run_at
LIMIT $2
FOR UPDATE OF s SKIP LOCKED
`

type LockDueSchedulesParams struct {
	Now     time.Time
	MaxRows int32
}

// Schedules of paused, needs_reauth, error or disabled connections wait until it is active again.
func (q *Queries) LockDueSchedules(ctx context.Context, arg LockDueSchedulesParams) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, lockDueSchedules, arg.Now, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schedule
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.Stream,
			&i.RunInterval,
			&i.Lookback,
			&i.NextRunAt,
			&i.Enabled,
			&i.Mode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retireStream = `-- name: RetireStream :exec
WITH sched AS (
  UPDATE schedules SET enabled = false WHERE connection_id = $1 AND stream = $2
), cur AS (
  UPDATE sync_cursors SET status = 'ok', status_reason = NULL, updated_at = now()
  WHERE connection_id = $1 AND stream = $2
)
UPDATE connections
SET status = CASE WHEN EXISTS (SELECT 1 FROM sync_cursors s WHERE s.connection_id = $1
                                 AND s.stream <> $2 AND s.status = 'degraded'
                                 AND (EXISTS (SELECT 1 FROM schedules x WHERE x.connection_id = s.connection_id
                                              AND x.stream = s.stream AND x.enabled)
                                      OR NOT EXISTS (SELECT 1 FROM schedules x WHERE x.connection_id = s.connection_id
                                                     AND x.stream = s.stream)))
                  THEN 'degraded' ELSE 'active' END,
    updated_at = now()
WHERE id = $1 AND status IN ('active', 'degraded')
`

type RetireStreamParams struct {
	ConnectionID uuid.UUID
	Stream       string
}

// A stream its connector no longer declares: stop its schedules, clear its degraded mark, and
// leave the connection degraded only while another stream still is (CTEs see the old rows). A
// degraded stream whose schedules are all disabled does not count.
func (q *Queries) RetireStream(ctx context.Context, arg RetireStreamParams) error {
	_, err := q.db.Exec(ctx, retireStream, arg.ConnectionID, arg.Stream)
	return err
}

const updateSchedule = `-- name: UpdateSchedule :one
UPDATE schedules SET run_interval = $1, lookback = $2, enabled = $3,
       next_run_at = CASE WHEN run_interval = $1 THEN next_run_at
                          ELSE least(next_run_at, now() + $1) END
WHERE id = $4
RETURNING id, connection_id, stream, run_interval, lookback, next_run_at, enabled, mode
`

type UpdateScheduleParams struct {
	RunInterval time.Duration
	Lookback    time.Duration
	Enabled     bool
	ID          uuid.UUID
}

// A changed interval may only bring the next run closer, never push it out by a full old interval.
func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, updateSchedule,
		arg.RunInterval,
		arg.Lookback,
		arg.Enabled,
		arg.ID,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.Stream,
		&i.RunInterval,
		&i.Lookback,
		&i.NextRunAt,
		&i.Enabled,
		&i.Mode,
	)
	return i, err
}
