// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: setup.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countAuthorizedConnections = `-- name: CountAuthorizedConnections :one
SELECT count(*)::int FROM connections c
JOIN providers p ON p.id = c.provider_id
JOIN credentials cr ON cr.connection_id = c.id
WHERE p.code = $1
`

// Connections of a provider that hold tokens, which refresh with the provider's app credentials.
func (q *Queries) CountAuthorizedConnections(ctx context.Context, provider string) (int32, error) {
	row := q.db.QueryRow(ctx, countAuthorizedConnections, provider)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countProviderConnections = `-- name: CountProviderConnections :one
SELECT count(*)::int FROM connections c JOIN providers p ON p.id = c.provider_id WHERE p.code = $1
`

// Every connection of a provider, whatever its status (a removed sidecar strands them).
func (q *Queries) CountProviderConnections(ctx context.Context, provider string) (int32, error) {
	row := q.db.QueryRow(ctx, countProviderConnections, provider)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteProviderApp = `-- name: DeleteProviderApp :execrows
DELETE FROM provider_app_credentials WHERE provider = $1
`

func (q *Queries) DeleteProviderApp(ctx context.Context, provider string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProviderApp, provider)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSidecar = `-- name: DeleteSidecar :execrows
DELETE FROM sidecars WHERE name = $1
`

func (q *Queries) DeleteSidecar(ctx context.Context, name string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSidecar, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProviderApp = `-- name: GetProviderApp :one

SELECT client_id, ciphertext, updated_at FROM provider_app_credentials WHERE provider = $1
`

type GetProviderAppRow struct {
	ClientID   string
	Ciphertext []byte
	UpdatedAt  time.Time
}

// Source setup in the web panel (E20, ADR-0021): provider app credentials and panel sidecars.
func (q *Queries) GetProviderApp(ctx context.Context, provider string) (GetProviderAppRow, error) {
	row := q.db.QueryRow(ctx, getProviderApp, provider)
	var i GetProviderAppRow
	err := row.Scan(&i.ClientID, &i.Ciphertext, &i.UpdatedAt)
	return i, err
}

const insertSidecar = `-- name: InsertSidecar :execrows
INSERT INTO sidecars (name, url, ciphertext, key_id, created_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (name) DO NOTHING
`

type InsertSidecarParams struct {
	Name       string
	Url        string
	Ciphertext []byte
	KeyID      string
	CreatedBy  *uuid.UUID
}

func (q *Queries) InsertSidecar(ctx context.Context, arg InsertSidecarParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertSidecar,
		arg.Name,
		arg.Url,
		arg.Ciphertext,
		arg.KeyID,
		arg.CreatedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listSidecars = `-- name: ListSidecars :many
SELECT name, url, ciphertext, created_at FROM sidecars ORDER BY name
`

type ListSidecarsRow struct {
	Name       string
	Url        string
	Ciphertext []byte
	CreatedAt  time.Time
}

func (q *Queries) ListSidecars(ctx context.Context) ([]ListSidecarsRow, error) {
	rows, err := q.db.Query(ctx, listSidecars)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSidecarsRow
	for rows.Next() {
		var i ListSidecarsRow
		if err := rows.Scan(
			&i.Name,
			&i.Url,
			&i.Ciphertext,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProviderAppsToRotate = `-- name: LockProviderAppsToRotate :many
SELECT provider, ciphertext FROM provider_app_credentials
WHERE key_id <> $1 ORDER BY provider LIMIT $2 FOR UPDATE SKIP LOCKED
`

type LockProviderAppsToRotateParams struct {
	KeyID string
	Batch int32
}

type LockProviderAppsToRotateRow struct {
	Provider   string
	Ciphertext []byte
}

func (q *Queries) LockProviderAppsToRotate(ctx context.Context, arg LockProviderAppsToRotateParams) ([]LockProviderAppsToRotateRow, error) {
	rows, err := q.db.Query(ctx, lockProviderAppsToRotate, arg.KeyID, arg.Batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockProviderAppsToRotateRow
	for rows.Next() {
		var i LockProviderAppsToRotateRow
		if err := rows.Scan(&i.Provider, &i.Ciphertext); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSidecarsToRotate = `-- name: LockSidecarsToRotate :many
SELECT name, ciphertext FROM sidecars
WHERE key_id <> $1 ORDER BY name LIMIT $2 FOR UPDATE SKIP LOCKED
`

type LockSidecarsToRotateParams struct {
	KeyID string
	Batch int32
}

type LockSidecarsToRotateRow struct {
	Name       string
	Ciphertext []byte
}

func (q *Queries) LockSidecarsToRotate(ctx context.Context, arg LockSidecarsToRotateParams) ([]LockSidecarsToRotateRow, error) {
	rows, err := q.db.Query(ctx, lockSidecarsToRotate, arg.KeyID, arg.Batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockSidecarsToRotateRow
	for rows.Next() {
		var i LockSidecarsToRotateRow
		if err := rows.Scan(&i.Name, &i.Ciphertext); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const providerConnectionCounts = `-- name: ProviderConnectionCounts :many
SELECT p.code AS provider, count(*)::int AS connections
FROM connections c JOIN providers p ON p.id = c.provider_id
WHERE c.user_id = $1 AND c.status <> 'disabled'
GROUP BY p.code
`

type ProviderConnectionCountsRow struct {
	Provider    string
	Connections int32
}

// The user's connections per provider that are not disconnected.
func (q *Queries) ProviderConnectionCounts(ctx context.Context, userID uuid.UUID) ([]ProviderConnectionCountsRow, error) {
	rows, err := q.db.Query(ctx, providerConnectionCounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderConnectionCountsRow
	for rows.Next() {
		var i ProviderConnectionCountsRow
		if err := rows.Scan(&i.Provider, &i.Connections); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resealProviderApp = `-- name: ResealProviderApp :exec
UPDATE provider_app_credentials SET ciphertext = $1, key_id = $2 WHERE provider = $3
`

type ResealProviderAppParams struct {
	Ciphertext []byte
	KeyID      string
	Provider   string
}

func (q *Queries) ResealProviderApp(ctx context.Context, arg ResealProviderAppParams) error {
	_, err := q.db.Exec(ctx, resealProviderApp, arg.Ciphertext, arg.KeyID, arg.Provider)
	return err
}

const resealSidecar = `-- name: ResealSidecar :exec
UPDATE sidecars SET ciphertext = $1, key_id = $2 WHERE name = $3
`

type ResealSidecarParams struct {
	Ciphertext []byte
	KeyID      string
	Name       string
}

func (q *Queries) ResealSidecar(ctx context.Context, arg ResealSidecarParams) error {
	_, err := q.db.Exec(ctx, resealSidecar, arg.Ciphertext, arg.KeyID, arg.Name)
	return err
}

const upsertProviderApp = `-- name: UpsertProviderApp :one
INSERT INTO provider_app_credentials (provider, client_id, ciphertext, key_id, updated_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (provider) DO UPDATE
SET client_id = excluded.client_id, ciphertext = excluded.ciphertext, key_id = excluded.key_id,
    updated_at = now(), updated_by = excluded.updated_by
RETURNING (xmax <> 0)::boolean AS replaced
`

type UpsertProviderAppParams struct {
	Provider   string
	ClientID   string
	Ciphertext []byte
	KeyID      string
	UpdatedBy  *uuid.UUID
}

// Returns whether a stored value was replaced.
func (q *Queries) UpsertProviderApp(ctx context.Context, arg UpsertProviderAppParams) (bool, error) {
	row := q.db.QueryRow(ctx, upsertProviderApp,
		arg.Provider,
		arg.ClientID,
		arg.Ciphertext,
		arg.KeyID,
		arg.UpdatedBy,
	)
	var replaced bool
	err := row.Scan(&replaced)
	return replaced, err
}
