// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sourcefilter.sql

package dbq

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const deleteIgnoredRecords = `-- name: DeleteIgnoredRecords :exec
DELETE FROM ignored_records WHERE raw_payload_id = $1
`

func (q *Queries) DeleteIgnoredRecords(ctx context.Context, rawPayloadID int64) error {
	_, err := q.db.Exec(ctx, deleteIgnoredRecords, rawPayloadID)
	return err
}

const getDeviceSourceFilter = `-- name: GetDeviceSourceFilter :one

SELECT cl.id, cl.user_id, cl.revoked_at, cl.source_filter, cl.source_filter_version, cl.health_sources, cl.health_sources_at
FROM clients cl
WHERE cl.id = $1 AND cl.user_id = $2 AND cl.kind = 'device'
`

type GetDeviceSourceFilterParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetDeviceSourceFilterRow struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	RevokedAt           *time.Time
	SourceFilter        json.RawMessage
	SourceFilterVersion int32
	HealthSources       json.RawMessage
	HealthSourcesAt     *time.Time
}

// Apple Health source filter (J22.25; docs/architecture/apple-health.md#source-filter).
func (q *Queries) GetDeviceSourceFilter(ctx context.Context, arg GetDeviceSourceFilterParams) (GetDeviceSourceFilterRow, error) {
	row := q.db.QueryRow(ctx, getDeviceSourceFilter, arg.ID, arg.UserID)
	var i GetDeviceSourceFilterRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RevokedAt,
		&i.SourceFilter,
		&i.SourceFilterVersion,
		&i.HealthSources,
		&i.HealthSourcesAt,
	)
	return i, err
}

const getRawDeviceFilter = `-- name: GetRawDeviceFilter :one
SELECT cl.id, cl.user_id, cl.source_filter, cl.source_filter_version
FROM raw_payloads r
JOIN ingest_batches b ON b.id = r.batch_id
JOIN clients cl ON cl.id = b.client_id
WHERE r.id = $1 AND cl.kind = 'device'
`

type GetRawDeviceFilterRow struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	SourceFilter        json.RawMessage
	SourceFilterVersion int32
}

// The source filter of the paired device that pushed a raw payload; no row for other senders.
func (q *Queries) GetRawDeviceFilter(ctx context.Context, id int64) (GetRawDeviceFilterRow, error) {
	row := q.db.QueryRow(ctx, getRawDeviceFilter, id)
	var i GetRawDeviceFilterRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceFilter,
		&i.SourceFilterVersion,
	)
	return i, err
}

const insertIgnoredRecords = `-- name: InsertIgnoredRecords :exec
INSERT INTO ignored_records (raw_payload_id, origin_id, user_id, item_kind, item_code, records, first_at, last_at)
SELECT r.id, o.id, r.user_id, x.item_kind, x.item_code, x.records, x.first_at, x.last_at
FROM raw_payloads r
JOIN connections c ON c.id = r.connection_id
CROSS JOIN (SELECT unnest($1::text[]) AS origin_key, unnest($2::text[]) AS item_kind,
  unnest($3::text[]) AS item_code, unnest($4::integer[]) AS records,
  unnest($5::timestamptz[]) AS first_at, unnest($6::timestamptz[]) AS last_at) AS x
JOIN data_origins o ON o.user_id = r.user_id AND o.provider_id = c.provider_id AND o.origin_key = x.origin_key
WHERE r.id = $7
`

type InsertIgnoredRecordsParams struct {
	OriginKeys   []string
	ItemKinds    []string
	ItemCodes    []string
	Records      []int32
	FirstAts     []time.Time
	LastAts      []time.Time
	RawPayloadID int64
}

// One row per origin and item; origins are the payload's provider's, written by the same normalization.
func (q *Queries) InsertIgnoredRecords(ctx context.Context, arg InsertIgnoredRecordsParams) error {
	_, err := q.db.Exec(ctx, insertIgnoredRecords,
		arg.OriginKeys,
		arg.ItemKinds,
		arg.ItemCodes,
		arg.Records,
		arg.FirstAts,
		arg.LastAts,
		arg.RawPayloadID,
	)
	return err
}

const listAppleOrigins = `-- name: ListAppleOrigins :many
SELECT o.id, o.origin_key, o.name, o.is_native, rp.code AS relayed_provider,
  coalesce((SELECT sum(i.records) FROM ignored_records i WHERE i.origin_id = o.id), 0)::bigint AS ignored_records
FROM data_origins o
JOIN providers p ON p.id = o.provider_id AND p.code = 'apple_health'
LEFT JOIN providers rp ON rp.id = o.relayed_provider_id
WHERE o.user_id = $1
ORDER BY o.origin_key
`

type ListAppleOriginsRow struct {
	ID              uuid.UUID
	OriginKey       string
	Name            *string
	IsNative        bool
	RelayedProvider *string
	IgnoredRecords  int64
}

// The owner's Apple Health origins with their classification and the records held raw because a
// filter ignored them.
func (q *Queries) ListAppleOrigins(ctx context.Context, userID uuid.UUID) ([]ListAppleOriginsRow, error) {
	rows, err := q.db.Query(ctx, listAppleOrigins, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAppleOriginsRow
	for rows.Next() {
		var i ListAppleOriginsRow
		if err := rows.Scan(
			&i.ID,
			&i.OriginKey,
			&i.Name,
			&i.IsNative,
			&i.RelayedProvider,
			&i.IgnoredRecords,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppleRelayPatterns = `-- name: ListAppleRelayPatterns :many
SELECT k.origin_pattern, p.code AS provider
FROM known_relay_origins k
JOIN providers t ON t.id = k.provider_id AND t.code = 'apple_health'
JOIN providers p ON p.id = k.relayed_provider_id
ORDER BY 1
`

type ListAppleRelayPatternsRow struct {
	OriginPattern string
	Provider      string
}

// Every known Apple Health relay origin, connected directly or not, to classify apps not seen yet.
func (q *Queries) ListAppleRelayPatterns(ctx context.Context) ([]ListAppleRelayPatternsRow, error) {
	rows, err := q.db.Query(ctx, listAppleRelayPatterns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAppleRelayPatternsRow
	for rows.Next() {
		var i ListAppleRelayPatternsRow
		if err := rows.Scan(&i.OriginPattern, &i.Provider); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIgnoredForMetric = `-- name: ListIgnoredForMetric :many
SELECT o.origin_key, o.name AS origin_name, sum(i.records)::bigint AS records,
  min(i.first_at)::timestamptz AS first_at, max(i.last_at)::timestamptz AS last_at
FROM ignored_records i JOIN data_origins o ON o.id = i.origin_id
WHERE i.user_id = $1 AND i.item_kind = 'metric' AND i.item_code = $2
  AND i.last_at >= $3::timestamptz AND i.first_at < $4::timestamptz
GROUP BY 1, 2
ORDER BY 1
`

type ListIgnoredForMetricParams struct {
	UserID uuid.UUID
	Metric string
	Start  time.Time
	EndAt  time.Time
}

type ListIgnoredForMetricRow struct {
	OriginKey  string
	OriginName *string
	Records    int64
	FirstAt    time.Time
	LastAt     time.Time
}

// The all-sources view's "ignored sources": records of a metric held raw in [start, end), per origin.
func (q *Queries) ListIgnoredForMetric(ctx context.Context, arg ListIgnoredForMetricParams) ([]ListIgnoredForMetricRow, error) {
	rows, err := q.db.Query(ctx, listIgnoredForMetric,
		arg.UserID,
		arg.Metric,
		arg.Start,
		arg.EndAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIgnoredForMetricRow
	for rows.Next() {
		var i ListIgnoredForMetricRow
		if err := rows.Scan(
			&i.OriginKey,
			&i.OriginName,
			&i.Records,
			&i.FirstAt,
			&i.LastAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIgnoredItems = `-- name: ListIgnoredItems :many
SELECT i.item_kind, i.item_code, o.origin_key, o.name AS origin_name, sum(i.records)::bigint AS records,
  min(i.first_at)::timestamptz AS first_at, max(i.last_at)::timestamptz AS last_at
FROM ignored_records i JOIN data_origins o ON o.id = i.origin_id
WHERE i.user_id = $1
GROUP BY 1, 2, 3, 4
ORDER BY 1, 2, 3
`

type ListIgnoredItemsRow struct {
	ItemKind   string
	ItemCode   string
	OriginKey  string
	OriginName *string
	Records    int64
	FirstAt    time.Time
	LastAt     time.Time
}

// Explore's "ignored sources": records held raw per item and origin.
func (q *Queries) ListIgnoredItems(ctx context.Context, userID uuid.UUID) ([]ListIgnoredItemsRow, error) {
	rows, err := q.db.Query(ctx, listIgnoredItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIgnoredItemsRow
	for rows.Next() {
		var i ListIgnoredItemsRow
		if err := rows.Scan(
			&i.ItemKind,
			&i.ItemCode,
			&i.OriginKey,
			&i.OriginName,
			&i.Records,
			&i.FirstAt,
			&i.LastAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIgnoredRawForTake = `-- name: ListIgnoredRawForTake :many
SELECT DISTINCT r.id, r.batch_id, o.origin_key, split_part(r.external_key, ':', 1)::text AS type
FROM ignored_records i
JOIN data_origins o ON o.id = i.origin_id
JOIN raw_payloads r ON r.id = i.raw_payload_id
JOIN ingest_batches b ON b.id = r.batch_id
WHERE i.user_id = $1 AND b.client_id = $2 AND o.origin_key = ANY($3::text[])
ORDER BY r.id
`

type ListIgnoredRawForTakeParams struct {
	UserID     uuid.UUID
	ClientID   *uuid.UUID
	OriginKeys []string
}

type ListIgnoredRawForTakeRow struct {
	ID        int64
	BatchID   uuid.UUID
	OriginKey string
	Type      string
}

// The device's raw payloads holding ignored records of these origins, to normalize again once
// they are taken. type is the HealthKit type of the page (external_key is '<type>:<key>').
func (q *Queries) ListIgnoredRawForTake(ctx context.Context, arg ListIgnoredRawForTakeParams) ([]ListIgnoredRawForTakeRow, error) {
	rows, err := q.db.Query(ctx, listIgnoredRawForTake, arg.UserID, arg.ClientID, arg.OriginKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIgnoredRawForTakeRow
	for rows.Next() {
		var i ListIgnoredRawForTakeRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.OriginKey,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceFilterDefaults = `-- name: ListSourceFilterDefaults :many
SELECT x.pattern::text AS pattern, p.code AS provider, p.name AS provider_name
FROM (
  SELECT replace(replace(replace(o.origin_key, '\', '\\'), '%', '\%'), '_', '\_') AS pattern, o.relayed_provider_id AS relayed
  FROM data_origins o JOIN providers t ON t.id = o.provider_id AND t.code = 'apple_health'
  WHERE o.user_id = $1 AND o.relayed_provider_id IS NOT NULL
  UNION
  SELECT k.origin_pattern, k.relayed_provider_id
  FROM known_relay_origins k JOIN providers t ON t.id = k.provider_id AND t.code = 'apple_health'
  WHERE NOT EXISTS (SELECT 1 FROM data_origins o WHERE o.user_id = $1 AND o.provider_id = k.provider_id AND o.origin_key LIKE k.origin_pattern)
) x
JOIN providers p ON p.id = x.relayed
WHERE EXISTS (SELECT 1 FROM connections c WHERE c.user_id = $1 AND c.provider_id = x.relayed AND c.status <> 'disabled')
ORDER BY 1, 2
`

type ListSourceFilterDefaultsRow struct {
	Pattern      string
	Provider     string
	ProviderName string
}

// The origins ignored by default: Apple Health origins that relay a provider the owner connects
// directly (a connection that is not disabled). A seen origin's classification
// (data_origins.relayed_provider_id, owner edits included) wins over known_relay_origins, which
// covers the origins not seen yet. Patterns are LIKE patterns with backslash escapes.
func (q *Queries) ListSourceFilterDefaults(ctx context.Context, userID uuid.UUID) ([]ListSourceFilterDefaultsRow, error) {
	rows, err := q.db.Query(ctx, listSourceFilterDefaults, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSourceFilterDefaultsRow
	for rows.Next() {
		var i ListSourceFilterDefaultsRow
		if err := rows.Scan(&i.Pattern, &i.Provider, &i.ProviderName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDeviceSourceFilter = `-- name: LockDeviceSourceFilter :one
SELECT cl.id, cl.user_id, cl.revoked_at, cl.source_filter, cl.source_filter_version, cl.health_sources, cl.health_sources_at
FROM clients cl
WHERE cl.id = $1 AND cl.user_id = $2 AND cl.kind = 'device'
FOR UPDATE
`

type LockDeviceSourceFilterParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type LockDeviceSourceFilterRow struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	RevokedAt           *time.Time
	SourceFilter        json.RawMessage
	SourceFilterVersion int32
	HealthSources       json.RawMessage
	HealthSourcesAt     *time.Time
}

func (q *Queries) LockDeviceSourceFilter(ctx context.Context, arg LockDeviceSourceFilterParams) (LockDeviceSourceFilterRow, error) {
	row := q.db.QueryRow(ctx, lockDeviceSourceFilter, arg.ID, arg.UserID)
	var i LockDeviceSourceFilterRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RevokedAt,
		&i.SourceFilter,
		&i.SourceFilterVersion,
		&i.HealthSources,
		&i.HealthSourcesAt,
	)
	return i, err
}

const setDeviceHealthSources = `-- name: SetDeviceHealthSources :execrows
UPDATE clients SET health_sources = $1, health_sources_at = $2::timestamptz
WHERE id = $3 AND kind = 'device' AND revoked_at IS NULL
`

type SetDeviceHealthSourcesParams struct {
	HealthSources json.RawMessage
	ReportedAt    time.Time
	ID            uuid.UUID
}

// What the device found in Apple Health (bundle ids, names, types and last sample times).
func (q *Queries) SetDeviceHealthSources(ctx context.Context, arg SetDeviceHealthSourcesParams) (int64, error) {
	result, err := q.db.Exec(ctx, setDeviceHealthSources, arg.HealthSources, arg.ReportedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setDeviceSourceFilter = `-- name: SetDeviceSourceFilter :one
UPDATE clients SET source_filter = $1, source_filter_version = source_filter_version + 1
WHERE id = $2 AND kind = 'device'
RETURNING source_filter_version
`

type SetDeviceSourceFilterParams struct {
	SourceFilter json.RawMessage
	ID           uuid.UUID
}

func (q *Queries) SetDeviceSourceFilter(ctx context.Context, arg SetDeviceSourceFilterParams) (int32, error) {
	row := q.db.QueryRow(ctx, setDeviceSourceFilter, arg.SourceFilter, arg.ID)
	var source_filter_version int32
	err := row.Scan(&source_filter_version)
	return source_filter_version, err
}
