// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: status.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const coverageHours = `-- name: CoverageHours :many

SELECT mc.code AS metric, p.code AS source, a.local_date, count(DISTINCT a.hour_start)::int AS hours
FROM source_hourly_aggregates a
JOIN metric_catalog mc ON mc.id = a.metric_id
JOIN connections c ON c.id = a.connection_id
JOIN providers p ON p.id = c.provider_id
WHERE a.user_id = $1
  AND a.hour_start >= $2 AND a.hour_start < $3
  AND a.local_date BETWEEN $4 AND $5
  AND ($6::text[] IS NULL OR mc.code = ANY($6::text[]))
  AND ($7::text[] IS NULL OR a.origin_id IN
       (SELECT o.id FROM data_origins o WHERE o.user_id = $1 AND o.origin_key = ANY($7::text[])))
GROUP BY mc.code, p.code, a.local_date
ORDER BY mc.code, p.code, a.local_date
`

type CoverageHoursParams struct {
	UserID   uuid.UUID
	FromAt   time.Time
	ToAt     time.Time
	FromDate time.Time
	ToDate   time.Time
	Metrics  []string
	Origins  []string
}

type CoverageHoursRow struct {
	Metric    string
	Source    string
	LocalDate time.Time
	Hours     int32
}

// Coverage and system status (J10.5).
// Hours with data per provider, metric and local date, from the hourly aggregates. A provider
// counts an hour once however many of its devices and apps contributed. The hour_start bounds
// (the date range widened by a day on both sides) let the primary key narrow the scan; local_date
// is the exact filter. origins (origin keys) narrows to the hours those apps contributed.
func (q *Queries) CoverageHours(ctx context.Context, arg CoverageHoursParams) ([]CoverageHoursRow, error) {
	rows, err := q.db.Query(ctx, coverageHours,
		arg.UserID,
		arg.FromAt,
		arg.ToAt,
		arg.FromDate,
		arg.ToDate,
		arg.Metrics,
		arg.Origins,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoverageHoursRow
	for rows.Next() {
		var i CoverageHoursRow
		if err := rows.Scan(
			&i.Metric,
			&i.Source,
			&i.LocalDate,
			&i.Hours,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const instanceSizes = `-- name: InstanceSizes :one
SELECT pg_database_size(current_database())::bigint AS database_bytes,
       current_setting('server_version')::text AS postgres_version,
       (SELECT coalesce(sum(stored_bytes), 0)::bigint FROM blobs) AS blob_bytes
`

type InstanceSizesRow struct {
	DatabaseBytes   int64
	PostgresVersion string
	BlobBytes       int64
}

// Database size, Postgres version and the stored size of the live blobs.
func (q *Queries) InstanceSizes(ctx context.Context) (InstanceSizesRow, error) {
	row := q.db.QueryRow(ctx, instanceSizes)
	var i InstanceSizesRow
	err := row.Scan(&i.DatabaseBytes, &i.PostgresVersion, &i.BlobBytes)
	return i, err
}

const listDeadJobsSince = `-- name: ListDeadJobsSince :many
SELECT j.id, j.kind, j.connection_id, j.attempts, j.finished_at, r.error_class
FROM jobs j
LEFT JOIN connections c ON c.id = j.connection_id
LEFT JOIN LATERAL (SELECT jr.error_class FROM job_runs jr WHERE jr.job_id = j.id ORDER BY jr.id DESC LIMIT 1) r ON true
WHERE j.status = 'dead' AND j.finished_at >= $1
  AND (j.connection_id IS NULL OR c.user_id = $2)
ORDER BY j.finished_at DESC, j.id DESC
LIMIT $3
`

type ListDeadJobsSinceParams struct {
	Since  *time.Time
	UserID uuid.UUID
	Lim    int32
}

type ListDeadJobsSinceRow struct {
	ID           uuid.UUID
	Kind         string
	ConnectionID *uuid.UUID
	Attempts     int32
	FinishedAt   *time.Time
	ErrorClass   *string
}

// Jobs that ran out of attempts since @since, newest first, with the error class of their last run.
// Connection-less jobs belong to the single owner.
func (q *Queries) ListDeadJobsSince(ctx context.Context, arg ListDeadJobsSinceParams) ([]ListDeadJobsSinceRow, error) {
	rows, err := q.db.Query(ctx, listDeadJobsSince, arg.Since, arg.UserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeadJobsSinceRow
	for rows.Next() {
		var i ListDeadJobsSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ConnectionID,
			&i.Attempts,
			&i.FinishedAt,
			&i.ErrorClass,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
