package main

// labReports is the synthetic lab corpus. Every lab name is invented; codes are from
// docs/architecture/analyte-catalog.md ("" = not in the catalogue). Features name what a
// report exercises so extractor and review tests can pick one.
func labReports() []labReport {
	usCols := []labCol{{"Test", "label", 40}, {"Result", "value", 235}, {"Flag", "flag", 295}, {"Units", "unit", 330}, {"Reference Range", "range", 430}}
	return []labReport{
		{
			id: "lab-01", lab: "Quorralin Diagnostics", title: "Comprehensive Metabolic Panel", layout: "table", letter: true,
			dates: "us", specimen: "Serum", cols: usCols, size: 9, rangeSep: " - ",
			features: []string{"us_units", "flag_column_before_unit", "comparator_gt", "out_of_range_flag", "us_date"},
			sections: []labSection{{rows: []labRow{
				{code: "glucose", label: "Glucose", unit: "mg/dL", lo: "70", hi: "99", out: 1, flag: "H"},
				{code: "bun", label: "BUN", unit: "mg/dL", lo: "7", hi: "20"},
				{code: "creatinine", label: "Creatinine", unit: "mg/dL", lo: "0.60", hi: "1.30"},
				{code: "egfr", label: "eGFR (CKD-EPI 2021)", unit: "mL/min/1.73m²", lo: "59", rng: ">", fixed: "> 90"},
				{code: "sodium", label: "Sodium", unit: "mmol/L", lo: "136", hi: "145"},
				{code: "potassium", label: "Potassium", unit: "mmol/L", lo: "3.5", hi: "5.1"},
				{code: "chloride", label: "Chloride", unit: "mmol/L", lo: "98", hi: "107"},
				{code: "calcium", label: "Calcium", unit: "mg/dL", lo: "8.6", hi: "10.3"},
				{code: "alt", label: "ALT (SGPT)", unit: "U/L", lo: "7", hi: "56"},
				{code: "ast", label: "AST (SGOT)", unit: "U/L", lo: "10", hi: "40"},
				{code: "bilirubin_total", label: "Bilirubin, Total", unit: "mg/dL", lo: "0.1", hi: "1.2"},
				{code: "albumin", label: "Albumin", unit: "g/dL", lo: "3.5", hi: "5.0"},
				{code: "uric_acid", label: "Uric Acid", unit: "mg/dL", lo: "3.4", hi: "7.0"},
			}}},
		},
		{
			id: "lab-02", lab: "Oskelund Analytics", title: "Clinical Chemistry", layout: "table", dates: "iso", specimen: "Serum",
			cols: []labCol{{"Analyte", "label", 40}, {"Result", "value", 230}, {"Unit", "unit", 290}, {"Reference interval", "range", 370}, {"Flag", "flag", 490}},
			size: 9, rangeSep: " - ", cmpSpace: true,
			features: []string{"si_units", "flag_column_last", "comparator_lt", "upper_limit_only_range", "out_of_range_flag"},
			sections: []labSection{{rows: []labRow{
				{code: "glucose", label: "Glucose, fasting", unit: "mmol/L", lo: "3.9", hi: "5.5"},
				{code: "urea", label: "Urea", unit: "mmol/L", lo: "2.5", hi: "7.8"},
				{code: "creatinine", label: "Creatinine", unit: "µmol/L", lo: "59", hi: "104"},
				{code: "sodium", label: "Sodium", unit: "mmol/L", lo: "136", hi: "145"},
				{code: "potassium", label: "Potassium", unit: "mmol/L", lo: "3.5", hi: "5.1"},
				{code: "calcium", label: "Calcium", unit: "mmol/L", lo: "2.15", hi: "2.55"},
				{code: "magnesium", label: "Magnesium", unit: "mmol/L", lo: "0.70", hi: "1.00"},
				{code: "phosphate", label: "Phosphate", unit: "mmol/L", lo: "0.81", hi: "1.45"},
				{code: "uric_acid", label: "Uric acid", unit: "µmol/L", lo: "200", hi: "430"},
				{code: "bilirubin_total", label: "Bilirubin, total", unit: "µmol/L", lo: "5", hi: "21", out: -1, flag: "L"},
				{code: "alt", label: "ALT", unit: "U/L", hi: "50", rng: "<"},
				{code: "ggt", label: "GGT", unit: "U/L", hi: "60", rng: "<"},
				{code: "crp", label: "CRP", unit: "mg/L", hi: "5.0", rng: "<", fixed: "< 0.6"},
			}}},
		},
		{
			id: "lab-03", lab: "Marrowgate Test Laboratory", title: "Lipid Panel with Lp(a)", layout: "inline", letter: true,
			dates: "us", specimen: "Serum", size: 9, rangeSep: "-",
			features: []string{"inline_layout", "us_units", "lpa_mass_unit", "hba1c_percent", "lower_limit_only_range", "no_space_comparator"},
			sections: []labSection{{heading: "LIPIDS", rows: []labRow{
				{code: "cholesterol_total", label: "Total Cholesterol", unit: "mg/dL", hi: "200", rng: "<"},
				{code: "triglycerides", label: "Triglycerides", unit: "mg/dL", hi: "150", rng: "<"},
				{code: "hdl_c", label: "HDL Cholesterol", unit: "mg/dL", lo: "39", rng: ">"},
				{code: "ldl_c", label: "LDL Cholesterol (calculated)", unit: "mg/dL", hi: "100", rng: "<", out: 1, flag: "H"},
				{code: "non_hdl_c", label: "Non-HDL Cholesterol", unit: "mg/dL", hi: "130", rng: "<"},
				{code: "apob", label: "Apolipoprotein B", unit: "mg/dL", hi: "90", rng: "<"},
				{code: "lpa_mass", label: "Lipoprotein (a)", unit: "mg/dL", hi: "30", rng: "<"},
			}}, {heading: "GLYCEMIC", rows: []labRow{
				{code: "hba1c", label: "Hemoglobin A1c", unit: "%", lo: "4.0", hi: "5.6"},
				{code: "hs_crp", label: "hs-CRP", unit: "mg/L", hi: "1.0", rng: "<"},
			}}},
		},
		{
			id: "lab-04", lab: "Pellucid Fixture Lab", title: "Cardiometabolic Profile", layout: "table", dates: "iso", specimen: "Serum",
			cols: []labCol{{"Test", "label", 40}, {"Result", "value", 220}, {"Units", "unit", 280}, {"Range", "range", 370}, {"Flag", "flag", 480}},
			size: 9, rangeSep: " - ", cmpSpace: true,
			features: []string{"si_units", "lpa_molar_unit", "hba1c_mmol_mol", "hba1c_percent", "unknown_analyte"},
			sections: []labSection{{heading: "Lipids", rows: []labRow{
				{code: "cholesterol_total", label: "Cholesterol, total", unit: "mmol/L", hi: "5.0", rng: "<"},
				{code: "ldl_c", label: "LDL-C", unit: "mmol/L", hi: "3.0", rng: "<"},
				{code: "hdl_c", label: "HDL-C", unit: "mmol/L", lo: "1.0", rng: ">"},
				{code: "triglycerides", label: "Triglycerides", unit: "mmol/L", hi: "1.7", rng: "<"},
				{code: "apob", label: "ApoB", unit: "g/L", lo: "0.55", hi: "1.20"},
				{code: "lpa_molar", label: "Lipoprotein(a)", unit: "nmol/L", hi: "75", rng: "<"},
				{label: "Lp-PLA2 activity", unit: "nmol/min/mL", hi: "225", rng: "<"},
			}}, {heading: "Glucose metabolism", rows: []labRow{
				{code: "glucose", label: "Glucose", unit: "mmol/L", lo: "3.9", hi: "5.5"},
				{code: "hba1c", label: "HbA1c (IFCC)", unit: "mmol/mol", lo: "20", hi: "42"},
				{code: "hba1c", label: "HbA1c (DCCT)", unit: "%", lo: "4.0", hi: "6.0", hba1cPct: true},
			}}},
		},
		{
			id: "lab-05", lab: "Brindlewick Haematology", title: "Full Blood Count", layout: "table", dates: "iso", specimen: "EDTA whole blood",
			cols: []labCol{{"Test", "label", 40}, {"Result", "value", 220}, {"Flag", "flag", 275}, {"Units", "unit", 305}, {"Reference", "range", 390}},
			size: 9, rangeSep: " - ", cmpSpace: true, perPage: 11,
			features: []string{"multi_page", "haematology", "out_of_range_flag", "percent_and_absolute"},
			sections: []labSection{{heading: "Full blood count", rows: []labRow{
				{code: "wbc", label: "White cell count", unit: "10^9/L", lo: "4.0", hi: "11.0"},
				{code: "rbc", label: "Red cell count", unit: "10^12/L", lo: "4.50", hi: "5.90"},
				{code: "hemoglobin", label: "Haemoglobin", unit: "g/L", lo: "130", hi: "170"},
				{code: "hematocrit", label: "Haematocrit", unit: "L/L", lo: "0.40", hi: "0.50"},
				{code: "mcv", label: "MCV", unit: "fL", lo: "80", hi: "100"},
				{code: "mch", label: "MCH", unit: "pg", lo: "27.0", hi: "33.0"},
				{code: "mchc", label: "MCHC", unit: "g/L", lo: "320", hi: "360"},
				{code: "rdw_cv", label: "RDW-CV", unit: "%", lo: "11.5", hi: "14.5"},
				{code: "platelets", label: "Platelets", unit: "10^9/L", lo: "150", hi: "400", out: -1, flag: "L"},
				{code: "mpv", label: "MPV", unit: "fL", lo: "7.5", hi: "11.5"},
			}}, {heading: "Differential", rows: []labRow{
				{code: "neutrophils_abs", label: "Neutrophils", unit: "10^9/L", lo: "2.0", hi: "7.5"},
				{code: "neutrophils_pct", label: "Neutrophils %", unit: "%", lo: "40", hi: "75"},
				{code: "lymphocytes_abs", label: "Lymphocytes", unit: "10^9/L", lo: "1.0", hi: "4.0"},
				{code: "lymphocytes_pct", label: "Lymphocytes %", unit: "%", lo: "20", hi: "45"},
				{code: "monocytes_abs", label: "Monocytes", unit: "10^9/L", lo: "0.2", hi: "1.0"},
				{code: "eosinophils_abs", label: "Eosinophils", unit: "10^9/L", lo: "0.0", hi: "0.5"},
				{code: "basophils_abs", label: "Basophils", unit: "10^9/L", lo: "0.00", hi: "0.10"},
				{code: "esr", label: "ESR", unit: "mm/h", hi: "20", rng: "<"},
			}}},
		},
		{
			id: "lab-06", lab: "Quillmarsh Reference Lab", title: "Coagulation and Inflammation", layout: "stacked", letter: true,
			dates: "us", specimen: "Citrate plasma", size: 9, rangeSep: " - ", cmpSpace: true,
			features: []string{"stacked_layout", "d_dimer_feu", "comparator_le", "le_range", "no_unit_row"},
			sections: []labSection{{rows: []labRow{
				{code: "d_dimer", label: "D-Dimer", unit: "µg/mL FEU", hi: "0.50", rng: "<", fixed: "≤ 0.19"},
				{code: "fibrinogen", label: "Fibrinogen", unit: "mg/dL", lo: "200", hi: "400"},
				{code: "pt", label: "Prothrombin Time", unit: "s", lo: "11.0", hi: "13.5"},
				{code: "inr", label: "INR", lo: "0.8", hi: "1.2"},
				{code: "aptt", label: "aPTT", unit: "s", lo: "25", hi: "35"},
			}}, {heading: "Serum", specimen: "Serum", rows: []labRow{
				{code: "hs_crp", label: "C-Reactive Protein, high sensitivity", unit: "mg/L", hi: "3.0", rng: "<", fixed: "< 0.2"},
				{code: "il6", label: "Interleukin-6", unit: "pg/mL", hi: "7.0", rng: "<="},
				{code: "ferritin", label: "Ferritin", unit: "ng/mL", lo: "24", hi: "336"},
				{code: "homocysteine", label: "Homocysteine", unit: "µmol/L", hi: "15.0", rng: "<="},
			}}},
		},
		{
			id: "lab-07", lab: "Halvorine Laboratories", title: "Endocrine Panel", layout: "inline", dates: "dmy", specimen: "Serum",
			size: 9, rangeSep: " – ", cmpSpace: true,
			features: []string{"inline_layout", "ambiguous_date", "comparator_gt", "above_measuring_range", "en_dash_range"},
			sections: []labSection{{heading: "Thyroid", rows: []labRow{
				{code: "tsh", label: "TSH", unit: "mIU/L", lo: "0.27", hi: "4.20"},
				{code: "free_t4", label: "Free T4", unit: "pmol/L", lo: "12.0", hi: "22.0"},
				{code: "free_t3", label: "Free T3", unit: "pmol/L", lo: "3.1", hi: "6.8"},
				{code: "anti_tpo", label: "Anti-TPO", unit: "IU/mL", hi: "34", rng: "<", fixed: "< 9.0"},
			}}, {heading: "Other hormones and vitamins", rows: []labRow{
				{code: "vitamin_b12", label: "Vitamin B12", unit: "pmol/L", lo: "145", hi: "569", fixed: "> 1476", flag: "H"},
				{code: "testosterone_total", label: "Testosterone", unit: "nmol/L", lo: "8.6", hi: "29.0"},
				{code: "shbg", label: "SHBG", unit: "nmol/L", lo: "18.3", hi: "54.1"},
				{code: "cortisol", label: "Cortisol (08:00)", unit: "nmol/L", lo: "166", hi: "507"},
				{code: "vitamin_d_25oh", label: "25-OH Vitamin D", unit: "nmol/L", lo: "50", hi: "175"},
				{code: "prolactin", label: "Prolactin", unit: "µg/L", lo: "4.0", hi: "15.2"},
			}}},
		},
		{
			id: "lab-08", lab: "Vintermark Labor", title: "Laborbefund", layout: "table", german: true, dates: "de", specimen: "Serum",
			cols: []labCol{{"Untersuchung", "label", 40}, {"Ergebnis", "value", 210}, {"Einheit", "unit", 275}, {"Referenzbereich", "range", 370}, {"Kennz.", "flag", 490}},
			size: 9, rangeSep: " - ", cmpSpace: false,
			features: []string{"german_labels", "decimal_comma", "de_date", "hba1c_mmol_mol", "hba1c_percent", "unknown_analyte", "plus_flag"},
			sections: []labSection{{heading: "Klinische Chemie", rows: []labRow{
				{code: "glucose", label: "Glukose nüchtern", unit: "mg/dL", lo: "70", hi: "100"},
				{code: "creatinine", label: "Kreatinin", unit: "mg/dL", lo: "0.70", hi: "1.20"},
				{code: "egfr", label: "eGFR (CKD-EPI)", unit: "mL/min/1,73m²", lo: "60", rng: ">"},
				{code: "uric_acid", label: "Harnsäure", unit: "mg/dL", lo: "3.4", hi: "7.0"},
				{code: "ggt", label: "Gamma-GT", unit: "U/L", hi: "60", rng: "<"},
				{label: "Coeruloplasmin", unit: "g/L", lo: "0.20", hi: "0.60"},
			}}, {heading: "Fettstoffwechsel", rows: []labRow{
				{code: "cholesterol_total", label: "Cholesterin gesamt", unit: "mg/dL", hi: "200", rng: "<"},
				{code: "ldl_c", label: "LDL-Cholesterin", unit: "mg/dL", hi: "116", rng: "<", out: 1, flag: "+"},
				{code: "hdl_c", label: "HDL-Cholesterin", unit: "mg/dL", lo: "40", rng: ">"},
				{code: "triglycerides", label: "Triglyceride", unit: "mg/dL", hi: "150", rng: "<"},
			}}, {heading: "Weitere", rows: []labRow{
				{code: "hba1c", label: "HbA1c", unit: "mmol/mol", lo: "20", hi: "42"},
				{code: "hba1c", label: "HbA1c", unit: "%", lo: "4.0", hi: "6.0", hba1cPct: true},
				{code: "tsh", label: "TSH basal", unit: "µIU/mL", lo: "0.27", hi: "4.20"},
				{code: "ferritin", label: "Ferritin", unit: "ng/mL", lo: "30", hi: "400"},
			}}},
		},
		{
			id: "lab-09", lab: "Corvenna Synthetic Labs", title: "Extended Wellness Panel", layout: "table", dates: "iso", specimen: "Serum",
			cols: []labCol{{"Test", "label", 40}, {"Result", "value", 230}, {"Flag", "flag", 290}, {"Unit", "unit", 320}, {"Reference", "range", 410}},
			size: 9, rangeSep: " - ", cmpSpace: true, perPage: 10,
			features: []string{"multi_page", "three_pages", "us_units", "comparator_lt"},
			sections: []labSection{{heading: "Iron and vitamins", rows: []labRow{
				{code: "iron", label: "Iron", unit: "µg/dL", lo: "60", hi: "170"},
				{code: "transferrin", label: "Transferrin", unit: "mg/dL", lo: "200", hi: "360"},
				{code: "transferrin_saturation", label: "Transferrin saturation", unit: "%", lo: "20", hi: "50"},
				{code: "ferritin", label: "Ferritin", unit: "ng/mL", lo: "30", hi: "400"},
				{code: "vitamin_d_25oh", label: "Vitamin D, 25-hydroxy", unit: "ng/mL", lo: "30", hi: "100"},
				{code: "vitamin_b12", label: "Vitamin B12", unit: "pg/mL", lo: "232", hi: "1245"},
				{code: "folate_serum", label: "Folate, serum", unit: "ng/mL", lo: "3.0", rng: ">"},
				{code: "zinc", label: "Zinc", unit: "µg/dL", lo: "60", hi: "130"},
				{code: "magnesium", label: "Magnesium", unit: "mg/dL", lo: "1.6", hi: "2.6"},
			}}, {heading: "Hormones", rows: []labRow{
				{code: "tsh", label: "TSH", unit: "µIU/mL", lo: "0.45", hi: "4.50"},
				{code: "free_t4", label: "Free T4", unit: "ng/dL", lo: "0.82", hi: "1.77"},
				{code: "cortisol", label: "Cortisol, AM", unit: "µg/dL", lo: "6.2", hi: "19.4"},
				{code: "testosterone_total", label: "Testosterone, total", unit: "ng/dL", lo: "264", hi: "916"},
				{code: "estradiol", label: "Estradiol", unit: "pg/mL", lo: "8", hi: "35"},
				{code: "dhea_s", label: "DHEA-S", unit: "µg/dL", lo: "102", hi: "416"},
				{code: "igf1", label: "IGF-1", unit: "ng/mL", lo: "98", hi: "282"},
				{code: "insulin", label: "Insulin, fasting", unit: "µIU/mL", lo: "2.6", hi: "24.9"},
				{code: "c_peptide", label: "C-Peptide", unit: "ng/mL", lo: "1.1", hi: "4.4"},
			}}, {heading: "Other", rows: []labRow{
				{code: "psa_total", label: "PSA, total", unit: "ng/mL", hi: "4.0", rng: "<"},
				{code: "nt_probnp", label: "NT-proBNP", unit: "pg/mL", hi: "125", rng: "<"},
				{code: "troponin_i_hs", label: "Troponin I, high sensitivity", unit: "ng/L", hi: "34", rng: "<", fixed: "< 3"},
				{code: "ck", label: "Creatine kinase", unit: "U/L", lo: "39", hi: "308"},
				{code: "ldh", label: "LDH", unit: "U/L", lo: "135", hi: "225"},
				{code: "amylase", label: "Amylase", unit: "U/L", lo: "28", hi: "100"},
				{code: "lipase", label: "Lipase", unit: "U/L", lo: "13", hi: "60"},
				{code: "cystatin_c", label: "Cystatin C", unit: "mg/L", lo: "0.61", hi: "0.95"},
			}}},
		},
		{
			id: "lab-10", lab: "Thistlebrook Laboratory", title: "Iron Studies and Vitamins", layout: "table", scanned: true,
			dates: "iso", specimen: "Serum",
			cols: []labCol{{"Test", "label", 40}, {"Result", "value", 215}, {"Units", "unit", 270}, {"Reference", "range", 335}, {"Flag", "flag", 430}},
			size: 9, rangeSep: " - ", cmpSpace: true,
			features: []string{"scanned_no_text_layer", "unreadable_cell", "ascii_units"},
			sections: []labSection{{rows: []labRow{
				{code: "iron", label: "Iron", unit: "umol/L", lo: "10", hi: "30"},
				{code: "transferrin", label: "Transferrin", unit: "g/L", lo: "2.0", hi: "3.6"},
				{code: "transferrin_saturation", label: "Transferrin saturation", unit: "%", lo: "20", hi: "50"},
				{code: "ferritin", label: "Ferritin", unit: "ug/L", lo: "30", hi: "400"},
				{code: "vitamin_d_25oh", label: "Vitamin D (25-OH)", unit: "nmol/L", lo: "50", hi: "175", unreadable: true},
				{code: "vitamin_b12", label: "Vitamin B12", unit: "pmol/L", lo: "145", hi: "569"},
				{code: "folate_serum", label: "Folate", unit: "nmol/L", lo: "7.0", rng: ">"},
				{code: "zinc", label: "Zinc", unit: "umol/L", lo: "11", hi: "18", out: 1, flag: "H"},
			}}},
		},
		{
			id: "lab-11", lab: "Saltmere Clinical Lab", title: "Urinalysis and Serology", layout: "table", letter: true,
			dates: "us", specimen: "Urine, Serum",
			cols: []labCol{{"Test", "label", 40}, {"Result", "value", 220}, {"Units", "unit", 300}, {"Reference Range", "range", 370}, {"Flag", "flag", 480}},
			size: 9, rangeSep: "-", cmpSpace: false,
			features: []string{"qualitative_results", "titre", "row_specimen", "unknown_analyte", "le_range", "asterisk_flag"},
			sections: []labSection{{heading: "Urinalysis - Specimen: Urine", specimen: "Urine", rows: []labRow{
				{code: "urine_color", label: "Color", fixed: "Yellow", rng: "text", refText: "Yellow"},
				{code: "urine_clarity", label: "Appearance", fixed: "Clear", rng: "text", refText: "Clear"},
				{code: "urine_specific_gravity", label: "Specific Gravity", lo: "1.005", hi: "1.030"},
				{code: "urine_ph", label: "pH", lo: "5.0", hi: "8.0"},
				{code: "urine_protein", label: "Protein", fixed: "Negative", rng: "text", refText: "Negative"},
				{code: "urine_glucose", label: "Glucose", fixed: "Negative", rng: "text", refText: "Negative"},
				{code: "urine_ketones", label: "Ketones", fixed: "Trace", rng: "text", refText: "Negative", flag: "*"},
				{code: "urine_blood", label: "Blood", fixed: "Negative", rng: "text", refText: "Negative"},
				{code: "urine_wbc", label: "WBC", unit: "/HPF", lo: "0", hi: "5", fixed: "0-2"},
			}}, {heading: "Serology - Specimen: Serum", specimen: "Serum", rows: []labRow{
				{code: "ana", label: "ANA Screen, IFA", fixed: "Positive", rng: "text", refText: "Negative", flag: "*"},
				{code: "ana", label: "ANA Titer", fixed: "1:160", rng: "text", refText: "<1:80", flag: "*"},
				{code: "rf", label: "Rheumatoid Factor", unit: "IU/mL", hi: "14", rng: "<", fixed: "<10"},
				{label: "Galectin-3", unit: "ng/mL", hi: "17.8", rng: "<="},
			}}},
		},
		{
			id: "lab-12", lab: "Lumenfold Diagnostics", title: "Liver and Kidney Function", layout: "twocol", dates: "iso", specimen: "Serum",
			cols: []labCol{{"Test", "label", 40}, {"Result", "value", 145}, {"Unit", "unit", 185}, {"Range", "range", 230}},
			size: 8, rangeSep: "-", cmpSpace: true,
			features: []string{"two_panel_layout", "si_units", "no_flag_column"},
			sections: []labSection{{heading: "Liver", rows: []labRow{
				{code: "alt", label: "ALT", unit: "U/L", lo: "10", hi: "50"},
				{code: "ast", label: "AST", unit: "U/L", lo: "10", hi: "50"},
				{code: "alp", label: "ALP", unit: "U/L", lo: "40", hi: "130"},
				{code: "ggt", label: "GGT", unit: "U/L", lo: "10", hi: "71"},
				{code: "bilirubin_total", label: "Bilirubin, total", unit: "µmol/L", lo: "5", hi: "21"},
				{code: "albumin", label: "Albumin", unit: "g/L", lo: "35", hi: "52"},
				{code: "total_protein", label: "Total protein", unit: "g/L", lo: "64", hi: "83"},
			}}, {heading: "Kidney", rows: []labRow{
				{code: "creatinine", label: "Creatinine", unit: "µmol/L", lo: "62", hi: "106"},
				{code: "urea", label: "Urea", unit: "mmol/L", lo: "2.8", hi: "8.1"},
				{code: "sodium", label: "Sodium", unit: "mmol/L", lo: "136", hi: "145"},
				{code: "potassium", label: "Potassium", unit: "mmol/L", lo: "3.5", hi: "5.1"},
				{code: "cystatin_c", label: "Cystatin C", unit: "mg/L", lo: "0.61", hi: "0.95"},
			}}},
		},
	}
}
