#!/usr/bin/env bash
# Copies api/openapi.yaml into VitamuxKit for swift-openapi-generator (J22.4, run by `make openapi`;
# CI fails when the committed copy drifts). A plain symlink is not enough: the generator rejects a
# nullable reference, `oneOf: [{$ref: X}, {type: 'null'}]`, and silently drops the property, so
# a closed object (additionalProperties: false) then fails to decode. The copy rewrites each one to
# `$ref: X` plus `type: ['null']` (an inline object to `type: [object, 'null']`), which the
# generator reads as an optional X. Nothing else changes.
set -euo pipefail
cd "$(dirname "$0")"
src=../../api/openapi.yaml
dst=Sources/VitamuxKit/API/openapi.yaml

{
  echo "# Generated by apple/VitamuxKit/copy-openapi.sh from api/openapi.yaml; do not edit. Run: make openapi"
  perl -0pe '
    # Block form:  oneOf:\n  - {$ref: X}\n  - {type: null}
    s/^([ ]+)oneOf:\n[ ]+- \{?\$ref: (\x27[^\x27]+\x27)\}?\n[ ]+- \{?type: \x27null\x27\}?\n/$1\$ref: $2\n$1type: [\x27null\x27]\n/mg;
    # Block value:  oneOf: [{$ref: X}, {type: null}]
    s/^([ ]+)oneOf: \[\{\$ref: (\x27[^\x27]+\x27)\}, \{type: \x27null\x27\}\]\n/$1\$ref: $2\n$1type: [\x27null\x27]\n/mg;
    # Inline object or null:  oneOf:\n  - type: object\n    ...\n  - {type: null}  ->  type: [object, null]
    s{^([ ]+)oneOf:\n\1  - type: object\n((?:\1    .*\n)+?)\1  - \{type: \x27null\x27\}\n}{my ($i, $b) = ($1, $2); $b =~ s/^\Q$i\E    /$i/mg; "${i}type: [object, \x27null\x27]\n$b"}mge;
    # Flow mapping:  {oneOf: [{$ref: X}, {type: null}], ...}
    s/\{oneOf: \[\{\$ref: (\x27[^\x27]+\x27)\}, \{type: \x27null\x27\}\]/{\$ref: $1, type: [\x27null\x27]/g;
  ' "$src"
} > "$dst.tmp"

# A nullable form this script does not know would be dropped again: fail instead.
if grep -nE "\{type: 'null'\}|- type: 'null'" "$dst.tmp"; then
  rm "$dst.tmp"
  echo "copy-openapi.sh: unhandled {type: 'null'} schema above; extend the rewrite" >&2
  exit 1
fi
mv "$dst.tmp" "$dst"
