package resolve

import (
	"encoding/json"
	"fmt"
	"slices"
	"strings"
)

// DefaultsDocPath is the generated list of built-ins, relative to the repository root.
const DefaultsDocPath = "docs/resolution-defaults.md"

// DefaultsDoc renders docs/resolution-defaults.md from Builtins.
func DefaultsDoc() string {
	var b strings.Builder
	b.WriteString("# Built-in resolution defaults\n\n")
	b.WriteString("Generated by `go run ./internal/resolve/gen` from [`internal/resolve/builtin.go`](../internal/resolve/builtin.go); do not edit. ")
	b.WriteString("The reasoning, evidence and review policy are in [architecture/resolution-defaults.md](architecture/resolution-defaults.md); the rule language is in [resolution.md](architecture/resolution.md#rule-specification).\n\n")
	b.WriteString("A built-in applies while the owner has no rule for the metric. The first edit copies it into the owner's version 1, and from then on it is an ordinary rule. ")
	b.WriteString("Groups are tried in ladder order (`first_available`, `event_priority`); an input joins the first group it matches. ")
	b.WriteString("Groups naming a connector that does not exist yet stay empty, and the ladder starts at the next group.\n\n")

	b.WriteString("## Rules\n\n| Rule | Window | Strategy and gates | Ladder | Why |\n| --- | --- | --- | --- | --- |\n")
	all := Builtins()
	groups := map[string][]Selector{}
	var ids []string
	for _, x := range all {
		r := x.Rule
		var ladder []string
		for _, gr := range r.Groups {
			ladder = append(ladder, "`"+gr.ID+"`")
			if _, ok := groups[gr.ID]; !ok {
				groups[gr.ID] = gr.Match
				ids = append(ids, gr.ID)
			}
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s |\n", x.Ref(), windowLabel(r.Window), gates(&r), strings.Join(ladder, " › "), x.Why)
	}

	b.WriteString("\n## Groups\n\nA group id means the same selectors in every built-in. Fields of one selector are ANDed; selectors are ORed.\n\n")
	b.WriteString("| Group | Selectors |\n| --- | --- |\n")
	slices.Sort(ids)
	for _, id := range ids {
		var sels []string
		for _, s := range groups[id] {
			j, _ := json.Marshal(s)
			sels = append(sels, "`"+string(j)+"`")
		}
		fmt.Fprintf(&b, "| `%s` | %s |\n", id, strings.Join(sels, " or "))
	}

	b.WriteString("\n## Coverage\n\n")
	b.WriteString("- `metric: sleep` covers every `sleep_derived` code; `metric: blood_pressure` covers the `bp_reading` components.\n")
	var exempt []string
	for code := range NoBuiltin {
		exempt = append(exempt, code)
	}
	slices.Sort(exempt)
	for _, code := range exempt {
		fmt.Fprintf(&b, "- No built-in for `%s`: %s.\n", code, NoBuiltin[code])
	}
	b.WriteString("- Codes not in [metrics.md](metrics.md) get their built-in together with the code.\n")
	return b.String()
}

// gates describes a rule's strategy and gates on one line.
func gates(r *Rule) string {
	parts := []string{string(r.Strategy.Op)}
	if q := r.Quality; q != nil {
		if q.MinCoverage != nil {
			parts = append(parts, fmt.Sprintf("min_coverage %g", *q.MinCoverage))
		}
		if q.RequireWear != "" {
			parts = append(parts, "require_wear "+q.RequireWear)
		}
		if q.PlausibleRange != nil {
			parts = append(parts, fmt.Sprintf("plausible_range %g–%g", q.PlausibleRange[0], q.PlausibleRange[1]))
		}
		if len(q.ExcludeFlags) > 0 {
			parts = append(parts, "exclude_flags "+strings.Join(q.ExcludeFlags, ", "))
		}
		if q.MaxStaleness != "" {
			parts = append(parts, "max_staleness "+string(q.MaxStaleness))
		}
		if s := q.Sleep; s != nil {
			if s.MatchOverlap != nil {
				parts = append(parts, fmt.Sprintf("match_overlap %g", *s.MatchOverlap))
			}
			if s.MinEpisodeCoverage != nil {
				parts = append(parts, fmt.Sprintf("min_episode_coverage %g", *s.MinEpisodeCoverage))
			}
		}
	}
	if ws := r.WithinSource; ws != nil && ws.Statistic != "" {
		parts = append(parts, strings.TrimSpace("statistic "+string(ws.Statistic)+" "+string(ws.Span)))
	}
	if c := r.Compose; c != nil {
		parts = append(parts, fmt.Sprintf("compose %s by %s (E9)", c.Op, c.From))
	}
	if r.Follow != "" {
		parts = append(parts, "follow `"+r.Follow+"` (E5)")
	}
	for _, ctx := range []Context{ContextWorkout, ContextSleep} {
		if ids := r.Contexts[ctx]; len(ids) > 0 {
			parts = append(parts, fmt.Sprintf("contexts.%s %s (E1)", ctx, strings.Join(ids, ", ")))
		}
	}
	return strings.Join(parts, " · ")
}
