package catalog

import (
	"fmt"
	"strconv"
	"strings"
)

// DocPath is docs/metrics.md, relative to the repository root.
const DocPath = "docs/metrics.md"

// Seed markers (Metric.Since, Unit.Since; 0 means SeedV1) name the migration that seeds an
// entry. A generated seed file never changes once released: an entry added later takes a new
// marker and its own file.
const (
	SeedV1      = 10 // the J07.1 v1 seed
	SeedDerived = 20 // the derived codes of J09.10
)

var seedFiles = map[int]struct{ path, job string }{
	SeedV1:      {"internal/db/migrations/00010_catalogue_seed.sql", "J07.1"},
	SeedDerived: {"internal/db/migrations/00020_catalogue_derived.sql", "J09.10"},
}

func since(marker int) int {
	if marker == 0 {
		return SeedV1
	}
	return marker
}

func quote(s string) string { return "'" + strings.ReplaceAll(s, "'", "''") + "'" }

// rows joins lines with ",\n" between them and the given terminator after the last.
func rows(lines []string, end string) string { return strings.Join(lines, ",\n") + end + "\n" }

// SeedFiles renders the goose seed migrations of units and metric_catalog, by path relative to
// the repository root.
func SeedFiles() map[string]string {
	out := make(map[string]string, len(seedFiles))
	for marker, f := range seedFiles {
		out[f.path] = seedSQL(marker, f.job)
	}
	return out
}

// seedSQL renders the migration of one marker. Rows are inserted in slice order, so ids are
// stable across fresh databases.
func seedSQL(marker int, job string) string {
	var us, ms, mc, uc []string
	for _, u := range units {
		if since(u.Since) == marker {
			us = append(us, "  ("+quote(u.Code)+")")
			uc = append(uc, "  "+quote(u.Code))
		}
	}
	for _, m := range metrics {
		if since(m.Since) == marker {
			ms = append(ms, fmt.Sprintf("  (%d, %s, %s)", len(ms)+1, quote(m.Code), quote(m.Unit)))
			mc = append(mc, "  "+quote(m.Code))
		}
	}
	var b strings.Builder
	what := "metric_catalog"
	if len(us) > 0 {
		what = "units and metric_catalog"
	}
	b.WriteString("-- Seed of " + what + " (" + job + "). Generated by `go run ./internal/catalog/gen`; do not edit.\n")
	b.WriteString("-- Codes added later get their own migration.\n\n-- +goose Up\n")
	if len(us) > 0 {
		b.WriteString("INSERT INTO units (code) VALUES\n" + rows(us, ";") + "\n")
	}
	if len(ms) > 0 {
		b.WriteString("INSERT INTO metric_catalog (code, unit_id)\nSELECT v.code, u.id\nFROM (VALUES\n" + rows(ms, ""))
		b.WriteString(") AS v(ord, code, unit) JOIN units u ON u.code = v.unit\nORDER BY v.ord;\n")
	}
	b.WriteString("\n-- +goose Down\n")
	if len(mc) > 0 {
		b.WriteString("DELETE FROM metric_catalog WHERE code IN (\n" + rows(mc, ");"))
	}
	if len(uc) > 0 {
		b.WriteString("DELETE FROM units WHERE code IN (\n" + rows(uc, ");"))
	}
	return b.String()
}

func join[T ~string](xs []T) string {
	s := make([]string, len(xs))
	for i, x := range xs {
		s[i] = string(x)
	}
	return strings.Join(s, ", ")
}

func num(f float64) string { return strconv.FormatFloat(f, 'f', -1, 64) }

// MetricsDoc renders docs/metrics.md, the reference for implemented codes.
func MetricsDoc() string {
	var b strings.Builder
	b.WriteString("# Metrics and units\n\n")
	b.WriteString("Generated by `go run ./internal/catalog/gen` from [`internal/catalog`](../internal/catalog); do not edit. ")
	b.WriteString("Rules for adding codes and the codes not yet implemented: [metric-catalog.md](architecture/metric-catalog.md). ")
	b.WriteString("Units are canonical per metric; source units convert through [Units](#units).\n\n")
	b.WriteString("Kinds: `sample`, `interval`, `daily_value` (see [data-model](architecture/data-model.md#measurements)). A kind of `-` means the value is derived from sleep sessions, or for a derived code from another metric's series (rule extension E2). ")
	b.WriteString("Aggregation values are defined in [resolution](architecture/resolution.md#within-source-aggregation). ")
	b.WriteString("Plausible is the range outside which a value is flagged `implausible`. Apple HK and Withings columns are informational; HK ids omit the `HKQuantityTypeIdentifier` prefix.\n")

	section := ""
	for _, m := range metrics {
		if m.Section != section {
			section = m.Section
			b.WriteString("\n## " + section + "\n\n")
			b.WriteString("| Code | Unit | Kinds | Aggregation | Plausible | Windows | Group | Apple HK | Withings |\n| --- | --- | --- | --- | --- | --- | --- | --- | --- |\n")
		}
		kinds := join(m.Kinds)
		if kinds == "" {
			kinds = "-"
		}
		if m.DerivedFrom != "" {
			kinds = "- (from `" + m.DerivedFrom + "`)"
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s to %s | %s | %s | %s | %s |\n",
			m.Code, m.Unit, kinds, m.Agg, num(m.Min), num(m.Max), join(m.Windows()), m.Group, m.HK, m.Withings)
	}

	b.WriteString("\n## Windows and strategies by aggregation\n\n")
	var selection []string
	for _, m := range metrics {
		if m.SelectionOnly {
			selection = append(selection, "`"+m.Code+"`")
		}
	}
	b.WriteString("Bucket size is 5 minutes for `intensive` and `additive`. Provider-scoped scores and selection-only metrics (" +
		strings.Join(selection, ", ") + ") lose `mean`, `min` and `max`. Metrics in a group add the `reading` window.\n\n")
	b.WriteString("| Aggregation | Windows | Strategies |\n| --- | --- | --- |\n")
	for _, a := range []Aggregation{Intensive, Additive, Latest, DailySummary, SleepDerived} {
		m := Metric{Agg: a}
		fmt.Fprintf(&b, "| %s | %s | %s |\n", a, join(m.Windows()), join(m.Strategies()))
	}
	b.WriteString("\n`sum` needs an explicit duplicate-risk acknowledgement in the rule.\n")

	b.WriteString("\n## Units\n\nA value converts to the base unit as `value * factor + offset`.\n\n")
	b.WriteString("| Unit | Base | Factor | Offset |\n| --- | --- | --- | --- |\n")
	for _, u := range units {
		fmt.Fprintf(&b, "| %s | %s | %s | %s |\n", u.Code, u.Base, num(u.Factor), num(u.Offset))
	}
	return b.String()
}
