package catalog

import (
	"fmt"
	"strconv"
	"strings"
)

// Paths of the generated files, relative to the repository root.
const (
	SeedPath = "internal/db/migrations/00010_catalogue_seed.sql"
	DocPath  = "docs/metrics.md"
)

func quote(s string) string { return "'" + strings.ReplaceAll(s, "'", "''") + "'" }

// rows joins lines with ",\n" between them and the given terminator after the last.
func rows(lines []string, end string) string { return strings.Join(lines, ",\n") + end + "\n" }

// SeedSQL renders the goose migration that seeds units and metric_catalog. Rows are inserted in
// slice order, so ids are stable across fresh databases.
func SeedSQL() string {
	var b strings.Builder
	b.WriteString("-- Seed of units and metric_catalog (J07.1). Generated by `go run ./internal/catalog/gen`; do not edit.\n")
	b.WriteString("-- Codes added later get their own migration.\n\n-- +goose Up\n")

	var us, ms, mc, uc []string
	for _, u := range units {
		us = append(us, "  ("+quote(u.Code)+")")
		uc = append(uc, "  "+quote(u.Code))
	}
	for i, m := range metrics {
		ms = append(ms, fmt.Sprintf("  (%d, %s, %s)", i+1, quote(m.Code), quote(m.Unit)))
		mc = append(mc, "  "+quote(m.Code))
	}
	b.WriteString("INSERT INTO units (code) VALUES\n" + rows(us, ";"))
	b.WriteString("\nINSERT INTO metric_catalog (code, unit_id)\nSELECT v.code, u.id\nFROM (VALUES\n" + rows(ms, ""))
	b.WriteString(") AS v(ord, code, unit) JOIN units u ON u.code = v.unit\nORDER BY v.ord;\n")

	b.WriteString("\n-- +goose Down\nDELETE FROM metric_catalog WHERE code IN (\n" + rows(mc, ");"))
	b.WriteString("DELETE FROM units WHERE code IN (\n" + rows(uc, ");"))
	return b.String()
}

func join[T ~string](xs []T) string {
	s := make([]string, len(xs))
	for i, x := range xs {
		s[i] = string(x)
	}
	return strings.Join(s, ", ")
}

func num(f float64) string { return strconv.FormatFloat(f, 'f', -1, 64) }

// MetricsDoc renders docs/metrics.md, the reference for implemented codes.
func MetricsDoc() string {
	var b strings.Builder
	b.WriteString("# Metrics and units\n\n")
	b.WriteString("Generated by `go run ./internal/catalog/gen` from [`internal/catalog`](../internal/catalog); do not edit. ")
	b.WriteString("Rules for adding codes and the codes not yet implemented: [metric-catalog.md](architecture/metric-catalog.md). ")
	b.WriteString("Units are canonical per metric; source units convert through [Units](#units).\n\n")
	b.WriteString("Kinds: `sample`, `interval`, `daily_value` (see [data-model](architecture/data-model.md#measurements)). A kind of `-` means the value is derived from sleep sessions. ")
	b.WriteString("Aggregation values are defined in [resolution](architecture/resolution.md#within-source-aggregation). ")
	b.WriteString("Plausible is the range outside which a value is flagged `implausible`. Apple HK and Withings columns are informational; HK ids omit the `HKQuantityTypeIdentifier` prefix.\n")

	section := ""
	for _, m := range metrics {
		if m.Section != section {
			section = m.Section
			b.WriteString("\n## " + section + "\n\n")
			b.WriteString("| Code | Unit | Kinds | Aggregation | Plausible | Windows | Group | Apple HK | Withings |\n| --- | --- | --- | --- | --- | --- | --- | --- | --- |\n")
		}
		kinds := join(m.Kinds)
		if kinds == "" {
			kinds = "-"
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s to %s | %s | %s | %s | %s |\n",
			m.Code, m.Unit, kinds, m.Agg, num(m.Min), num(m.Max), join(m.Windows()), m.Group, m.HK, m.Withings)
	}

	b.WriteString("\n## Windows and strategies by aggregation\n\n")
	b.WriteString("Bucket size is 5 minutes for `intensive` and `additive`. Provider-scoped scores lose `mean`, `min` and `max`. Metrics in a group add the `reading` window.\n\n")
	b.WriteString("| Aggregation | Windows | Strategies |\n| --- | --- | --- |\n")
	for _, a := range []Aggregation{Intensive, Additive, Latest, DailySummary, SleepDerived} {
		m := Metric{Agg: a}
		fmt.Fprintf(&b, "| %s | %s | %s |\n", a, join(m.Windows()), join(m.Strategies()))
	}
	b.WriteString("\n`sum` needs an explicit duplicate-risk acknowledgement in the rule.\n")

	b.WriteString("\n## Units\n\nA value converts to the base unit as `value * factor + offset`.\n\n")
	b.WriteString("| Unit | Base | Factor | Offset |\n| --- | --- | --- | --- |\n")
	for _, u := range units {
		fmt.Fprintf(&b, "| %s | %s | %s | %s |\n", u.Code, u.Base, num(u.Factor), num(u.Offset))
	}
	return b.String()
}
