package analytes

import (
	"fmt"
	"path/filepath"
	"strconv"
	"strings"
)

// Generated files, relative to the repository root. The migration is found by its name
// suffix, so a renumbered migration keeps working.
const (
	SeedGlob = "internal/db/migrations/*_analytes.sql"
	DocPath  = "docs/analytes.md"
)

// SeedPath returns the path of the seed migration under root: the single file matching SeedGlob.
func SeedPath(root string) (string, error) {
	m, err := filepath.Glob(filepath.Join(root, SeedGlob))
	if err != nil {
		return "", err
	}
	if len(m) != 1 {
		return "", fmt.Errorf("analytes: want exactly one %s, found %d", SeedGlob, len(m))
	}
	return m[0], nil
}

func quote(s string) string { return "'" + strings.ReplaceAll(s, "'", "''") + "'" }

func nullable(s string) string {
	if s == "" {
		return "NULL"
	}
	return quote(s)
}

func num(f float64) string { return strconv.FormatFloat(f, 'f', -1, 64) }

// schema is the DDL part of the seed migration. The foreign keys from the 00018 lab tables
// are added here because those tables are created first.
const schema = `CREATE TABLE analytes (
  id             smallint PRIMARY KEY,
  code           text NOT NULL UNIQUE CHECK (code ~ '^[a-z][a-z0-9_]*$'),
  name           text NOT NULL,
  canonical_unit text,
  loinc          text CHECK (loinc ~ '^[0-9]{1,7}-[0-9]$')
);
COMMENT ON TABLE analytes IS 'Lab analytes owned by internal/documents/analytes. No reference ranges: ranges come from the printed report.';
COMMENT ON COLUMN analytes.canonical_unit IS 'Null when values are kept as printed only. Conversions are owned by code.';
COMMENT ON COLUMN analytes.loinc IS 'Only from a verified loinc.org lookup, never guessed.';
REVOKE INSERT, UPDATE, DELETE ON analytes FROM vitamux_app;

CREATE TABLE analyte_aliases (
  id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  analyte_id smallint NOT NULL REFERENCES analytes,
  label      text NOT NULL CHECK (label <> ''),
  label_key  text NOT NULL CHECK (label_key <> ''),
  user_id    uuid REFERENCES users ON DELETE CASCADE,
  created_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK ((user_id IS NULL) = (created_by IS NULL))
);
COMMENT ON TABLE analyte_aliases IS 'Printed labels mapped to analytes: seeded rows (user_id null, read-only by convention) and owner aliases, which take precedence.';
COMMENT ON COLUMN analyte_aliases.label_key IS 'analytes.LabelKey(label): lower case, punctuation runs collapsed to one space.';
CREATE UNIQUE INDEX analyte_aliases_seed_idx ON analyte_aliases (label_key) WHERE user_id IS NULL;
CREATE UNIQUE INDEX analyte_aliases_owner_idx ON analyte_aliases (user_id, label_key) WHERE user_id IS NOT NULL;
REVOKE UPDATE ON analyte_aliases FROM vitamux_app;

ALTER TABLE lab_extracted_rows ADD CONSTRAINT lab_extracted_rows_suggested_analyte_id_fkey
  FOREIGN KEY (suggested_analyte_id) REFERENCES analytes;
ALTER TABLE lab_results ADD CONSTRAINT lab_results_analyte_id_fkey FOREIGN KEY (analyte_id) REFERENCES analytes;
`

// SeedSQL renders the goose migration that creates and seeds analytes and analyte_aliases.
// Rows are inserted in slice order, so ids are stable across fresh databases.
func SeedSQL() string {
	var b strings.Builder
	b.WriteString("-- Lab analyte catalogue and aliases (J12.5; docs/architecture/analyte-catalog.md).\n")
	b.WriteString("-- Generated by `go run ./internal/documents/analytes/gen`; do not edit. Codes added later get their own migration.\n\n")
	b.WriteString("-- +goose Up\n" + schema)

	var as, ls []string
	for i, an := range analytes {
		as = append(as, fmt.Sprintf("  (%d, %s, %s, %s, %s)", i+1, quote(an.Code), quote(an.Name), nullable(an.Unit), nullable(an.LOINC)))
		for _, l := range an.SeedAliases() {
			ls = append(ls, fmt.Sprintf("  (%d, %s, %s)", i+1, quote(l), quote(LabelKey(l))))
		}
	}
	b.WriteString("\nINSERT INTO analytes (id, code, name, canonical_unit, loinc) VALUES\n" + strings.Join(as, ",\n") + ";\n")
	b.WriteString("\nINSERT INTO analyte_aliases (analyte_id, label, label_key) VALUES\n" + strings.Join(ls, ",\n") + ";\n")

	b.WriteString("\n-- +goose Down\n")
	b.WriteString("ALTER TABLE lab_results DROP CONSTRAINT lab_results_analyte_id_fkey;\n")
	b.WriteString("ALTER TABLE lab_extracted_rows DROP CONSTRAINT lab_extracted_rows_suggested_analyte_id_fkey;\n")
	b.WriteString("DROP TABLE analyte_aliases, analytes;\n")
	return b.String()
}

func (c Conversion) String() string {
	s := c.Unit + " ×" + num(c.Factor)
	if c.Offset != 0 {
		s += " " + num(c.Offset) + " (affine)"
	}
	return s
}

// Doc renders docs/analytes.md, the reference for implemented codes.
func Doc() string {
	var b strings.Builder
	b.WriteString("# Lab analytes\n\n")
	b.WriteString("Generated by `go run ./internal/documents/analytes/gen` from [`internal/documents/analytes`](../internal/documents/analytes); do not edit. ")
	b.WriteString("Rules: [analyte-catalog.md](architecture/analyte-catalog.md). Catalogue version " + strconv.Itoa(Version) + ".\n\n")
	b.WriteString("A conversion turns a printed value into the canonical unit as `value × factor + offset`; only affine conversions have an offset. ")
	b.WriteString("Refused units measure a different quantity and are never converted. A canonical unit of `-` means values are kept as printed only. ")
	b.WriteString("Units match ignoring case, spaces and parentheses, with µ/μ/u/mcg for micro and 10⁹, 10^9, x10E9 for powers of ten. ")
	b.WriteString("Name, code and aliases are the seeded printed labels; owner aliases are added through the API. ")
	b.WriteString("No LOINC code is filled until it is verified on loinc.org.\n")

	sec := ""
	for _, an := range analytes {
		if an.Section != sec {
			sec = an.Section
			b.WriteString("\n## " + sec + "\n\n")
			b.WriteString("| Code | Analyte | Canonical | Conversions | Refused | LOINC | Aliases |\n| --- | --- | --- | --- | --- | --- | --- |\n")
		}
		unit := an.Unit
		if unit == "" {
			unit = "-"
		}
		convs := make([]string, len(an.Conversions))
		for i, c := range an.Conversions {
			convs[i] = c.String()
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s | %s | %s |\n", an.Code, an.Name, unit,
			strings.Join(convs, " · "), strings.Join(an.Refused, ", "), an.LOINC, strings.Join(an.Aliases, ", "))
	}
	return b.String()
}
