-- Identity, settings and audit (J02.2). Ids are UUIDv7 generated by the app.

-- +goose Up
CREATE TABLE users (
  id              uuid PRIMARY KEY,
  username        text NOT NULL UNIQUE,
  password_hash   text NOT NULL,
  totp_ciphertext bytea,
  totp_key_id     text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  CHECK ((totp_ciphertext IS NULL) = (totp_key_id IS NULL))
);
COMMENT ON TABLE users IS 'The owner account. No signup; created by `vitamux admin create-owner`.';
COMMENT ON COLUMN users.password_hash IS 'argon2id PHC string.';
COMMENT ON COLUMN users.totp_ciphertext IS 'Sealed TOTP secret (internal/crypto format, purpose credentials).';
COMMENT ON COLUMN users.totp_key_id IS 'Master key id of totp_ciphertext, for rotation.';

CREATE TABLE timezone_periods (
  id         uuid PRIMARY KEY,
  user_id    uuid NOT NULL REFERENCES users ON DELETE CASCADE,
  tz         text NOT NULL,
  valid_from timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, valid_from)
);
COMMENT ON TABLE timezone_periods IS 'IANA timezone in effect from valid_from until the next period; used for local dates when a source has no offset.';

CREATE TABLE settings (
  user_id    uuid NOT NULL REFERENCES users ON DELETE CASCADE,
  key        text NOT NULL,
  value      jsonb NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, key)
);
COMMENT ON TABLE settings IS 'Owner settings as key/value.';

CREATE TABLE sessions (
  id           uuid PRIMARY KEY,
  user_id      uuid NOT NULL REFERENCES users ON DELETE CASCADE,
  token_hash   bytea NOT NULL UNIQUE,
  created_at   timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  expires_at   timestamptz NOT NULL
);
COMMENT ON TABLE sessions IS 'Server-side UI sessions; the cookie holds the token, the row only its SHA-256.';

CREATE TABLE api_keys (
  id           uuid PRIMARY KEY,
  user_id      uuid NOT NULL REFERENCES users ON DELETE CASCADE,
  name         text NOT NULL,
  secret_hash  bytea NOT NULL,
  scopes       text[] NOT NULL CHECK (cardinality(scopes) > 0
                 AND scopes <@ ARRAY['read:health', 'read:config', 'write:config', 'write:documents', 'admin']),
  created_at   timestamptz NOT NULL DEFAULT now(),
  last_used_at timestamptz,
  expires_at   timestamptz,
  revoked_at   timestamptz
);
COMMENT ON TABLE api_keys IS 'Personal access tokens `vmx_pat_<id>_<secret>`: the id is the lookup prefix, only the secret''s SHA-256 is stored.';

CREATE TABLE audit_events (
  id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id     uuid REFERENCES users ON DELETE SET NULL,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  actor       text NOT NULL,
  action      text NOT NULL,
  target_type text,
  target_id   text,
  detail      jsonb NOT NULL DEFAULT '{}'
);
COMMENT ON TABLE audit_events IS 'Append-only for the app role. Never holds secrets or health values.';
COMMENT ON COLUMN audit_events.actor IS 'Who acted: owner, an API key, a client, or system.';
REVOKE UPDATE, DELETE ON audit_events FROM vitamux_app;

-- +goose Down
DROP TABLE audit_events, api_keys, sessions, settings, timezone_periods, users;
