-- Seed of metric_catalog (J18.4, J19.4). Generated by `go run ./internal/catalog/gen`; do not edit.
-- Codes added later get their own migration.

-- +goose Up
INSERT INTO metric_catalog (code, unit_id)
SELECT v.code, u.id
FROM (VALUES
  (1, 'garmin_stress', 'index'),
  (2, 'garmin_body_battery', 'index'),
  (3, 'garmin_training_readiness', 'index'),
  (4, 'garmin_sleep_score', 'index'),
  (5, 'whoop_recovery', '%'),
  (6, 'whoop_strain', 'index'),
  (7, 'whoop_sleep_performance', '%')
) AS v(ord, code, unit) JOIN units u ON u.code = v.unit
ORDER BY v.ord;

-- +goose Down
DELETE FROM metric_catalog WHERE code IN (
  'garmin_stress',
  'garmin_body_battery',
  'garmin_training_readiness',
  'garmin_sleep_score',
  'whoop_recovery',
  'whoop_strain',
  'whoop_sleep_performance');
