-- Source setup in the web panel (E20, ADR-0021): provider app credentials and sidecars added in
-- the panel, both sealed by internal/crypto (purpose credentials). An environment value wins
-- over these rows; `vitamux keys rotate` re-seals them.

-- +goose Up
CREATE TABLE provider_app_credentials (
  provider   text PRIMARY KEY REFERENCES providers (code),
  client_id  text NOT NULL CHECK (client_id <> '' AND length(client_id) <= 512),
  ciphertext bytea NOT NULL,
  key_id     text NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid REFERENCES users ON DELETE SET NULL
);
COMMENT ON TABLE provider_app_credentials IS 'The owner''s own OAuth application per provider, entered in the panel. Environment values (e.g. VITAMUX_WITHINGS_CLIENT_ID and _SECRET) win over the row.';
COMMENT ON COLUMN provider_app_credentials.ciphertext IS 'Client secret, sealed (purpose credentials, AAD provider_app:<provider>). Write-only: never returned by the API.';

CREATE TABLE sidecars (
  name       text PRIMARY KEY CHECK (name ~ '^[a-z][a-z0-9_]*$'),
  url        text NOT NULL CHECK (url ~ '^https?://'),
  ciphertext bytea NOT NULL,
  key_id     text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid REFERENCES users ON DELETE SET NULL
);
COMMENT ON TABLE sidecars IS 'Remote sidecar connectors added in the panel (name = provider code); those of VITAMUX_SIDECARS are not stored.';
COMMENT ON COLUMN sidecars.ciphertext IS 'Shared bearer secret generated by Vitamux and shown once, sealed (purpose credentials, AAD sidecar:<name>).';

-- +goose Down
DROP TABLE sidecars;
DROP TABLE provider_app_credentials;
