-- Seed of metric_catalog (J25.4). Generated by `go run ./internal/catalog/gen`; do not edit.
-- Codes added later get their own migration.

-- +goose Up
INSERT INTO metric_catalog (code, unit_id)
SELECT v.code, u.id
FROM (VALUES
  (1, 'whoop_workout_strain', 'index'),
  (2, 'whoop_hr_zone_0_time', 's'),
  (3, 'whoop_hr_zone_1_time', 's'),
  (4, 'whoop_hr_zone_2_time', 's'),
  (5, 'whoop_hr_zone_3_time', 's'),
  (6, 'whoop_hr_zone_4_time', 's'),
  (7, 'whoop_hr_zone_5_time', 's'),
  (8, 'elevation_change', 'm'),
  (9, 'whoop_sleep_debt_post', 's'),
  (10, 'whoop_sleep_need_habitual', 's'),
  (11, 'whoop_sleep_need_from_strain', 's'),
  (12, 'whoop_sleep_nap_credit', 's'),
  (13, 'whoop_sleep_cycles', 'count')
) AS v(ord, code, unit) JOIN units u ON u.code = v.unit
ORDER BY v.ord;

-- +goose Down
DELETE FROM metric_catalog WHERE code IN (
  'whoop_workout_strain',
  'whoop_hr_zone_0_time',
  'whoop_hr_zone_1_time',
  'whoop_hr_zone_2_time',
  'whoop_hr_zone_3_time',
  'whoop_hr_zone_4_time',
  'whoop_hr_zone_5_time',
  'elevation_change',
  'whoop_sleep_debt_post',
  'whoop_sleep_need_habitual',
  'whoop_sleep_need_from_strain',
  'whoop_sleep_nap_credit',
  'whoop_sleep_cycles');
