-- Seed of metric_catalog (J25.5). Generated by `go run ./internal/catalog/gen`; do not edit.
-- Codes added later get their own migration.

-- +goose Up
INSERT INTO metric_catalog (code, unit_id)
SELECT v.code, u.id
FROM (VALUES
  (1, 'garmin_hr_zone_1_time', 's'),
  (2, 'garmin_hr_zone_2_time', 's'),
  (3, 'garmin_hr_zone_3_time', 's'),
  (4, 'garmin_hr_zone_4_time', 's'),
  (5, 'garmin_hr_zone_5_time', 's'),
  (6, 'garmin_training_effect_aerobic', 'index'),
  (7, 'garmin_training_effect_anaerobic', 'index'),
  (8, 'garmin_activity_training_load', 'index'),
  (9, 'garmin_activity_moving_time', 's'),
  (10, 'garmin_floors_descended', 'count'),
  (11, 'garmin_chronic_load_low', 'index'),
  (12, 'garmin_chronic_load_high', 'index'),
  (13, 'garmin_recovery_time', 'min'),
  (14, 'garmin_vo2max_cycling', 'mL/kg/min'),
  (15, 'garmin_hrv_baseline_low', 'ms'),
  (16, 'garmin_hrv_baseline_high', 'ms'),
  (17, 'garmin_hrv_baseline_floor', 'ms'),
  (18, 'garmin_metabolic_age', 'years'),
  (19, 'garmin_physique_rating', 'index'),
  (20, 'garmin_achievable_fitness_age', 'years'),
  (21, 'garmin_sweat_loss', 'mL'),
  (22, 'garmin_sleep_movement', 'index')
) AS v(ord, code, unit) JOIN units u ON u.code = v.unit
ORDER BY v.ord;

-- +goose Down
DELETE FROM metric_catalog WHERE code IN (
  'garmin_hr_zone_1_time',
  'garmin_hr_zone_2_time',
  'garmin_hr_zone_3_time',
  'garmin_hr_zone_4_time',
  'garmin_hr_zone_5_time',
  'garmin_training_effect_aerobic',
  'garmin_training_effect_anaerobic',
  'garmin_activity_training_load',
  'garmin_activity_moving_time',
  'garmin_floors_descended',
  'garmin_chronic_load_low',
  'garmin_chronic_load_high',
  'garmin_recovery_time',
  'garmin_vo2max_cycling',
  'garmin_hrv_baseline_low',
  'garmin_hrv_baseline_high',
  'garmin_hrv_baseline_floor',
  'garmin_metabolic_age',
  'garmin_physique_rating',
  'garmin_achievable_fitness_age',
  'garmin_sweat_loss',
  'garmin_sleep_movement');
