-- Seed of units and metric_catalog (J25.5). Generated by `go run ./internal/catalog/gen`; do not edit.
-- Codes added later get their own migration.

-- +goose Up
INSERT INTO units (code) VALUES
  ('steps/min');

INSERT INTO metric_catalog (code, unit_id)
SELECT v.code, u.id
FROM (VALUES
  (1, 'garmin_activity_avg_speed', 'm/s'),
  (2, 'garmin_activity_max_speed', 'm/s'),
  (3, 'garmin_activity_avg_power', 'W'),
  (4, 'garmin_activity_max_power', 'W'),
  (5, 'garmin_activity_norm_power', 'W'),
  (6, 'garmin_activity_running_cadence', 'steps/min'),
  (7, 'garmin_activity_running_cadence_max', 'steps/min'),
  (8, 'garmin_activity_cycling_cadence_max', 'rpm'),
  (9, 'garmin_activity_temperature_min', '°C'),
  (10, 'garmin_activity_temperature_max', '°C'),
  (11, 'garmin_activity_elevation_loss', 'm'),
  (12, 'garmin_activity_elevation_min', 'm'),
  (13, 'garmin_activity_elevation_max', 'm'),
  (14, 'garmin_activity_vertical_speed_max', 'm/s'),
  (15, 'garmin_activity_vertical_ratio', '%'),
  (16, 'garmin_activity_swolf', 'index'),
  (17, 'garmin_activity_body_battery_change', 'index'),
  (18, 'garmin_activity_power_zone_1_time', 's'),
  (19, 'garmin_activity_power_zone_2_time', 's'),
  (20, 'garmin_activity_power_zone_3_time', 's'),
  (21, 'garmin_activity_power_zone_4_time', 's'),
  (22, 'garmin_activity_power_zone_5_time', 's'),
  (23, 'garmin_activity_fastest_split_1000', 's'),
  (24, 'garmin_activity_fastest_split_1609', 's'),
  (25, 'garmin_activity_fastest_split_5000', 's'),
  (26, 'garmin_activity_fastest_split_10000', 's'),
  (27, 'garmin_activity_respiration_min', 'breaths/min'),
  (28, 'garmin_activity_respiration_max', 'breaths/min')
) AS v(ord, code, unit) JOIN units u ON u.code = v.unit
ORDER BY v.ord;

-- +goose Down
DELETE FROM metric_catalog WHERE code IN (
  'garmin_activity_avg_speed',
  'garmin_activity_max_speed',
  'garmin_activity_avg_power',
  'garmin_activity_max_power',
  'garmin_activity_norm_power',
  'garmin_activity_running_cadence',
  'garmin_activity_running_cadence_max',
  'garmin_activity_cycling_cadence_max',
  'garmin_activity_temperature_min',
  'garmin_activity_temperature_max',
  'garmin_activity_elevation_loss',
  'garmin_activity_elevation_min',
  'garmin_activity_elevation_max',
  'garmin_activity_vertical_speed_max',
  'garmin_activity_vertical_ratio',
  'garmin_activity_swolf',
  'garmin_activity_body_battery_change',
  'garmin_activity_power_zone_1_time',
  'garmin_activity_power_zone_2_time',
  'garmin_activity_power_zone_3_time',
  'garmin_activity_power_zone_4_time',
  'garmin_activity_power_zone_5_time',
  'garmin_activity_fastest_split_1000',
  'garmin_activity_fastest_split_1609',
  'garmin_activity_fastest_split_5000',
  'garmin_activity_fastest_split_10000',
  'garmin_activity_respiration_min',
  'garmin_activity_respiration_max');
DELETE FROM units WHERE code IN (
  'steps/min');
