-- Seed of units and metric_catalog (J25.5, J25.3). Generated by `go run ./internal/catalog/gen`; do not edit.
-- Codes added later get their own migration.

-- +goose Up
INSERT INTO units (code) VALUES
  ('strokes/min');

INSERT INTO metric_catalog (code, unit_id)
SELECT v.code, u.id
FROM (VALUES
  (1, 'garmin_activity_swim_cadence', 'strokes/min'),
  (2, 'garmin_activity_swim_cadence_max', 'strokes/min'),
  (3, 'garmin_activity_stroke_distance', 'm'),
  (4, 'garmin_activity_grade_adjusted_speed', 'm/s'),
  (5, 'garmin_activity_stress_avg', 'index'),
  (6, 'garmin_activity_stress_max', 'index'),
  (7, 'garmin_activity_stress_start', 'index'),
  (8, 'garmin_activity_stress_end', 'index'),
  (9, 'garmin_activity_sets_active', 'count'),
  (10, 'garmin_activity_sets_total', 'count'),
  (11, 'garmin_activity_reps_total', 'count'),
  (12, 'swim_laps', 'count')
) AS v(ord, code, unit) JOIN units u ON u.code = v.unit
ORDER BY v.ord;

-- +goose Down
DELETE FROM metric_catalog WHERE code IN (
  'garmin_activity_swim_cadence',
  'garmin_activity_swim_cadence_max',
  'garmin_activity_stroke_distance',
  'garmin_activity_grade_adjusted_speed',
  'garmin_activity_stress_avg',
  'garmin_activity_stress_max',
  'garmin_activity_stress_start',
  'garmin_activity_stress_end',
  'garmin_activity_sets_active',
  'garmin_activity_sets_total',
  'garmin_activity_reps_total',
  'swim_laps');
DELETE FROM units WHERE code IN (
  'strokes/min');
