//go:build integration

package db_test

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/KaanEmec/vitamux/internal/db"
	"github.com/KaanEmec/vitamux/internal/db/dbtest"
)

const updateSchemaDocEnv = "VITAMUX_UPDATE_SCHEMA_DOC"

// TestSchemaDoc keeps docs/schema/README.md in sync with the migrations. It is the CI drift check;
// regenerate with VITAMUX_UPDATE_SCHEMA_DOC=1.
func TestSchemaDoc(t *testing.T) {
	_, app := dbtest.Migrated(t)
	got, err := schemaDoc(context.Background(), app)
	if err != nil {
		t.Fatal(err)
	}
	_, file, _, _ := runtime.Caller(0)
	path := filepath.Join(filepath.Dir(file), "..", "..", "docs", "schema", "README.md")
	if os.Getenv(updateSchemaDocEnv) != "" {
		if err := os.WriteFile(path, []byte(got), 0o644); err != nil { //nolint:gosec // a committed doc
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if got != string(want) {
		gl, wl := strings.Split(got, "\n"), strings.Split(string(want), "\n")
		line := 0
		for line < len(gl) && line < len(wl) && gl[line] == wl[line] {
			line++
		}
		t.Fatalf("docs/schema/README.md is stale from line %d; run %s=1 go test -tags integration -run TestSchemaDoc ./internal/db", line+1, updateSchemaDocEnv)
	}
}

// schemaDoc renders the migrated schema from the catalogs. Everything is ordered by name and
// avoids version-specific output (e.g. PostgreSQL 18 NOT NULL constraints), so 17 and 18 agree.
func schemaDoc(ctx context.Context, pool *pgxpool.Pool) (string, error) {
	type table struct {
		oid        uint32
		name, desc string
		privileges string
	}
	tables, err := collect(ctx, pool, `
		SELECT c.oid, c.relname, coalesce(obj_description(c.oid, 'pg_class'), ''),
		       coalesce((SELECT string_agg(p, ', ' ORDER BY o) FROM unnest(ARRAY['SELECT', 'INSERT', 'UPDATE', 'DELETE', 'TRUNCATE'])
		                 WITH ORDINALITY AS t (p, o) WHERE has_table_privilege($2, c.oid, p)), 'none')
		FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
		WHERE n.nspname = $1 AND c.relkind IN ('r', 'p') AND c.relname <> 'goose_db_version'
		ORDER BY c.relname`,
		func(r pgx.CollectableRow) (tb table, err error) {
			err = r.Scan(&tb.oid, &tb.name, &tb.desc, &tb.privileges)
			return
		}, db.Schema, string(db.AppRole))
	if err != nil {
		return "", err
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# Database schema\n\n<!-- Generated by TestSchemaDoc in internal/db; do not edit. See docs/development.md. -->\n\n")
	fmt.Fprintf(&b, "Schema `%s` at migration %d. Design and rationale: [data-model.md](../architecture/data-model.md).\n\n", db.Schema, db.ExpectedVersion())
	b.WriteString("| Table | App role | Description |\n| --- | --- | --- |\n")
	for _, tb := range tables {
		fmt.Fprintf(&b, "| [%s](#%s) | %s | %s |\n", tb.name, tb.name, tb.privileges, cell(tb.desc))
	}

	for _, tb := range tables {
		fmt.Fprintf(&b, "\n## %s\n\n", tb.name)
		if tb.desc != "" {
			b.WriteString(tb.desc + "\n\n")
		}
		cols, err := collect(ctx, pool, `
			SELECT a.attname, format_type(a.atttypid, a.atttypmod), CASE WHEN a.attnotnull THEN 'no' ELSE 'yes' END,
			       CASE a.attidentity WHEN 'a' THEN 'identity (always)' WHEN 'd' THEN 'identity (by default)'
			            ELSE coalesce(pg_get_expr(d.adbin, d.adrelid), '') END,
			       coalesce(col_description(a.attrelid, a.attnum), '')
			FROM pg_attribute a LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
			WHERE a.attrelid = $1 AND a.attnum > 0 AND NOT a.attisdropped
			ORDER BY a.attnum`,
			func(r pgx.CollectableRow) (c [5]string, err error) {
				err = r.Scan(&c[0], &c[1], &c[2], &c[3], &c[4])
				return
			}, tb.oid)
		if err != nil {
			return "", err
		}
		b.WriteString("| Column | Type | Null | Default | Notes |\n| --- | --- | --- | --- | --- |\n")
		for _, c := range cols {
			fmt.Fprintf(&b, "| %s | %s | %s | %s | %s |\n", c[0], c[1], c[2], code(c[3]), cell(c[4]))
		}

		cons, err := collect(ctx, pool, `
			SELECT conname, pg_get_constraintdef(oid) FROM pg_constraint
			WHERE conrelid = $1 AND contype IN ('p', 'u', 'f', 'c', 'x')
			ORDER BY conname`,
			scanPair, tb.oid)
		if err != nil {
			return "", err
		}
		list(&b, "Constraints", cons)

		idx, err := collect(ctx, pool, `
			SELECT i.relname, CASE WHEN x.indisunique THEN 'UNIQUE ' ELSE '' END
			       || substring(pg_get_indexdef(i.oid) FROM ' USING (.*)$')
			FROM pg_index x JOIN pg_class i ON i.oid = x.indexrelid
			WHERE x.indrelid = $1 AND NOT EXISTS (SELECT FROM pg_constraint c
			      WHERE c.conrelid = x.indrelid AND c.conindid = x.indexrelid AND c.contype IN ('p', 'u', 'x'))
			ORDER BY i.relname`,
			scanPair, tb.oid)
		if err != nil {
			return "", err
		}
		list(&b, "Indexes", idx)
	}
	return b.String(), nil
}

func collect[T any](ctx context.Context, pool *pgxpool.Pool, sql string, scan func(pgx.CollectableRow) (T, error), args ...any) ([]T, error) {
	rows, err := pool.Query(ctx, sql, args...)
	if err != nil {
		return nil, err
	}
	return pgx.CollectRows(rows, scan)
}

func scanPair(r pgx.CollectableRow) (c [2]string, err error) {
	err = r.Scan(&c[0], &c[1])
	return
}

func list(b *strings.Builder, title string, items [][2]string) {
	if len(items) == 0 {
		return
	}
	fmt.Fprintf(b, "\n%s:\n\n", title)
	for _, it := range items {
		fmt.Fprintf(b, "- `%s`: `%s`\n", it[0], it[1])
	}
}

func cell(s string) string { return strings.ReplaceAll(s, "|", `\|`) }

func code(s string) string {
	if s == "" {
		return ""
	}
	return "`" + cell(s) + "`"
}
