// Command apiref writes docs/api-reference.md, the operation list of api/openapi.yaml grouped by
// tag, with the access each operation has in api/authz.yaml. Run it from the repository root:
//
//	go run ./tools/apiref
//
// TestDocIsCurrent fails when the committed file differs from what this renders.
package main

import (
	"errors"
	"fmt"
	"os"
	"slices"
	"strings"

	"gopkg.in/yaml.v3"
)

const (
	specPath  = "api/openapi.yaml"
	authzPath = "api/authz.yaml"
	docPath   = "docs/api-reference.md"
)

var methods = []string{"get", "put", "post", "patch", "delete", "head", "options"}

func main() {
	doc, err := renderFiles(specPath, authzPath)
	if err == nil {
		err = os.WriteFile(docPath, []byte(doc), 0o644) //nolint:gosec // repository file, not a secret
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "apiref:", err)
		os.Exit(1)
	}
}

func renderFiles(spec, authz string) (string, error) {
	s, err := os.ReadFile(spec) //nolint:gosec // fixed repository paths
	if err != nil {
		return "", err
	}
	a, err := os.ReadFile(authz) //nolint:gosec // fixed repository paths
	if err != nil {
		return "", err
	}
	return render(s, a)
}

type access struct {
	Allow   string `yaml:"allow"`
	CSRF    bool   `yaml:"csrf"`
	Planned bool   `yaml:"planned"`
}

type operation struct {
	method, path, summary string
}

// render keeps the spec's order of tags, paths and methods, so the document follows the spec.
func render(spec, authz []byte) (string, error) {
	var a struct {
		Routes map[string]access `yaml:"routes"`
	}
	if err := yaml.Unmarshal(authz, &a); err != nil {
		return "", fmt.Errorf("%s: %w", authzPath, err)
	}
	var root yaml.Node
	if err := yaml.Unmarshal(spec, &root); err != nil {
		return "", fmt.Errorf("%s: %w", specPath, err)
	}
	if len(root.Content) == 0 {
		return "", fmt.Errorf("%s: empty", specPath)
	}
	doc := root.Content[0]

	type tag struct{ name, desc string }
	var tags []tag
	for _, t := range get(doc, "tags").Content {
		tags = append(tags, tag{scalar(get(t, "name")), scalar(get(t, "description"))})
	}
	byTag := map[string][]operation{}
	var errs []error
	paths := get(doc, "paths")
	for i := 0; i+1 < len(paths.Content); i += 2 {
		path, item := paths.Content[i].Value, paths.Content[i+1]
		for j := 0; j+1 < len(item.Content); j += 2 {
			method := item.Content[j].Value
			if !slices.Contains(methods, method) {
				continue // parameters, summary, ...
			}
			op := item.Content[j+1]
			t := get(op, "tags")
			if t == nil || len(t.Content) == 0 {
				errs = append(errs, fmt.Errorf("%s %s: no tag", strings.ToUpper(method), path))
				continue
			}
			name := t.Content[0].Value
			byTag[name] = append(byTag[name], operation{strings.ToUpper(method), path, scalar(get(op, "summary"))})
		}
	}

	var b strings.Builder
	b.WriteString("# API reference\n\n")
	b.WriteString("Generated by `go run ./tools/apiref` from [`api/openapi.yaml`](../api/openapi.yaml) (the contract: parameters, bodies, responses) and [`api/authz.yaml`](../api/authz.yaml); do not edit. Conventions such as authentication, pagination, errors and idempotency are in [architecture/api.md](architecture/api.md).\n\n")
	b.WriteString("Access: `public` needs no credentials (an OAuth state or hook token authorizes it), `session` is the owner's browser session only, `client` is a client or device token for its own connection, and a scope admits the owner's session or an API key with that scope or `admin`. *CSRF*: a session request must send `X-CSRF-Token`. *Planned*: in the spec, not served yet (404).\n")
	seen := map[string]bool{}
	for _, t := range tags {
		ops := byTag[t.name]
		seen[t.name] = true
		if len(ops) == 0 {
			continue
		}
		fmt.Fprintf(&b, "\n## %s\n\n", t.name)
		if t.desc != "" {
			fmt.Fprintf(&b, "%s\n\n", t.desc)
		}
		b.WriteString("| Method | Path | Access | Summary |\n| --- | --- | --- | --- |\n")
		for _, o := range ops {
			key := o.method + " " + o.path
			ac, ok := a.Routes[key]
			if !ok {
				errs = append(errs, fmt.Errorf("%s: not in %s", key, authzPath))
				continue
			}
			who := "`" + ac.Allow + "`"
			if ac.CSRF {
				who += ", CSRF"
			}
			if ac.Planned {
				who += ", planned"
			}
			fmt.Fprintf(&b, "| `%s` | `%s` | %s | %s |\n", o.method, o.path, who, cell(o.summary))
		}
	}
	for name := range byTag {
		if !seen[name] {
			errs = append(errs, fmt.Errorf("tag %q is used but not declared", name))
		}
	}
	return b.String(), errors.Join(errs...)
}

// get returns the value of key in a mapping node, or nil.
func get(n *yaml.Node, key string) *yaml.Node {
	if n == nil || n.Kind != yaml.MappingNode {
		return nil
	}
	for i := 0; i+1 < len(n.Content); i += 2 {
		if n.Content[i].Value == key {
			return n.Content[i+1]
		}
	}
	return nil
}

func scalar(n *yaml.Node) string {
	if n == nil {
		return ""
	}
	return strings.Join(strings.Fields(n.Value), " ")
}

func cell(s string) string { return strings.ReplaceAll(s, "|", `\|`) }
